### ISSUE TITLE
weather map integration

### ISSUE THREAD

**Issue by alialshaqah** [TUDelft-CNS-ATM/bluesky#115]
Hi Guys,
I need to integrate the weather data and visualize it with blue sky interface, how I can do such thing.

**Comment by jooste** [comment]
Hi! What kind of weather data would you want to visualize? Wind fields, or weather cells? The first could be a set of gl lines, whereas the second probably requires a texture. Also important, of course, is where you want to get the weather data from: should it be actual historical data, or generated? We already have a windfield model in BlueSky, although it is not visualized on the gui yet.

**Comment by jooste** [comment]
Ok, I would then implement this as a textured surface. There are a couple of steps involved.
The simulation and the gui are decoupled in BlueSky, and communicate through TCP. The weather data would be loaded as part of a simulation scenario, and then sent to the gui for visualization.
The required additions to bluesky would be:
1. Code that loads weather data from a file, which can be called from the BlueSky command stack (this can be done in a plugin)
2. Code that sends this data from the sim to the gui, and on the gui side some additions to be able to receive the data
3. Code on the gui side to 
    - create a textured rectangle
    - draw the rectangle
    - upload the incoming weather data to the GPU's memory as a texture.
Step 1 is relatively straightforward, especially if you make this into a plugin. Step 3 would be straightforward if we already had gui-side plugins :) This might be a nice reason to start making them.. Step 2 is a bit cumbersome in the current main version, but should be easier in the version under development in the bluesky-zmq branch.
