### ISSUE TITLE
NEA WPT name is duplicated, is a fix name but also a VOR/DME

### ISSUE THREAD

**Issue by javiergarciaheras** [TUDelft-CNS-ATM/bluesky#172]
Hello,

I was creating FPL from EHAM to LEMD and after adding NENEM WPT I wanted to include VOR/DME NEA but instead I turn into a FIX called the same. I was checking this issue and I realised that in the fix.dat folder we have  43.737500 -001.023055 NEA but it is also in the nav.dat file where we have 3  42.02760800 -004.10913100   3002 11675  40   -2.5 NEA  TABANERA VOR-DME (the one I wanted).

Also, I tried to create the FPL LEMD-EHAM (to be closer to the VOR/DME WPT when I add NEA WPT) and the one I am getting is the VOR/DME WPT.

I think NEA FIX should be removed.

**Comment by ProfHoekstra** [comment]
Dear Javier,

In case of duplicate names (there are many!) the one closest to reference position is taken. This is normally aircraft position. Check to code to see how you can influence the reference position, e.g. by temporarily moving the aircraft. We will think about using another way to determine the most suitable for flight plans, e.g closest to last addition in route, and then fix this.

Thanks.

Best regards,
    Jacco Hoekstra

**Comment by ProfHoekstra** [comment]
VOR NEA removed from file with non-beacon fixes
