### ISSUE TITLE
Logging conflicts

### ISSUE THREAD

**Issue by colineRamee** [TUDelft-CNS-ATM/bluesky#178]
Hi,
I am trying to use Bluesky for research on urban air mobility, but I am having some issues figuring out how to get started and I would really appreciate some help. 
The first thing I'd like to measure is conflicts (number, length, severity), but I can't figure out how to log them. 
I've looked at the wiki and didn't find much details on logging. Looking at area.py it's pretty clear how to log some information at the end of the flight, but I am not really sure how it could be extended for conflicts. Is there already a way to log conflicts that i have missed? 
Otherwise I saw that asas keeps track of conflicts and deletes them once the CPA is passed, is there a way to save the conflict details at that moment?
Thanks for the help!

**Comment by jooste** [comment]
Hi,
There are logging facilities in bluesky, but its a work in progress to make logging more user-friendly. So far, there is the datalogger in bluesky.tools, which can be used in bluesky's code to implement loggers. This has been done for different attributes in different forks of bluesky. look [here](https://github.com/eman89/bluesky/tree/Project3StabilityCapacity) for instance for an extensive implementation of a conflict logger.

The plan is to make this much easier by making it possible to define loggers in a scenario file, so no need anymore to dive into the source code. Depending on how much of a hurry you are in you can wait for that, or copy what you need from the fork I mentioned above.

**Comment by Torgenn** [comment]
Thanks a lot @jooste ! I'll try to use what @eman89 did.
