### ISSUE TITLE
snaplog command doesn't 

### ISSUE THREAD

**Issue by davidlinardy** [TUDelft-CNS-ATM/bluesky#181]
![snaplog](https://user-images.githubusercontent.com/47732343/54279037-9bb9d880-45c6-11e9-8574-b94ccaa2d388.jpg)

**Comment by davidlinardy** [comment]
i've also tried to write down the snaplog command in my .py file and it is still read as an unknown command but the other commands work well

**Comment by jooste** [comment]
Hi David,

I'll paste the same comment as in the other thread here:

It depends what you want to log. To periodically log data (most often aircraft states), you can create a logger using the CRELOG command. For example:

    CRELOG MYLOG 1.0
    MYLOG ADD lat, lon, alt, tas, gs, hdg, asas.inconf
    MYLOG ON

would create a periodic logger that logs once per second the variables `lat`, `lon`, `alt`, `tas`, `gs`, `hdg`, `asas.inconf`

**Comment by jooste** [comment]
This syntax has replaced the hard-coded periodic loggers like `SNAPLOG`.

**Comment by davidlinardy** [comment]
Hi Jooste, 

so the logname is the same as my file name? or just the output name?
if my file name is test123.SCN, it will be

CRELOG test123
MYLOG  ADD lat, lon, alt, tas, gs, hdg, asas.inconf
MYLOG on?

**Comment by davidlinardy** [comment]
HI Jooste,

the CRELOG is working but if i have 3 aircraft defined in my simulation, which aircraft data is shown in the output?

**Comment by ProfHoekstra** [comment]
Add id to the variables that you log and you can recognize which aircraft the line is for:


CRELOG MYLOG 1.0

MYLOG ADD id, lat, lon, alt, tas, gs, hdg, asas.inconf

MYLOG ON

**Comment by jooste** [comment]
Documentation for logging is now available on the [wiki](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Data-Logging).
