### ISSUE TITLE
aircraft landing problem

### ISSUE THREAD

**Issue by davidlinardy** [TUDelft-CNS-ATM/bluesky#182]
Can i remove the aircraft that has landed ? and why the speed never become 0 after reaching the airport? only the altitude.

is it possible for me to use the sectorcount plugin to count every aircraft that has landed? i need it to count the capacity of the airport.

thank you

**Comment by andubadea** [comment]
Hello! In order to have aircraft de-spawn when they reach their destination, you must put the command "taxi off" at the beginning of the simulation. This makes aircraft de-spawn when they go below 1500 ft at their destination. The 1500ft level can be changed like this: taxi off 2000 makes the aircraft de-spawn at 2000 ft.

**Comment by jooste** [comment]
Hi David,

I guess you could use the sectorcount plugin with a very flat sector covering your airport or runway. That way you count all the aircraft just before they land on your airport. You can also make your own plugin of course!

**Comment by davidlinardy** [comment]
Hi Andubadea,

thanks for the input, it works well

**Comment by davidlinardy** [comment]
Hi jooste, 

i still have some problem in defining the parameter/argument to use together with the sectorcount command. Can use please give me some example? because some plugins don't have the explanation in the wiki. Besides, i still new to this language so it is hard to understand from the code.

thank you.

**Comment by jooste** [comment]
Hi David,

If you have the sectorcount plugin loaded you can do the following:

    POLY mypoly lat0,lon0,lat1,lon1, ..., latn, lonn
    SECTORCOUNT ADD mypoly

With the above you first define a polygonal area (called myname), which you then pass to the sectorcount plugin to use for counting. The plugin then prints to the bluesky console how many aircraft enter and leave the area each plugin timestep, and how many are inside. The last of these variables it also logs in a file.

**Comment by davidlinardy** [comment]
![sectrcount](https://user-images.githubusercontent.com/47732343/54416644-97aac980-4732-11e9-82ab-ed1b45a2a1dc.jpg)

Hi Jooste, 

The program still read the sectorcount as an unknown command. Here is my code:

0:00:00.00>PCALL NEWWAYPT

 00:00:00.00>symbol

 00:00:00.00>LOAD PLUGIN SECTORCOUNT
 00:00:00.00>POLY mypoly1 -6.1425,106.64277,-6.1425,106.6429,-6.14337,106.64368,-6.143418,106.643155
 00:00:00.00>SECTORCOUNT ADD mypoly1

 0:00:00.00>PAN NOKTA
 0:00:00.00>CRE DL001,B737,-4.861666,106.62333,155,FL290,250
 0:00:00.00>CRE DL002,B737,-5.260277,106.21333,107,FL290,250
 0:00:00.00>CRE DL003,B737,-5.197222,107.60666,249,FL310,250

 0:00:00.00>CRELOG DATASIM 2.0
 0:00:00.00>DATASIM ADD ID, ALT, LAT, LON, TAS, HDG
 0:00:00.00>DATASIM ON
...
...
...

is there anything wrong with my code?

thank you

**Comment by jooste** [comment]
Ok, to load a plugin you have to do:
    PLUGINS LOAD SECTORCOUNT
