### ISSUE TITLE
BADA has a bug in the mass calculation

### ISSUE THREAD

**Issue by MTMesfum** [TUDelft-CNS-ATM/bluesky#185]
Hi,

When an aircraft is initialised, a considerate amount of mass is lost due to timestep -1/0 (?).
This has severe implications for fuel consumption calculations and I assume for the aircraft simulation as well.
This mass loss is dependent on the spawn time of the aircraft and the way perfbada handles the first timestep.

This snip shows the mass of the aircraft as it moves through the simulation:

![image](https://user-images.githubusercontent.com/46937551/55399218-cc988800-554a-11e9-8030-a49a301f9963.png)

![image](https://user-images.githubusercontent.com/46937551/55399350-27ca7a80-554b-11e9-8152-f62753d209f4.png)

![image](https://user-images.githubusercontent.com/46937551/55399392-4b8dc080-554b-11e9-869d-c8bb51c1a831.png)

It can be seen that dt_act at the first timestep equals the simulation time.
This means that when an aircraft spawns at 10:00 it will be assumed that it has flown for 10 hours.
This creates a significant mass loss.
When BlueSky uses the same settings for a batch simulation, the first aircraft (1.1) will have vastly different results when compared to aircraft 1.2 & 1.3 in parallel simulations.
Aircraft 1.2 and 1.3 will show identical fuel consumptions.
When a second aircraft spawns in the same simulation, the same problem occurs.
Aircraft 2.1 will be vastly different from the identical values for 2.2 and 2.3.
This can be seen in the excel-snip below:

![image](https://user-images.githubusercontent.com/46937551/55399888-abd13200-554c-11e9-8bcf-871542c0a369.png)

Also, the aircrafts spawn 1 to 2 seconds before they actually should.
I'm not sure if this is intended and just want to mention it.
It's not something that poses a problem.

If I understand the structure and intention of the code properly, I would suggest the following solution:

![image](https://user-images.githubusercontent.com/46937551/55400772-13887c80-554f-11e9-8cc1-fabeba6e2857.png)

This provides the following results:

![image](https://user-images.githubusercontent.com/46937551/55400969-9a3d5980-554f-11e9-9859-28c0359e629c.png)

The dt_act value is forced to be equal to the simulation timestep during the first timestep.
The resulting fuel consumption should be insignificant and shouldn't affect the results.
I wouldn't set it to 0 because the aircraft does move from the moment it spawns.
Afterwards dt_act seems to be locked on 1.0 even though the simulation uses a 0.1 update rate.
This is probably because the bada plugin uses its own update rate.
The results seem to be consistent with fuel usages of the A320.

However, it can be seen that simulation 1 is ahead by 1 timestep over simulation 2 and 3.
Since the update rate of my wind fields is significantly lower, it shouldn't pose a problem for my simulations.
Although, it might be of interest for others.

**Comment by MTMesfum** [comment]
Unfortunately, the changes still lead to a significant impact on the fuel consumption:

![image](https://user-images.githubusercontent.com/46937551/55408484-5d2d9300-5560-11e9-8e15-4ba2985525f5.png)

I've noticed that aircraft 3.1 shows abnormal behaviour, especially when compared to the other aircrafts.
The other 6 sibling-aircrafts do show uniform behaviour.
The behaviour is captured in the following screenshots;

![image](https://user-images.githubusercontent.com/46937551/55408453-4dae4a00-5560-11e9-9b43-5b2b5d140770.png)

![image](https://user-images.githubusercontent.com/46937551/55408425-425b1e80-5560-11e9-8a60-1b405846c56b.png)

I don't really know why this happens, but the aircraft seems to be "stuck" on the ground.
It stays on the same altitude and position until a certain speed is met.
After the speed threshold is met, the aircraft climbs and follows its intended trajectory.

**Comment by jooste** [comment]
Hi,

Actually, the perfbada is high on the list for a re-write, or at least a very careful look. 

I'm also interested in your remark regarding the creation time being off. How did you determine this? Did you print sim.simt? Do you have a minimal test scenario to reproduce this?

**Comment by MTMesfum** [comment]
Hi Joost,

How did you determine this? 
I printed the mass of the aircraft at different instances in the program within one update.
The mass initiates at 64000, but after the first update it ends up at ~63000 or ~53000 kg due to the spawntime of my aircrafts.

Did you print sim.simt?
I printed self.simt within perf.bada. 
This should be the same variable.

Do you have a minimal test scenario to reproduce this?
You can try to recreate the problem, however my version of BlueSky is modified considerably by now.
I wrote the changes at the bottom of this comment.

If it doesn't work, I can pass by your office and show it on my laptop (even though it's a slow one).
Or I can help implement the changes on your system.
I've got some other questions as well.

______________________________________________________________________________________________________________

These are my batch and scenario files:

[Trajectories.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3035351/Trajectories.txt)

[Trajectories-batch.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3035356/Trajectories-batch.txt)

Then change some portions of perf.bada;

1) The first part of the if-statement should look as follows (line 340 onwards);

![image](https://user-images.githubusercontent.com/46937551/55426204-7ea07600-5584-11e9-80fa-065b6a213b60.png)

    def perf(self, simt):
        if simt - self.t0 >= self.dt:
            # Actual dt can vary due to float roundoff errors
            print('simt is 1 : ', simt)
            print('self.t0 is 1: ', self.t0)
            print('dt_act is 1: ',dt_act)
            dt_act = simt - self.t0
            if dt_act > simt:
                dt_act = -self.t0
            self.t0 = simt
            print('simt is: ', simt)
            print('self.t0 is: ', self.t0)
            print('dt_act is: ',dt_act)

2) The update mass section will change to line 567 and should look as follows;

![image](https://user-images.githubusercontent.com/46937551/55426341-d6d77800-5584-11e9-8819-bee7f09660e3.png)

        # update mass
        print('mass in perfbada 1 is: ', self.mass)
        print('self.ff is: ', self.ff)
        print('dt_act is: ', dt_act)
        self.mass = self.mass - self.ff * dt_act  # Use fuelflow in kg/min
        print('mass in perfbada 2 is: ', self.mass)

I run these files in conjunction with my own datalogger plugin:

[datalogger.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3035389/datalogger.txt)

Also, make sure to change the folders to ones that exist on your pc in the batch file.
I'm not sure if it will work on your end even when you add all these files and changes.
But if it does work, you should see the following printed out during the simulation;
the mass at; pre-update, update, creation (during create function), before and after mass calculation
the dt_act, self.t0 and self.ff at; before and after dt_act calculation, before mass calculation

**Comment by MTMesfum** [comment]
Hi Joost,

Can you commit a settings file to BlueSky as well?
The program can't be started without it.

**Comment by jooste** [comment]
This should not be necessary. But while double checking I did notice a typo in the openap performance module, which I fixed. This may be what you ran into.

**Comment by MTMesfum** [comment]
I'm stuck on this error;

![image](https://user-images.githubusercontent.com/46937551/55824625-81f7ac80-5b04-11e9-842d-003e34e7e2dc.png)

Not really sure what could cause it.
We can have a look at it tomorrow.

**Comment by jooste** [comment]
This was fixed in 80c0107.
