### ISSUE TITLE
SPD bug

### ISSUE THREAD

**Issue by rjdverbeek** [TUDelft-CNS-ATM/bluesky#188]
Hi Joost,

Under certain conditions a flight being provided with a large speed (beyond max speed) the speed will reduce to the minimum. The following scenario will replicate this bug.

`
00:00:00.00>CRE KLM123 B744 52.226492 1.889584 90 36000 300
`
`
00:00:09.75>spd klm123 400
`

I think the following is happening. With a very large CAS the resulting Mach number will be above 1. When having a Mach above 1 this is interpreted as a CAS within BlueSky and not as a Mach number. So BlueSky thinks the desired CAS has become 1.05 kts and reduces the speed in stead of setting the speed to max.

Wkr,
René

**Comment by jooste** [comment]
Hi René,

This is fixed in 98d3310: the automatic switch between constant-CAS and constant-Mach based on altitude was removed.
