### ISSUE TITLE
Enhancement Route.py

### ISSUE THREAD

**Issue by rjdverbeek** [TUDelft-CNS-ATM/bluesky#190]
Hi Joost,

I have build a plugin with enhanced fms functionality. Implementing the plugin I had the problem that I wanted to store additional information for the fms functionality in the route dataset. In this way I wouldn't need to keep track of a separate list of waypoints next to the list already available in Bluesky. I made this work by extending the route class after runtime.
The only way I could make this work, was if I made a small change to the route.py that would be backwards compatible, but also would allow for the enhancement of the route class through the plugin.

So my question to you is if you add the following change to the master Bluesky such that the enhanced fms functionality becomes compatible with future Bluesky versions. The change I am suggesting is setup such that it should be backwards compatible (I only take a number of steps from a module and put them in a separate module that is called from the original module). With this addition I am able to make my plugin available for general use.

Route.py row 821

```
# NEW LOCAL DEL MODULE THAT IS CALLED BY DELWPT
def _del_wpt_data(self, idx):
	del self.wpname[idx]
	del self.wplat[idx]
	del self.wplon[idx]
	del self.wpalt[idx]
	del self.wpspd[idx]
	del self.wptype[idx]

def delwpt(self,delwpname,iac=None):
        """Delete waypoint"""

        # Delete complete route?
        if delwpname =="*":
            return self.delrte(iac)

        # Look up waypoint
        idx = -1
        i = len(self.wpname)
        while idx == -1 and i > 0:
            i -= 1
            if self.wpname[i].upper() == delwpname.upper():
                idx = i

        # Delete waypoint
        if idx == -1:
            return False, "Waypoint " + delwpname + " not found"

        self.nwp =self.nwp - 1
	# REPLACED SEPARATE DEL FUNCTIONS WITH SINGLE DEL FUNCTION THAT CALLS ALL DELLS
        #del self.wpname[idx]
        #del self.wplat[idx]
        #del self.wplon[idx]
        #del self.wpalt[idx]
        #del self.wpspd[idx]
        #del self.wptype[idx]
		self._del_wpt_data(idx)  # NEW LINE
		
        if self.iactwp > idx:
            self.iactwp = max(0, self.iactwp - 1)

        self.iactwp = min(self.iactwp, self.nwp - 1)

        # If no waypoints left, make sure to disable LNAV/VNAV
        if self.nwp==0 and (iac or iac==0):
            bs.traf.swlnav[iac]    =  False
            bs.traf.swvnav[iac]    =  False
            bs.traf.swvnavspd[iac] =  False

        return True
```

**Comment by rjdverbeek** [comment]
Once this is available in Bluesky I am able to do the following through the plugin to enhance the Route class:

```
old_route_init = Route.__init__
def new_route_init(self, *k, **kw):
    old_route_init(self, *k, **kw)
    self.wprta = []  # [s] Required Time of Arrival to WPT

Route.__init__ = new_route_init
old_route_addwpt_data = Route.addwpt_data

def new_route_addwpt_data(self, overwrt, wpidx, *k, **kw):
    old_route_addwpt_data(self, overwrt, wpidx, *k, **kw)
    if overwrt:
        self.wprta[wpidx] = -1.  # negative indicates no rta
    else:
        self.wprta.insert(wpidx, -1.)  # negative indicates no rta

Route.addwpt_data = new_route_addwpt_data
old_route_del_wpt_data = Route._del_wpt_data

def new_del_wpt_data(self, wpidx):
    old_route_del_wpt_data(self, wpidx)
    del self.wprta[wpidx]

Route._del_wpt_data = new_del_wpt_data
```
In this way the stack functions for adding, updating and deleting waypoints remain functional for the standard waypoint data and also works likewise on the enhanced waypoint data.

**Comment by ProfHoekstra** [comment]
Hi Joost,

Lijkt me prima voorstel, ik verwacht inderdaad geen probleem of interferentie met bestaande code op deze manier.

Met vriendelijke groeten,
    Jacco Hoekstra


On 1 May 2019, at 11:11, rjdverbeek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Joost,

I have build a plugin with enhanced fms functionality. Implementing the plugin I had the problem that I wanted to store additional information for the fms functionality in the route dataset. In this way I wouldn't need to keep track of a separate list of waypoints next to the list already available in Bluesky. I made this work by extending the route class after runtime.
The only way I could make this work, was if I made a small change to the route.py that would be backwards compatible, but also would allow for the enhancement of the route class through the plugin.

So my question to you is if you add the following change to the master Bluesky such that the enhanced fms functionality becomes compatible with future Bluesky versions. The change I am suggesting is setup such that it should be backwards compatible (I only take a number of steps from a module and put them in a separate module that is called from the original module). With this addition I am able to make my plugin available for general use.

Route.py row 821

# NEW LOCAL DEL MODULE THAT IS CALLED BY DELWPT
def _del_wpt_data(self, idx):
        del self.wpname[idx]
        del self.wplat[idx]
        del self.wplon[idx]
        del self.wpalt[idx]
        del self.wpspd[idx]
        del self.wptype[idx]

def delwpt(self,delwpname,iac=None):
        """Delete waypoint"""

        # Delete complete route?
        if delwpname =="*":
            return self.delrte(iac)

        # Look up waypoint
        idx = -1
        i = len(self.wpname)
        while idx == -1 and i > 0:
            i -= 1
            if self.wpname[i].upper() == delwpname.upper():
                idx = i

        # Delete waypoint
        if idx == -1:
            return False, "Waypoint " + delwpname + " not found"

        self.nwp =self.nwp - 1
        # REPLACED SEPARATE DEL FUNCTIONS WITH SINGLE DEL FUNCTION THAT CALLS ALL DELLS
        #del self.wpname[idx]
        #del self.wplat[idx]
        #del self.wplon[idx]
        #del self.wpalt[idx]
        #del self.wpspd[idx]
        #del self.wptype[idx]
                self._del_wpt_data(idx)  # NEW LINE

        if self.iactwp > idx:
            self.iactwp = max(0, self.iactwp - 1)

        self.iactwp = min(self.iactwp, self.nwp - 1)

        # If no waypoints left, make sure to disable LNAV/VNAV
        if self.nwp==0 and (iac or iac==0):
            bs.traf.swlnav[iac]    =  False
            bs.traf.swvnav[iac]    =  False
            bs.traf.swvnavspd[iac] =  False

        return True

**Comment by jooste** [comment]
Hi René,

I like the idea of making more parts of bluesky (such as the route implementation) more extensible, but I'd rather use inheritance than this kind of monkey-patching, which, in my opinion, is not the most beautiful 'feature' of Python ;)

Basically my plan is to enable plugins to extend basically any part of bluesky. I will think on this a bit more to get to a flexible approach! I'll keep you posted.

**Comment by rjdverbeek** [comment]
Hi Joost,

You are right. This is not the most beautiful solution. But it helped me
not changing your original code.

Good luck with finding a way to make also the route implementation
extensible.

Wkr. René

Op vr 3 mei 2019 om 15:38 schreef Joost Ellerbroek <notifications@github.com

**Comment by jooste** [comment]
Hi René,

In b3d103b and several following commits I've implemented the possibility for plugins to subclass most classes in BlueSky. If that plugin is loaded the newly defined implementation becomes visible, and can be selected via a stack command. This way, all functions can be adapted through regular inheritance. For your example this would be something like:

    from bluesky.traffic import Route
    
    class MyRoute(Route):
        def __init__(self):
            super().__init__()
            # my initialisation here

        def delwpt(self,delwpname,iac=None):
            success = super().delwpt(delwpname, iac)
            # do something with your own data
            return success

Load this plugin, and select your new implementation via the stack as follows:

    IMPL route myroute
