### ISSUE TITLE
Logging of traffic variables with capital letters

### ISSUE THREAD

**Issue by rjdverbeek** [TUDelft-CNS-ATM/bluesky#191]
Hi Joost,

When I try to use the CRELOG functionality I am not able to log variables that have capital letters.

Examples (using bada):
This works:
MYLOG ADD traf.alt
MYLOG ADD traf.perf.fuelflow

This does not work:
MYLOG ADD traf.M
Syntax error: MYLOG: Variable TRAF.M not found
MYLOG ADD traf.perf.Thr
Syntax error: MYLOG: Variable TRAF.PERF.THR not found

Wkr, René

**Comment by rjdverbeek** [comment]
Hi Joost,

This is my own solution for making the logger work with case sensitive letters. The problem is in the varexplorer.

I added the following class to the varexplorer.py which takes a dictionary and makes it case insensitive when searching the dictionary
```
from collections import Mapping

class CaseInsensitiveDict(Mapping):
    def __init__(self, d):
        self._d = d
        self._s = dict((k.lower(), k) for k in d)
    def __contains__(self, k):
        return k.lower() in self._s
    def __len__(self):
        return len(self._s)
    def __iter__(self):
        return iter(self._s)
    def __getitem__(self, k):
        return self._d[self._s[k.lower()]]
    def actual_key_case(self, k):
        return self._s.get(k.lower())
```

and updated line 102 and 103 in the following way:
```
if obj and name in CaseInsensitiveDict(vars(obj)):
     return Variable(obj, varset[-2][0], CaseInsensitiveDict(vars(obj)).actual_key_case(name), index)
```

I don't know if this solution will generate a speed hit.

**Comment by jooste** [comment]
Hi René,

I've solved it somewhat differently, by adding a case-sensitive 'word' argument type. You can now distinguish, e.g., between traf.M and traf.m. See 93fdd6b.
