### ISSUE TITLE
Airport editing

### ISSUE THREAD

**Issue by TheoHabenicht** [TUDelft-CNS-ATM/bluesky#195]
Is it possible to edit the existing layouts of airports, or create new ones, to do some capacity studies for runways?

**Comment by jooste** [comment]
Dear Theo,

Yes, it's possible to change the visual databases. BlueSky uses x-plane data for this. You can use x-plane's world editor to adapt these files: [http://developer.x-plane.com/tools/worldeditor/](http://developer.x-plane.com/tools/worldeditor/).

**Comment by TheoHabenicht** [comment]
Hello jooste,
thank you very much!
