### ISSUE TITLE
Bug: HDG command accuracy depends on simulation time step size

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#196]
The result of the HDG command seems to depend on the size of the timestep used for the simulation. For small time steps the final heading is equal (or at least close) to the value commanded by the user, however for larger time steps the final heading can differ from the commanded heading by multiple degrees.

The following scenario results in a final heading of 090 degrees (rounded to the nearest integer). 
```
0:00:00.00>PAN 0.0,0.0
0:00:00.00>DT 0.05
0:00:00.00>CRE AC001 B744,0,0,360,36000,280
0:00:00.00>HDG AC001 090
```

The next scenario results in a final heading of 088 degrees (rounded to the nearest integer). 
```
0:00:00.00>PAN 0.0,0.0
0:00:00.00>DT 0.5
0:00:00.00>CRE AC001 B744,0,0,360,36000,280
0:00:00.00>HDG AC001 090
```

And this scenario results in a final heading of 087 degrees (rounded to the nearest integer). 
```
0:00:00.00>PAN 0.0,0.0
0:00:00.00>DT 1.0
0:00:00.00>CRE AC001 B744,0,0,360,36000,280
0:00:00.00>HDG AC001 090
```

**Comment by jooste** [comment]
Thanks! fixed in 18f8346.
