### ISSUE TITLE
Bug: Compiled geo module does not seem to be used after importing it

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#197]
When attempting to  use the compiled geo and asas modules I noticed that my simulations did not seem to experience any speed gains. After putting some print statements in geo.py and ~~StatebasedCD.py~~ it seems that even with `prefer_compiled` set to True the functions defined in these files are still executed every time step. 

On initialization BlueSky prints "_Using compiled geo functions_" ~~and "_StateBasedCD: using compiled version._"~~ to the console as expected. The import code is thus executed, but the result is not as it should be. After the import statements, printing the geo related (key : value) pairs in `sys.modules` gives the following result:

```
bluesky.tools : <module 'bluesky.tools' from 'C:\\Users\\Ruben\\Code\\Python\\bluesky\\bluesky\\tools\\__init__.py'>
bluesky.tools.src_cpp : <module 'bluesky.tools.src_cpp' (namespace)>
bluesky.tools.src_cpp.cgeo : <module 'bluesky.tools.src_cpp.cgeo' from 'C:\\Users\\Ruben\\Code\\Python\\bluesky\\bluesky\\tools\\src_cpp\\cgeo.cp36-win_amd64.pyd'>
```
Somehow using `from bluesky.tools import geo` will result in importing the native Python version instead of the compiled version which exists in a separate namespace. My guess is that this is caused by the fact that for versions >3.3 the import system in Python can import modules inside a folder even without an ` __init__.py` file (or bypassing an existing one...)

~~After some testing it seems that this issue can be resolved by using three different names for the modules: two for the two files and a one by which the module is made available in the package structure via the `__init__.py` file. (E.g.: _py_geo.py_, _c_geo.pyd_ and then make them available as 'geo').~~

Note: I am using Python 3.6 and have not tested whether the current imports ~~and the name change fix~~ will work in previous versions.

Edit: Accidentally tested on wrong branch, the casas compiled module seems to work (maybe because it is only used in relative imports?)

**Comment by jooste** [comment]
Interesting! I've tried renaming geo.py to pygeo.py, but that doesn't solve things. Specifying an alternative name in __init__.py with `import pygeo as geo` only works when you import geo from tools: `from bluesky.tools import geo`, not when you import the submodule directly, or import from geo: `from bluesky.tools.geo import qdrdist`. You can enable this by editing `sys.modules`, but that seems an ugly solution to me. Lets look for a better solution!

**Comment by RubenJacobse** [comment]
If I understand [PEP420](https://www.python.org/dev/peps/pep-0420/) correctly (and I most likely don't), it seems that the use of `from bluesky.tools.geo` defaults to importing as an implicit namespace package regardless of what is in `__init__.py` for Python >3.3. If this is correct, then the current approach of using `from bluesky.tools.geo import ...` might not be possible at all.

I tried making geo a subpackage of tools and then only making one implementation available via the `__init__.py` file in that subfolder but that also does not work when using `from bluesky.tools.geo import ...` because the import system apparently attempts to find a file `bluesky\tools\geo.py` and then fails at importing.

On the upside, being forced to use `from bluesky.tools import geo` and then calling geo functions as `geo.function()` may improve readability (though that is probably mostly a matter of personal preference).
