### ISSUE TITLE
Drawing aircraft trails in multiple nodes simultaneously

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#199]
During testing I often use the aircraft trails to visually inspect the differences between scenarios. Currently these are only drawn for the node that is 'active' in the radar widget, but not for any other nodes.

Would it be possible to extend the TRAILS ON functionality to also continue drawing in nodes that are not 'active' in the radar widget? It would be nice to have the ability to run multiple scenarios at the same time and then compare the differences in trails.

**Comment by ronicse59** [comment]
Hi,
If I want to draw a circle for each aircraft where the radius of each circle would be 5 NM. Is it possible to draw? I know the SYMBOL command makes the circle but I need to customize the circle radius.

Thanks in advance for understanding!

**Comment by jooste** [comment]
Implemented in 02b320d.
