### ISSUE TITLE
Erratic behaviour of aircraft (?)

### ISSUE THREAD

**Issue by MTMesfum** [TUDelft-CNS-ATM/bluesky#200]
Hi Joost,

I'm facing a problem with the fuel flow.
This is a snippet of a log of a scenario with 2 aircraft following the same trajectory.
However, aircraft 2 has a delay and therefore flies at a higher speed.

![image](https://user-images.githubusercontent.com/46937551/58495999-31521680-8179-11e9-9871-ad34f70778a5.png)

As you can see, aircraft 2 flies at a higher speed but has a significantly lower fuel consumption.
Also, it alternatively accelerates and decelerates between updates.
In the simulation, both aircrafts fly at constant speed.
This snippet is taken from between waypoint 3 and 4.

This scenario is run with several plugins activated, but I've created a save file using the input.
Using this savefile, it should be possible to recreate this behaviour on other BlueSky versions without those plugins.
The file is added at the bottom.

Running this scenario, without my plugins activated and with BADA, still creates this behaviour.
I've tried to test this behaviour on a clean install of BlueSky myself, but I ended up facing the following error:

![image](https://user-images.githubusercontent.com/46937551/58496385-103df580-817a-11e9-8cc4-6e6da54779a1.png)

I've tried uninstalling and installing PyOpenGl and PyOpenGl-accelerate to no avail.

If you could help isolate the source of this behaviour, it would help resolve the matter.

Kind regards,

Johannes
_______________________________________________________________________________________

[trajectories_saveic_bug.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3228849/trajectories_saveic_bug.txt)

**Comment by jooste** [comment]
Hi Johannes,

I’ve ran your simulation in the main version of bluesky, but there I don’t get this behaviour:


As for your problems running the main version of bluesky: do you use separate virtual environments for the main version and your version of bluesky? Because the error indeed seems to indicate a problem with your python installation. 

Best,
Joost

**Comment by jooste** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/7164813/58502606-20100680-8187-11e9-8421-3c34157d3450.png">

**Comment by MTMesfum** [comment]
Thanks for the fast feedback!
And yes, I use virtual environments.

**Comment by MTMesfum** [comment]
I changed the environment and it's working!
I'll compare the fuel flows and such to see where it goes wrong.
Thanks!

**Comment by MTMesfum** [comment]
Hi Joost,

The error seems to be on my side.
Several files were outdated.
So I will close this issue and resolve the matter.

Kind regards,

Johannes

**Comment by MTMesfum** [comment]
Hi Joost,

The error isn't on my side.
The source of this behaviour is described by Rene in https://github.com/TUDelft-CNS-ATM/bluesky/issues/201 .
You can reproduce the issue with the script on the bottom.

Kind regards,

Johannes
___________________________________________________________________________________

00:00:00.00>CRELOG MYLOG 0.1 "MYLOG"
00:00:00.00>MYLOG ADD traf.id, traf.ax, traf.gs, pilot.tas, traf.perf.mass, traf.perf.fuelflow
00:00:00.00>MYLOG ON
00:00:00.00>cre apple, A320, 54, 3, 35, FL250, 250
00:00:00.00>ff
00:00:15.00>spd apple 0.9
00:04:00.00>spd apple 0.6

**Comment by jooste** [comment]
The bug illustrated by René has been fixed in d09510e. I assume this will also fix your problems!
