### ISSUE TITLE
calclimit ask for tas and gets cas

### ISSUE THREAD

**Issue by rjdverbeek** [TUDelft-CNS-ATM/bluesky#201]
In traffic.performance.legacy.performance.py there is a function calclimit

def calclimits(desspd, gs, to_spd, vmin, vmo, mmo, M, alt, hmaxact,
           desalt, desvs, maxthr, Thr, D, tas, mass, ESF, phase)

It asks for a tas, but in traffic.performance.bada.perfbada.py when calling the calclimit function it is provided with a cas speed

calclimits(vtas2cas(bs.traf.pilot.tas, bs.traf.alt),   \
                                        bs.traf.gs,            \
                                        self.vmto,             \
                                        self.vmin,             \
                                        self.vmo,              \
                                        self.mmo,              \
                                        bs.traf.M,             \
                                        bs.traf.alt,           \
                                        self.hmaxact,          \
                                        bs.traf.pilot.alt,     \
                                        bs.traf.pilot.vs,      \
                                        self.maxthr,           \
                                        self.Thr,              \
                                        self.D,                \
                                        bs.traf.cas,           \
                                        self.mass,             \
                                        self.ESF,              \
                                        self.phase)

This seems to be incorrect.

Wkr,
René

**Comment by jooste** [comment]
Thanks René! Fixed in d09510e.
