### ISSUE TITLE
calclimit test for mmo results in instable behaviour

### ISSUE THREAD

**Issue by rjdverbeek** [TUDelft-CNS-ATM/bluesky#202]
In traffic.performance.legacy.performanc.py  in the function calclimits seems to be a small bug.

In line 228 there is a test for maximum mach number. If you set the speed above this maximum mach number the limit speed is set to this maximum mach number minus 0.01. 

limspd      = np.where((M > mmo), vmach2cas((mmo - 0.01), alt), limspd)

This results in an oscillating  behaviour where the pilot.tas speed is set up and down all the time when operating at max speed.

My suggestion is to make the test equal to the new limit the speed is set to:
So M > mmo - 0.01 and vmach2cas((mmo - 0.01), ...
Or M > mmo and vmach2cas((mmo), ...

Wkr,
René

**Comment by jooste** [comment]
Thanks René, implemented in 901f27d.
