### ISSUE TITLE
Issue using CSVLogger in scenario batches

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#203]
When using the FLSTLOG logger in the area.py plugin in scenario batches not all logfiles are written properly. Some logfiles are created but remain empty. 

When using the scenario files given below, I observe the following behaviour (tested on 1718a7f):
- When using `max_nnodes = 1`: all logfiles except the last one (for scenario test16) are written correctly. This last one remains empty.
- When using `max_nnodes = 4`: all but three logfiles are written correctly. These three also remain empty.

Scenario files:
[batch_log_test.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3350149/batch_log_test.txt)
[log_test.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3350150/log_test.txt)

**Comment by jooste** [comment]
Thanks! Should be fixed in c6938c0.
