### ISSUE TITLE
resopairs set in asas changes order 

### ISSUE THREAD

**Issue by tommeke303** [TUDelft-CNS-ATM/bluesky#206]
Due to the use of a set for resopairs (asas.py), the order can change. By having this different order, executing the same scenario in the same setting, leads to different speeds and different results. However, if a list is used, which does not change the order, and conflicts are added only when a conflict is not in the list, executing the same scenario, leads to the same results.

**Comment by jooste** [comment]
Hi Tommeke,

In the current implementation, the order of resopairs shouldn’t have an effect, as all resolutions are calculated in the same timestep, and within a single timestep resolutions don’t influence each other. If you are observing inconsistent behaviour between runs please provide a scenario which recreates this so we can check.

Joost

**Comment by tommeke303** [comment]
Dear Joost

I am currently using a slightly older version of BlueSky. And the problem that I had was solved in your latest update of asas.py: https://github.com/TUDelft-CNS-ATM/bluesky/commit/a9031a32a9b4bdb5e3dbe78e5662499c62da7b2c

However, it is still useful to change the resopairs to a list instead of a set for future changes. If you show the list of resopairs at line 421, for whatever scenario you want (if it uses asas at least), you will see that the order of the set can change when executing multiple times. For the added scenario, the results are given in two text files. The difference appears when the resopairs set is being filled with pairs. In the first test, the order is:
SELF.RESOPAIRS: {('KL001', 'KL002'), ('KL002', 'KL001')}

In the second test this is:
SELF.RESOPAIRS: {('KL002', 'KL001'), ('KL001', 'KL002')}

It does not create a problem anymore due to the last update but in the future, it could become an issue again if the asas.py file is modified.

[test_asas_scenario.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3469270/test_asas_scenario.txt)


[test_1_asas.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3469251/test_1_asas.txt)
[test_2_asas.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/3469252/test_2_asas.txt)

**Comment by jooste** [comment]
Thanks for the feedback. Since the set logic is specifically used to update things like resopairs efficiently, I'd like to keep it as a set unless there is really something going wrong if we don't.
