### ISSUE TITLE
Replay history trajectories

### ISSUE THREAD

**Issue by klippehu** [TUDelft-CNS-ATM/bluesky#207]
Hi,
There are ADS_B and radar history flight trajectories, and I want to replay them using blue-sky. The playback modes include static and dynamic ways. Do there already have some way to achieve it? If not, how can I do this? 
Thank you very much for your help!

**Comment by jooste** [comment]
hi,

Bluesky already has a plugin that feeds live ADS-B data in the simulation, this could be used to also create something to parse time histories. It depends a bit on the file format that your data is in. Is it just timestamped position/velocity updates?

**Comment by ronicse59** [comment]
Hi,
Is it possible to save the full log? For example, if I play for 10 minutes with two aircrafts and different commands. After that, I want to save the complete records for each aircraft like the full log file. Is it possible?

**Comment by jooste** [comment]
Hi ronicse59,

That depends what you mean by full log. There are two ways to save a simulation:

1. you can create a scenario file that can be simulated again with bluesky with `SAVEIC`. This function starts by saving the current state of the simulation, and until the simulation is stopped, then records all stack commands that are given (in a timestamped manner).

2. you can log raw data to a csv file. BlueSky doesn't keep previous data, so you have to start logging from the first timestep that you want to record the data. You can create a CSV logger with the `CRELOG` function. See [here](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Data-Logging) for an explanation.

**Comment by ronicse59** [comment]
Dear Jooste,

Could you please give me an example commands sequentially. Because I couldn't what does it mean by 'dt' or 'header'. Or it may my mistake. Also, where the CSV file will be saved and how? Please let me know. Thank you.

**Comment by jooste** [comment]
Hi ronicse59,

Did you look at the explanation on the wiki? (there's a link to the appropriate page in my previous message). It explains step by step how to create and use a logger, and where outputs are stored.

**Comment by ronicse59** [comment]
Dear Jooste,
First of all, I apologize for that I didn't understand. Now, I am done.
Thank you so much.

**Comment by ronicse59** [comment]
Dear Jooste,

If I am not wrong then the default system can detect conflict around 7 minutes before. If I want to modify it by 10 min in code where I have to change?
Thanks in advance.

**Comment by ProfHoekstra** [comment]
Dear Roni,

The default lookahead time is 5 minutes. You can set this by using the command:

DTLOOK 600

to 10 minutes (= 600 seconds)

Best regards,
    Jacco Hoekstra


On 25 Sep 2019, at 01:45, MS Rahman <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Jooste,

If I am not wrong then the default system can detect conflict around 7 minutes before. If I want to modify it by 10 min in code where I have to change?
Thanks in advance.

**Comment by omar-Fouad** [comment]
Dear Jooste
can i send traf.lat, traf.lon, traf.alt to another pc using  IP 
thanks

**Comment by jooste** [comment]
Yes. Bluesky uses tcp already for all of its communication between gui and simulation. If your external application is also python you can directly use bluesky's [Client](bluesky/network/client.py) class. If your application is written in another language you'd have to make your own implementation. Bluesky uses ZMQ to manage its sockets, and MSGPACK to (de)serialise data.

**Comment by omar-Fouad** [comment]
hi again 
i run blueskygui
python bluesky.py
mcre 10
then 
i tried read the traffic id

>>> from bluesky import traf
>>> traf
>>> # Get number of aircraft
... num_ac = traf.ntraf
**Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'NoneType' object has no attribute 'ntraf'**

**Comment by jooste** [comment]
hi,
Where do you make this import? In a plugin this should work, anywhere else in bluesky it cannot be guaranteed that bluesky is already initialised, and therefore that the traf, sim, ... objects in bluesky are already constructed.

**Comment by omar-Fouad** [comment]
thanks alot
