### ISSUE TITLE
Approximation error for the altitude

### ISSUE THREAD

**Issue by tommeke303** [TUDelft-CNS-ATM/bluesky#208]
In the pilot.py file I discovered that the altitude for the same scenario can be different because of rounding errors. By rounding the altitude to 6 decimals, this problem was solved. I did this in line 473: self.alt = np.where(self.swaltsel, self.alt + self.vs * simdt, self.pilot.alt)
and changed it to:
self.alt = np.where(self.swaltsel, np.round(self.alt + self.vs * simdt, 6), self.pilot.alt)

**Comment by ProfHoekstra** [comment]
Looks like a good solution to me. We’ll implement it in the master version. Thanks! – Jacco Hoekstra

**Comment by ProfHoekstra** [comment]
Added to master version.
