### ISSUE TITLE
Stuck when starting

### ISSUE THREAD

**Issue by ruifengma** [TUDelft-CNS-ATM/bluesky#215]
![屏幕快照 2019-11-07 下午5 00 52](https://user-images.githubusercontent.com/33011392/68405383-48f9e600-0180-11ea-9d14-2c46f1a1d140.png)

**Comment by jooste** [comment]
Hi,

Your screenshot shows that you need to install qtwebengine (preferred) or qtwebkit. With pip you can do this:

    pip install PyQtWebEngine

Please try this and see if it resolves your problem!

**Comment by ruifengma** [comment]
Thanks @jooste , I solve this issue by downgrade the version of PyQt. I think for the version which is greater than 5.11, it wouldn't work. Maybe you can modify a bit on the documentation since if you use pip install without specifying the version, it will automatically install the latest version which is not compatible.

**Comment by jooste** [comment]
@ruifengma, I'm not sure about that, I have bluesky running with pyqt 5.13.2 without problems. 
The required qt-related packages to install are PyQt5 and PyQtWebEngine.
