### ISSUE TITLE
AttributeError: module 'bluesky.settings' has no attribute 'simdt'

### ISSUE THREAD

**Issue by ruifengma** [TUDelft-CNS-ATM/bluesky#216]
Don't know it's a bug or I did not use it correctly, when I just want to do some kind of dirty try, I got this error. The following is the code I used
```
from bluesky import stack, settings, navdb, traf, sim, scr, tools
sim.start()
```

**Comment by jooste** [comment]
Hi,

You need to do the following before anything else:

    import bluesky
    bluesky.init()

**Comment by ruifengma** [comment]
Thanks @jooste , may I ask if there is any example code for interacting with the environment through python, cause my idea is to extra the state information from the traf object and control the aircraft through autopilot (not sure if I'm current). Since I cannot find a example resource to do the whole procedure.

**Comment by jooste** [comment]
Well, there is currently no such example, but it is quite possible. When you want to run a bluesky simulation without the bluesky main loop you need your own loop, where you call bluesky.sim.step() in each cycle. The easiest way to control the simulation is still through the stack. That way the control is still the same as when you'd normally run bluesky.

The following example would, for instance, run a scenario for some fixed number of time steps:

    import bluesky as bs
    bs.init(mode='sim-detached')
    bs.stack.stack('IC myscenario.scn')
    bs.stack.stack('FF')
    sample = 5000
    while sample > 0:
        bs.stack.stack('STACK YOUR ADDITIONAL COMMANDS HERE')
        # Example of accessing data:
        if bs.traf.ntraf:
            print('Latitude of first aircraft:', bs.traf.lat[0])
        bs.sim.step()
        sample -= 1

Many of the traffic attributes in bluesky.traffic are described in the bluesky wiki.

**Comment by ruifengma** [comment]
Thank you very much @jooste ,this is very helpful. As for directly access the traffic object, for example, if I would like to do reinforcement learning algorithm, from the wiki, if I'm not wrong, I saw that I can get the state information from traffic object, one thing I'm not sure is that, if the traf.autopilot is the api to control each aircraft's action. Besides, Can they be used together with the step() function as well? Sorry for so many questions

**Comment by jooste** [comment]
This depends on what you want to control. First of all I would like to again encourage you to interact with the simulation via the stack. If there is a specific reason that you want to access these functions directly, the autopilot is used to give autopilot commands (HDG, SPD, ALT, ...), the Route object is used for LNAV/VNAV functionality.
