### ISSUE TITLE
Vertical speed of active waypoint not present for all generated aircraft while simulating scenarios

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#217]
Hi,

While trying the trafgen plugin, I came across the issue shown in the screenshot below. 
![bluesky-error](https://user-images.githubusercontent.com/24636674/71907882-3e9e9d00-316d-11ea-96a3-f8ff06ecb5fa.png)

I did some debugging and it turns out that the problem occurs in the ComputeVNAV method and happens because bs.traf.actwp.vs does not the correct number of elements, hence the index out of bounds error. To test this I printed bs.traf.vs, bs.traf.gs, bs.traf,tas and bs.traf.id and the number of elements increases with each newly generated aircraft, while this does not happen for bs.traf.actwp.vs. 

I tried running also simulating scenarios without using the trafgen plugin, more specifically I just ran the demo scenarios and the same issue came up. I think this might be happening because aircraft get generated faster than the variables are updated, but I'm not sure.

I'm using Windows 10 and running the qt version of bluesky. 

Any hints would be greatly appreciated as this is a blocking issue for me.

Cheers,
Ralvi

**Comment by jooste** [comment]
Dear Ralvi,

Please check if your bluesky version is at least at commit 8217c42, which includes a fix for similar issues. If you already have bluesky up to this version or if it doesn't fix your problem, please make a minimum working example scenario file which replicates this crash and post it here.

**Comment by risufaj** [comment]
Dear Joost,

Thanks for the reply. Getting the latest version seems to have fixed the problem, so far the issue hasn't occured again. There was one other thing that came up after updating, which as far as I can rememeber didn't occur before (it could be that the previous issue happened before so the part of this new issue was never run).

![bluesky-error-2](https://user-images.githubusercontent.com/24636674/71977165-68f96480-3218-11ea-96a6-b1141898c573.png)
I managed to resolve it by substituting kwikdist with kwikqdrdist, though I'm not quite sure this is the correct way to solve this. 

Cheers,
Ralvi

**Comment by jooste** [comment]
Looks like that was just a bug in the trafgen plugin, should be fixed in 09ba8ce.

**Comment by risufaj** [comment]
Perfect. I'll go ahead and close this, as everything seems resolved. Thanks.
