### ISSUE TITLE
Suspected bug in glbuffer handling

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#218]
When drawing and deleting areas the buffers don't seem to be reset/cleared properly, leading to line pieces of polygons that remain visible after deletion. This is visible when a new polygon has fewer vertices than the deleted polygon.

[drawtest.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/4077200/drawtest.txt)

**Comment by jooste** [comment]
Thanks! Fixed in 50cee26.
