### ISSUE TITLE
Aiport positions

### ISSUE THREAD

**Issue by EdvinPilot** [TUDelft-CNS-ATM/bluesky#225]
![Capture](https://user-images.githubusercontent.com/45877690/74662174-ae0aa200-5199-11ea-894e-d8cc9540e45a.PNG)

The airports position and map position is not aligned ? 

Best regards

**Comment by jooste** [comment]
Hi,

Can you tell me more about the hardware/software you're running this on? If I remember correctly this issue occurred with some Intel integrated graphics configurations.

**Comment by EdvinPilot** [comment]
Windows 7 Professional SP1
Intel(R)Xeon(R)CPU W3565 @ 3.2Ghz 3.19 GHz
RAM 6 GB
64-bit
NVIDIA Quadro 2000

This only happens on newer BlueSky interface QTOpenGL. On the Classic user interface everthing is ok. 

Best regards

**Comment by jooste** [comment]
Your hardware is quite old, but according to the specs should be able to support all of the OpenGL calls we use in bluesky. You could try updating your graphics driver, but with such old hardware I fear that this is unsolvable.
