### ISSUE TITLE
Obstacle avoidance

### ISSUE THREAD

**Issue by terivan** [TUDelft-CNS-ATM/bluesky#226]
Hi,

I'd like to implement aircraft obstacle avoidance, for example flying around static or moving convective weather systems in the free-flight mode (not using waypoints). Ideally, I would be able to create a "cloud" of a size that I choose that will move along a pre-defined route. All aircraft in the analysis area would do their best to avoid the cloud and also have their MVP ASAS enabled in order to avoid mid-air intrusions with each other. How would I go about implementing this functionality? Thank you.

**Comment by jooste** [comment]
If I understand correctly you basically want to have one or more 'pseudo aircraft' that have different dimensions (i.e., separation minima), and that are passive. Currently, separation minima are the same for all aircraft, and thus stored in a single float. You would have to change this to a numpy array in a derived implementation. This would require adaptation of the conflict detection function, and also MVP, which probably isn't able to handle non-scalar separation minima.

You can do this by making a plugin, that defines a child class of ConflictDetection (or StateBased if you want to reuse some of its functions) and a child class of ConflictResolution (or MVP if you want to reuse some of its functions).

Have a look at the [Eby](plugins/asas/eby.py) plugin for an example.
