### ISSUE TITLE
Send commands over TCP

### ISSUE THREAD

**Issue by airlooking** [TUDelft-CNS-ATM/bluesky#227]
Hi, as you mentioned in API Reference part, "BlueSky can be connected over TCP to send it simulation commands", which means that I can send commands such as "CRE KL001 B737 52 3 180 FL100 300" from outer code programs. But there is no tutorial about this part, I find it's hard to look for related APIs from such huge amount of codes.

Please provide some examples or update the tutorial about network communication, thank you!

**Comment by jooste** [comment]
Hi, this was indeed on the todo list! I've created a simple example in the `extra` folder, and added a tutorial [here](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Connecting-external-applications-to-BlueSky).

**Comment by airlooking** [comment]
Many thanks for your work!
