### ISSUE TITLE
Question: Simulating trajectory between several points

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#229]
Hi,

I am working with ddr2 traffic (.so6) files and I want to simulate the trajectory between several consecutive recordings for the same flight. We assume constant speed between two points. Several approaches come to mind:

1. Create the aircraft at the location of the first point, calculating heading and speed using the second point. Then add the following points as waypoints, calculating heading and speed between each to points
2. The start of the procedure would be the same as the first approach, but in this way I would use the 'SCHEDULE' command to update heading and speed between two points. The 'SCHEDULE' command would fire after the time difference between two points.
3. Manually interpolate intermediate points between two given recordings. Positions are updated using the 'MOVE' command. I saw this method applied in utils/Scenario-creator/so6_to_scn.py which creates scenarios files from so6 files. 

I believe the third approach is more prone to errors, as the first approaches rely on the implementation of autopilot already present in bluesky, but I was still wondering if you had any thoughts and/or suggestions on which approach is more reasonable. I was also wondering if there is any reason why that particular method was used in so6_to_scn.py

Best,
Ralvi

**Comment by ProfHoekstra** [comment]
Hi Ralvi,

MOVE also contains speed and heading. If you use the correct speed and heading based on the second point (speed is CAS) I think that the effect should be the same as BlueSky will do the correct extrapolation.

Best regards,
    Jacco Hoekstra


On 10 Apr 2020, at 14:54, Ralvi Isufaj <notifications@github.com> wrote:

﻿

Hi,

I am working with ddr2 traffic (.so6) files and I want to simulate the trajectory between several consecutive recordings for the same flight. We assume constant speed between two points. Several approaches come to mind:

  1.  Create the aircraft at the location of the first point, calculating heading and speed using the second point. Then add the following points as waypoints, calculating heading and speed between each to points
  2.  The start of the procedure would be the same as the first approach, but in this way I would use the 'SCHEDULE' command to update heading and speed between two points. The 'SCHEDULE' command would fire after the time difference between two points.
  3.  Manually interpolate intermediate points between two given recordings. Positions are updated using the 'MOVE' command. I saw this method applied in utils/Scenario-creator/so6_to_scn.py which creates scenarios files from so6 files.

I believe the third approach is more prone to errors, as the first approaches rely on the implementation of autopilot already present in bluesky, but I was still wondering if you had any thoughts and/or suggestions on which approach is more reasonable. I was also wondering if there is any reason why that particular method was used in so6_to_scn.py

Best,
Ralvi
