### ISSUE TITLE
aircraft does not reduce speed when landing

### ISSUE THREAD

**Issue by mflorent23** [TUDelft-CNS-ATM/bluesky#231]
Hi everyone,

I would like to know why the aircraft does not reduce its speed when landing. The altitude decreases accordingly, but the aircraft never stops. I know I can "delete" the aircraft with 'TAXI OFF 1' for instance, but I would like to have an approach where the aircraft also slows down apart from descending its altitude.

Thank you.

**Comment by jooste** [comment]
This could be either related to the performance implementation, the autopilot, or how you specify your commands. Can you give a minimum-working example of a scenario?

**Comment by ProfHoekstra** [comment]
I'm currently doing some maintenance on autopilot speed guidance in VNAV alongside implementing turn speeds, I'll also have a look at this. Could you include the scenario file you use? Maybe inlined in the e-mail?

**Comment by mflorent23** [comment]
I don't add any specific performances like BADA or similar. The scenario file is very simple, just O-D flight. Here you have the lines:
`0:00:00>TAXI OFF 1
0:00:00>CRE TAP1 B767 39.78 -8.82 100 FL300 300
0:00:01>ORIG TAP1 LPJF
0:00:01>DEST TAP1 LEAB
0:00:01>TAP1 AT LEAB SPD 0
0:00:01>VNAV TAP1 ON
0:00:01>LNAV TAP1 ON`

**Comment by ProfHoekstra** [comment]
Speed commands are activated when passing the waypoint, at which the speed has been defined. This means the speed acts on the "next leg". In this case, there is no next leg as the speed is set on the final waypoint at which LNAV/VNAV are deactivated as there are no more waypoints. 

It might be an idea for us to copy the last waypointsettings for speed and altitude to the autopilot before switching off LNAV/VNAV. We'll look into adding that feature. 

But for now: we normally have a threshold waypoint (you can click on the begin and end of runway to add these waypoints) with speed 20 or 0 and altitude 0 and/or use a runway. Just an airport is  not enough for a realistic landing, then we indeed use taxi off.  One of our students also suggested adding a few lines to your scenario file for an approach (also attached, see last line):

00:00:00.00>TAXI OFF 1
00:00:00.00>CRE TAP1 B767 39.78 -8.82 100 30000 300
00:00:01.00>ORIG TAP1 LPJF
00:00:01.00>DEST TAP1 LEAB
00:00:01.00>TAP1 AT LEAB SPD 0
00:00:01.00>VNAV TAP1 ON
00:00:01.00>LNAV TAP1 ON

#Added for realistic approach speeds
00:00:02.00>DEFWPT SPDCOMMAND 38.936761,-2.369939
00:00:02.00>TAP1 addwpt spdcommand,,200
00:00:02.00>TAP1 addwpt ABT,,160


[florentnew.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/4491333/florentnew.scn.txt)
