### ISSUE TITLE
Can't seem to run scenarios in headless mode

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#232]
Hi,

I'm trying to run some scenarios without calling the gui. The reason for this is that in my scenarios I create around 2000-3000 aircraft and that seems to be very slow, meaning that simulation speed is down to x0.1. The way I do this is by first creating a headless server: 
`python BlueSky.py --headless`
and then by creating a simulation node to which I also give the scenario file as an argument:
`python BlueSky.py --sim --scenfile scenario1.scn`
The problem seems to be that the commands in the scenario don't seem to be executed. If I create the server with the guy and then enter the scenario file as a command in the gui, everything works as expected. 
Do you have any idea what might be causing this? Also do you think this is the right way to go about speeding the simulations? Thanks in advance.

Cheers,
Ralvi

**Comment by jooste** [comment]
Hi Ralvi,

I tried this out myself, and noticed that it indeed doesn't correctly process the scenfile argument. I've committed a fix in 15b55a5.

Note, though, that a) the gui doesn't take much CPU power (it mostly runs on the GPU), and b) if you really don't want the gui to be available all the time, you can always start headless, and connect with bluesky in client mode:

`process 1: python BlueSky.py --headless`
`process 2: python BlueSky.py --client`
