### ISSUE TITLE
Bug windgfs.py

### ISSUE THREAD

**Issue by albiboni** [TUDelft-CNS-ATM/bluesky#233]
link file: https://github.com/TUDelft-CNS-ATM/bluesky/blob/master/plugins/windgfs.py
base_url = "http://nomads.ncdc.noaa.gov/data/gfsanl" seems to be outdated, the new one is base_url = "https://www.ncei.noaa.gov/data/global-forecast-system/access/historical/analysis/"

and

lon1_ = max(lon0, **lat1**) should be lon1_ = max(lon0, **lon1**)

**Comment by jooste** [comment]
Thanks for the suggestion! I've fixed this in 04f6c96.
