### ISSUE TITLE
Get aircraft inside a POLY bounds

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#237]
Is there an existing feature that can give a list of all aircraft that exist inside a defined POLY area?

**Comment by jooste** [comment]
Yes, you can do the following in a plugin:

```python
from bluesky import traf
from bluesky.tools import areafilter

inside = areafilter.checkInside('areaname', traf.lat, traf.lon, traf.alt)
```

There are several examples of this in the plugin folder, such as `sectorcount.py`.
