### ISSUE TITLE
Error message from check.py

### ISSUE THREAD

**Issue by yaofuzhou** [TUDelft-CNS-ATM/bluesky#238]
Hi, I have tried a few branches of Bluesky on my Macbook with Catalina v10.15.6, Python 3.8.5, and HomeBrew for package management, and `check.py` has been giving me the following (error) message:

> ~/.../bluesky(master) » python3 check.py
> This script checks the availability of the libraries required by BlueSky, and the capabilities of your system.
> 
> Checking for numpy               [OK]
> ...
> OpenGL module version is         [3.1.5]
> qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> [1]    27134 abort      python3 check.py

The "Could not find the Qt platform plugin "cocoa" in """ is an common issue found on Google, but none of the solutions I have found could get it fixed. A typical solution found on Google may look like:
`pip3 install opencv-python-headless`
These install commands execute fine, but none could fix the issue for me.
Thank you.

**Comment by jooste** [comment]
Hi, I use macports myself, so I don't know too much about homebrew. It could be that the (py)qt5 installation is incomplete, or that you have a malfunctioning package. I would recommend you to check your installation of pyqt5, whether it is homebrew or pip. If it is homebrew see if it has any missing additional packages that you might need. Alternatively you can also try to install pyqt5 through pip (`pip install PyQt5`).

**Comment by yaofuzhou** [comment]
joooste, I uninstall PyQt5 using Brew and installed PyQt5 using pip3, and the issue has been fixed. Thank you.
