### ISSUE TITLE
Error while creating RadarWidget objects: Empty data-type

### ISSUE THREAD

**Issue by yaofuzhou** [TUDelft-CNS-ATM/bluesky#239]
Hi again,

I have succeeded in launching BlueSky with GUI, but got the subsequent terminal readout, where the error appears near the bottom:

> ~/Downloads/bluesky-master » python3 BlueSky.py    
> Reading config from settings.cfg
> Using Python-based geo functions
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
>    *****   BlueSky Open ATM simulator *****
> Distributed under GNU General Public License v3
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/Users/.../Downloads/bluesky-master/bluesky/network/server.py", line 71, in run
>     self.fe_event.bind(f'tcp://*:{bs.settings.event_port}')
>   File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
>   File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
> zmq.error.ZMQError: Address already in use
> Loading palette bluesky-default
> Using Qt 5.15.0 for windows and widgets
> QGLWidget initialized for OpenGL version 3.3
> Reading cache: data/cache/py3/aptsurface.p
> Reading cache: data/cache/py3/coastlines.p
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> Maximum supported texture size: 16384
> Loading texture data/graphics/world.16384x8192.dds
> Error while creating RadarWidget objects: Empty data-type
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> Client b'\x00\x02\x08\xdd\x0f' connected to host b'\x00\xcd\x8a\xa7c'
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> ...

This issue persists when running in the Python virtual environment.

I am new to BlueSky, and will keep consulting the documentation, but thank you if you have the solution.

**Comment by jooste** [comment]
Something is going wrong in the construction of the OpenGL gui. Can you do the following:

in **bluesky/ui/qtgl/radarwidget.py**, around line 445, change:

```python
    except Exception as e:
        print('Error while creating RadarWidget objects: ' + e.args[0])
```

into:

```python
    except Exception as e:
        print('Error while creating RadarWidget objects: ' + e.args[0])
        raise e
```

Then run BlueSky again and let me know the full exception printed to the terminal.

**Comment by yaofuzhou** [comment]
Dear Joost,

Thank you for attending to this. Here is the print-out:

> ~/Documents/UAM_research/bluesky(lstm*) » python3 BlueSky.py
> Reading config from settings.cfg
> Using Python-based geo functions
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
>    *****   BlueSky Open ATM simulator *****
> Distributed under GNU General Public License v3
> Accepting event connections on port 11000, and stream connections on port 11001
> Discovery is disabled
> Loading palette bluesky-default
> Reading config from settings.cfg
> Using Python-based geo functions
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
> StateBasedCD: using default Python version, no compiled version for this platform.
> StateBasedCD: using Python version.
> Using BlueSky legacy performance model
> pygame 2.0.0.dev6 (SDL 2.0.10, python 3.8.5)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Using Qt 5.15.0 for windows and widgets
> QGLWidget initialized for OpenGL version 3.3
> Reading cache: data/cache/py3/aptsurface.p
> Reading cache: data/cache/py3/coastlines.p
> ND: Context not valid in create_objects, or shareWidget not yet initialized
> Maximum supported texture size: 16384
> Loading texture data/graphics/world.16384x8192.dds
> Error while creating RadarWidget objects: Empty data-type
> Traceback (most recent call last):
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/radarwidget.py", line 447, in initializeGL
>     raise e
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/radarwidget.py", line 444, in initializeGL
>     self.create_objects()
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/radarwidget.py", line 356, in create_objects
>     self.wptlabels = self.font.prepare_text_instanced(npwpids, (5, 1), self.wptlatbuf, self.wptlonbuf, char_size=text_size, vertex_offset=(wpt_size, 0.5 * wpt_size))
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/glhelpers.py", line 371, in prepare_text_instanced
>     ret.bind_attrib(self.attrib_texdepth, 1, text_array, instance_divisor=1, datatype=gl.GL_UNSIGNED_BYTE)
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/glhelpers.py", line 194, in bind_attrib
>     gl.glBufferData(gl.GL_ARRAY_BUFFER, data.nbytes, data, storagetype)
>   File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
>   File "/usr/local/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_5.py", line 86, in glBufferData
>     data = ArrayDatatype.asArray( data )
>   File "src/arraydatatype.pyx", line 174, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
>   File "src/numpy_formathandler.pyx", line 159, in OpenGL_accelerate.numpy_formathandler.NumpyHandler.c_asArray
>   File "src/numpy_formathandler.pyx", line 132, in OpenGL_accelerate.numpy_formathandler.NumpyHandler.c_zeros
> TypeError: Empty data-type
> 

and the GUI was stuck at the logo.

**Comment by jooste** [comment]
From the line `File "/usr/local/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_1_5.py", line 86, in glBufferData` it looks like your installation of pyopengl is using OpenGL version 1, whereas you need version >=3. Can you try updating pyopengl?

**Comment by yaofuzhou** [comment]
I do have
`OpenGL` module version is         [3.1.5]
when `check.py` is run. I will check if I can get program looking for the correct version of OpenGL, and update then.

**Comment by jooste** [comment]
3.1.5 is indeed the latest version that pip provides. 

In case the problem does lie elsewhere you could try the following: In `bluesky/ui/qtgl/radarwidget.py` before line 356 insert:

```python
    print('WPname buffer size:', len(npwpids))
```
And let me know what it prints.

**Comment by yaofuzhou** [comment]
>   File "/Users/yaofuzhou/Documents/UAM_research/bluesky/bluesky/ui/qtgl/radarwidget.py", line 356, in create_objects
>     print('WPname buffer size:', len(npwpids))
> TypeError: len() of unsized object

**Comment by jooste** [comment]
Ah, sorry, apparently you need `npwpids.size` instead of `len(npwpids)`.

**Comment by jooste** [comment]
By coincidence I just received an email from someone with exactly the same problems as you are experiencing. Also with a Mac and Python 3.8. I'm starting to think that this is related to python 3.8 and the packages that come with it. Would you mind trying installing python 3.7? This is what I use myself (also on a mac), and it works fine.

**Comment by yaofuzhou** [comment]
> Ah, sorry, apparently you need `npwpids.size` instead of `len(npwpids)`.

WPname buffer size: 1

**Comment by yaofuzhou** [comment]
It is finally working for me!
Specifically, I installed miniconda to create a virtual environment of Python 3.7 (3.7.9 to be exact).
Another critical step in my attempt was `pip3 install msgpack==0.6.2`, which is another downgrade from the latest version.
