### ISSUE TITLE
OpenAP Rotorcraft speed

### ISSUE THREAD

**Issue by marcbrittain** [TUDelft-CNS-ATM/bluesky#240]
When using the OpenAP model, the rotorcraft do not respond to the SPD command for positive values. They do however respond to negative speed values. There also seems to be a bug when using the ADDWPT command with the rotorcraft as well.

Minimal working example:

> >git clone (master bluesky branch)
> 
> python BlueSky.py
> Inside the BlueSky GUI
> CRE KL1 EC35 lat, lon, 1200, 90, 50
> click "play"
> 
> The speed for the aircraft will drop to "0".
> SPD KL1 25
> 
> Will not change the speed.
> 
> SPD KL1 -25
> Will change the speed in the negative direction.

Another error related to the rotorcraft

> ADDWPT KL1 (random location)
> Will flip the heading of the aircraft 180 from the waypoint.

**Comment by jooste** [comment]
Hi Marc, good to hear from you again.

Perhaps a typo, but your CRE command is not correct: I think you swapped heading and altitude. That probably won't fix the bug though!

**Comment by marcbrittain** [comment]
Hi Joost!

Likewise! I hope things are going well with you. I had attempted writing the CRE command from memory instead of looking at my console again :) 

Correct, I do have the correct syntax written within BlueSky. I have also tested this on two different OS with the same results.

**Comment by junzis** [comment]
Fixed now in 4ed74da.
Cheers.
