### ISSUE TITLE
"areafilter.checkInside()" not working whan calling python BlueSky.py --sim --detached --scenfile...

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#242]
When running the program using `python BlueSky.py --sim --detached --scenfile...` the function used to get traffic inside of areas doesnot seem to work. 
It works when running it with a gui (running BlueSky.py directly). 
Is this a known issue or is there an issue with the way I've created the areas?

**Comment by jooste** [comment]
I can think of no reason why this should behave any different when you start a simulation in detached mode. Are you sure the problem lies with areafilter?

**Comment by Ellislee1** [comment]
Maybe its in the way the plugin is loaded or traffic is created?
```
python BlueSky.py --sim --detached --scenfile ml.scn
Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
Using Open Aircraft Performance (OpenAP) model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Setting up Traffic Management
========
[30, 25, 20, 20, 20, 30, 30, 20, 30, 20, 25, 25, 30, 30, 20, 20, 30, 25, 25, 25, 25, 30, 25, 25, 25, 20, 25, 25, 20, 20, 20]
========
###############
Preparing Data Loader
###############
====================
Epoch 0
====================
Successfully loaded plugin ML_TRAFF
====================
Epoch 0
====================
Loading global navigation database...
Reading cache: data/cache\py3\navdata.py
```
This is the output on startup. the anomoly seems to be the repetition of 
```
====================
Epoch 0
====================
```

**Comment by jooste** [comment]
Did you try running the exact same test scenario in both the detached and the regular setup? If I run a test scenario with an area defined, and put a temporary print statement in checkInside, this message is printed periodically both in the normal as well as in the detached mode. This seems to indicate that the problem you are facing is occurring somewhere else.

**Comment by Ellislee1** [comment]
I figured out the problem. I was using `stack` to create areas when running in `python BlueSky.py --sim --detached --scenfile...`. I have since switched to using `areafilter.defineArea()` which seems to work so far as areas are showing as existing in the simulation now.

**Comment by jooste** [comment]
It should also work when setting the area via a stack command, so perhaps something else is also not working correctly!
