### ISSUE TITLE
Question: Keeping a constant speed

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#243]
Hi,

I am trying to simulate a miles-in-trail scenario and would like the aircraft to hold a constant speed, but this doesn't seem to happen, as the speed decreases with time. Is there any way I could achieve this? I'm also attaching a simple scenario to recreate this.
`00:00:00>cre aclmg1 B744  45.815917 1.025583 128.04247840930185 25000 476

00:00:00>cre actou1 B744  43.680833 1.309806 54.50122318892586 25000 476

00:00:00>schedule 110,cre aclmg2 B744  45.815917 1.025583 128.04247840930185 25000 476

00:00:00>schedule 110,cre actou2 B744  43.680833 1.309806 54.50122318892586 25000 476

00:00:00> trail on

00:00:00> asas off`

Thank you!

**Comment by jooste** [comment]
Hi!

You are creating an aircraft at an airspeed that lies outside of its flight envelope (476 kts CAS at FL250 is > 1 Mach!)
If you use a reasonable speed it should remain constant after creation.
