### ISSUE TITLE
 Under PyQt 5: 'RadarWidget' object has no attribute 'globaldata' 

### ISSUE THREAD

**Issue by weiguowilliam** [TUDelft-CNS-ATM/bluesky#244]
I got the error:

Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Accepting event connections on port 11000, and stream connections on port 11001
Discovery is disabled
Loading palette bluesky-default
Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
Using Open Aircraft Performance (OpenAP) model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Using Qt 5.15.1 for windows and widgets
QGLWidget initialized for OpenGL version 3.3
Cachefile not found: data/cache/py3/aptsurface.p
Reading apt.dat from apt.zip
Writing cache: data/cache/py3/aptsurface.p
Cachefile not found: data/cache/py3/coastlines.p
Reading coastlines.dat
Writing cache: data/cache/py3/coastlines.p
This plugin does not support propagateSizeHints()
OpenGL context created with GL version 3.1
Client b'\x00\xba\xc1\x0b\x11' connected to host b'\x00(O\x8eZ'
Traceback (most recent call last):
  File "/home/wei/Documents/bluesky-master/bluesky/network/client.py", line 112, in receive
    self.actnode(nodes_myserver[0])
  File "/home/wei/Documents/bluesky-master/bluesky/network/client.py", line 154, in actnode
    self.actnode_changed(newact)
  File "/home/wei/Documents/bluesky-master/bluesky/ui/qtgl/guiclient.py", line 77, in actnode_changed
    self.actnodedata_changed.emit(newact, self.get_nodedata(newact), UPDATE_ALL)
  File "/home/wei/Documents/bluesky-master/bluesky/tools/signal.py", line 15, in emit
    subs(*args, **kwargs)
  File "/home/wei/Documents/bluesky-master/bluesky/ui/qtgl/radarwidget.py", line 179, in actnodedataChanged
    self.allpolys.set_vertex_count(0)
AttributeError: 'RadarWidget' object has no attribute 'allpolys'

---

I found this issue https://github.com/TUDelft-CNS-ATM/bluesky/issues/37 . The solution is to use PyQt5. I used PyQt 5.15.1. And here is some related information.

When running check.py, it gives the error: ‘Xbc’ found but cannot initialize. Then I set 'export QT_QPA_PLATFORM=offscreen' and check.py run successfully.

System: 
Ubuntu 20.10 (virtualbox)

OpenGL:
OpenGL version string: 3.1 Mesa 20.2.1

Package:
Package         Version
--------------- -------------------
certifi         2020.6.20
cycler          0.10.0
kiwisolver      1.2.0
matplotlib      3.3.2
msgpack         1.0.0
numpy           1.19.2
pandas          1.1.3
Pillow          8.0.1
pip             20.2.4
pygame          1.9.6
PyOpenGL        3.1.5
pyparsing       2.4.7
PyQt5           5.15.1
PyQt5-sip       12.8.1
python-dateutil 2.8.1
pytz            2020.1
pyzmq           19.0.2
QtPy            1.9.0
scipy           1.5.3
setuptools      50.3.0.post20201006
six             1.15.0
wheel           0.35.1

Should I update OpenGL to 3.3? What is the reason for the error? Thank you.

**Comment by weiguowilliam** [comment]
And after I stopped the program and run it again, it gives the following information:

Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wei/anaconda3/envs/bluesky/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/wei/Documents/bluesky-master/bluesky/network/server.py", line 71, in run
    self.fe_event.bind(f'tcp://*:{bs.settings.event_port}')
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

Loading palette bluesky-default
Using Qt 5.15.1 for windows and widgets
QGLWidget initialized for OpenGL version 3.3
Reading cache: data/cache/py3/aptsurface.p
Reading cache: data/cache/py3/coastlines.p
This plugin does not support propagateSizeHints()
OpenGL context created with GL version 3.1

**Comment by jooste** [comment]
Hello,

The second error you are getting indicates that there is still a BlueSky process running in the background. This can happen when BlueSky isn't quit cleanly. You can find out which processes are still running with the following command:

`ps aux |grep BlueSky`

For all processes listed here do:

`kill #pid#`

Where pid is the process id listed for each process in the ps aux list.

The first error you are getting is  indeed related to the fact that your current setup only supports OpenGL 3.1. You need at least OpenGL 3.3 to run the Qt version of BlueSky.
