### ISSUE TITLE
'bluesky' has no attribute 'stack'

### ISSUE THREAD

**Issue by LuisNavarroGarcia** [TUDelft-CNS-ATM/bluesky#246]
I was just about to start using this simulator, when running check.py, or BlueSky.py, the message: 'bluesky' has no attribute 'stack', pops up. I was wondering where this issue might be coming from as I'm new to the simulator and don't know how to fix the problem myself or if it is happening to everyone after the last update several days ago.

**Comment by jooste** [comment]
Hi Luis,

First of all welcome to the BlueSky community!

I don't get this error, even when I download a clean version of bluesky. It might still be related to the recent changes to the stack though! Can you show the complete console output of BlueSky?

**Comment by LuisNavarroGarcia** [comment]
Thank you for the quick response!

I attach a screenshot of the console output.

Happy to join the community!

![Captura](https://user-images.githubusercontent.com/73844258/97902994-afd3c000-1d3e-11eb-8255-74a405425536.JPG)

**Comment by jooste** [comment]
That's odd. Which version of python are you using?

**Comment by LuisNavarroGarcia** [comment]
I'm using python 3.6.8

**Comment by jooste** [comment]
Ok, that shouldn't be the problem. Windows, linux, or macos?

**Comment by LuisNavarroGarcia** [comment]
It's windows, sadly not 10 as I have to work from an old computer. I fear that might be the issue here. Doesn´t usually give me errors, but I don't really know much of the code yet to judge that. I'll try to find a new computer I can clone the repository to see if it works.

**Comment by ProfHoekstra** [comment]
Dear Luis,

Just to be sure: could you try putting it in a path-name without spaces?

Met vriendelijke groeten,
    Jacco Hoekstra


On 2 Nov 2020, at 20:23, LuisNavarroGarcia <notifications@github.com> wrote:

﻿

It's windows, sadly not 10 as I have to work from an old computer. I fear that might be the issue here. Doesn´t usually give me errors, but I don't really know much of the code yet to judge that. I'll try to find a new computer I can clone the repository to see if it works.

**Comment by jooste** [comment]
As a temporary fix you could try to remove the synthetic import in bluesky/stack/basecmds.py, and comment out the syn commands in the large dictionary in the same file.

**Comment by LuisNavarroGarcia** [comment]
Dear @ProfHoekstra,

Just tried that, cloned it straight into the desktop folder. However still throws the same error.

I'll try the temporary fix @jooste suggested until I can access a different computer and try again.

Thank you very much to both of you, I really appreciate all of your feedback! 

Congrats on such a great project!

**Comment by jooste** [comment]
Hi @LuisNavarroGarcia, did removing the synthetic import help? In that case commit ccd9cc6 should also fix your problems.

**Comment by LuisNavarroGarcia** [comment]
Hi @jooste, I've been trying several things (including the above mentioned) and the same error pops up from different parts of the code. I assume it's compatibility issues with the computer that I'll try to figure out, otherwise it would be really weird that I get this kind of error message all the time from different parts of the code. However, the conversation was of great help and I really really appreciate the time and effort! 

Sorry for the inconvenience and I really hope I was not much of an annoyance.

**Comment by jooste** [comment]
No problem! And if you have any more questions don't hesitate to ask. We are also interested in execution issues on different platforms and hardware configurations, so don't worry about inconveniencing us :)

**Comment by jooste** [comment]
Hi @LuisNavarroGarcia,

It turns out your problems were related to an import issues that was resolved in python3.7. I managed to circumvent the problem in commit 79ca0a0. BlueSky should now run again on Python 3.6.

**Comment by LuisNavarroGarcia** [comment]
Great to hear @jooste!!!

Thank you very much!
