### ISSUE TITLE
Issuing a Single Bank Angle & Heading Change for Conflict Reso Plugin

### ISSUE THREAD

**Issue by aidnaw** [TUDelft-CNS-ATM/bluesky#247]
Hello,

I'm interested in implementing a resolution algorithm for short range conflicts (tLOS < 2min), and have some questions about sub-classing conflict resolution since the documentation is not yet on the wiki. I've noticed in Eby and MVP, for example, that the conflicts seem to be incrementally solved, and a new track, tas, etc. are issued in every timestep using the resolve and update functions. How would one go about an implementation where the initial geometry of the conflict (relative spd and hdg) is the only input, and a desired bank angle and heading change are issued just once? I understand that the stack commands BANK and HDG may be useful, but I don't know how to deal with the incremental nature that the current CR seems to have.

Thanks in advance.

**Comment by jooste** [comment]
Hi Aidan,

Welcome to BlueSky!
There indeed isn't any documentation on subclassing for each of the individual classes yet, it's on the todo-list :) 
To avoid the incremental behaviour I would keep an additional per-aircraft or per-conflict flag. You set this flag to true after the first calculation of a resolution, and only (re)calculate a resolution when this flag is not set. If you go for a per-aircraft state use the TrafficArrays logic to make bluesky automatically increment and decrement the array size for you when aircraft are added and deleted.

The resolve function should return aircraft-sized arrays of track, TAS, V/S, and altitude. The bank angle is not in there, but you could indeed use the BANK stack command for that, or use [bs.]traf.setbanklim(idx, bank_limit). When the resolve function returns a target track/heading, the aircraft will turn in that direction with the given bank limit.

**Comment by aidnaw** [comment]
Thanks for the quick reply! I'm also interested in logging some traf.asas variables, but I can't figure out the syntax of how to do this from within BlueSky. For example, I've tried 'MYLOG from traf.asas add tLOS' and 'MYLOG add traf.asas.tLOS'.

**Comment by jooste** [comment]
Are you using the main version of BlueSky?

You can create a logger with the `CRELOG` command: `CRELOG MYLOG 1.0` would create the logger `MYLOG` with a periodic logging interval of 1 second. Once you've done that you can add variables to the logger with: `MYLOG ADD cd.tLOS` or similar. Note that in the main version of BlueSky, traf.asas doesn't exist anymore. Now you can find all conflict detection related data in traf.cd, and all conflict resolution related data in traf.cr.
