### ISSUE TITLE
Query about using bluesky in AI-assisted ATC research

### ISSUE THREAD

**Issue by epaulz-vt** [TUDelft-CNS-ATM/bluesky#248]
If this is not the appropriate channel for a general question, please point me in the right direction.

I am in the early stages of a small research project to design/implement an ATC system where some sort of external AI engine is integrated to assist a human controller in making decisions.  It seems to me that through the self-contained plugins, a skilled Python develop could notionally write a plugin to tie in such an external resource.  Could anyone close to the project confirm/deny that bluesky would be a good tool for this type of project?

Eric

**Comment by jooste** [comment]
Hi Eric,

You can indeed use Bluesky also for real-time applications, and it has also already been used in combination with (external) machine learning / reinforcement learning algorithms several times. If you look around at the different forks of bluesky on github you will find several implementations of bluesky combined with python RL libraries. Note that the graphical interface of BlueSky is not an ATCo screen: you might have to make one yourself if you need more than just a top-down representation of traffic. That is also possible as an external application to bluesky. You can find an example of an external client in the [wiki](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Connecting-external-applications-to-BlueSky).

**Comment by epaulz-vt** [comment]
Great.  Your response is very helpful for my planning.  I hope to contribute to the project in some way throughout the research.

Thank you.
