### ISSUE TITLE
TypeError: update() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by Broever101** [TUDelft-CNS-ATM/bluesky#255]
While copying the following tutorial: https://github.com/TUDelft-CNS-ATM/bluesky/wiki/plugin

I encountered this error:

```
Traceback (most recent call last):
  File "BlueSky.py", line 115, in <module>
    main()
  File "BlueSky.py", line 82, in main
    bs.net.run()
  File "C:\Users\stree\Desktop\bluesky\bluesky\network\node.py", line 67, in run
    bs.sim.step()
  File "C:\Users\stree\Desktop\bluesky\bluesky\simulation\simulation.py", line 95, in step
    simtime.update()
  File "C:\Users\stree\Desktop\bluesky\bluesky\core\simtime.py", line 73, in update
    fun.trigger()
  File "C:\Users\stree\Desktop\bluesky\bluesky\core\simtime.py", line 209, in call_timed
    self._callback()
TypeError: update() missing 1 required positional argument: 'self'
```

It's presumably the update function which is causing the issue. Weirdly, making update a @classmethod solves this issue, but with that, we can't register trafarrays. What am I missing?

**Comment by Broever101** [comment]
Update:

Setting self = None in the update function signature also resolves this issue. Weird.

**Comment by jooste** [comment]
Hi! This happens when the timed_function and command decorators are used on methods of a class that don't derive from core.Entity. The exception is currently not very explanatory, I'll change this when I get around to it.

**Comment by Broever101** [comment]
> Hi! This happens when the timed_function and command decorators are used on methods of a class that don't derive from core.Entity. The exception is currently not very explanatory, I'll change this when I get around to it.

Thanks for the timely reply.

Unfortunately, it's happening even with deriving from core.Entity. Here's what I'm doing:

`
def init_plugin():
    config = {
        'plugin_name':     'SIMGEN',

        'plugin_type':     'sim', 
        }
    return config 

class Simgen(core.Entity):
    def __init__(self):
        super().__init__()
        with self.settrafarrays():
            self.npassengers = np.array([])

    def create(self, n=1):
        super().create(n)
        self.npassengers[-n:] = [randint(0, 150) for _ in range(n)]

    @core.timed_function(name='simgen', dt=5)
    def update(self):
        stack.stack('ECHO Example update: creating a random aircraft')
        stack.stack('MCRE 1')
'`

As you can see, this identical to the code in Example.py with the exception of the name of the class and the name parameter passed to the timed_function. At first I was registering my own arrays with trafarrays and writing my own logic in the update and it gave me this issue, so I simply copied Example.py (which runs on its own). And it's still giving the same issue. What am I doing wrong?

**Comment by Broever101** [comment]
Update: 

The issue is resolved. I was not instantiating Simgen singleton object in the init_plugin() function. I glanced over Example.py closely and found that was the only difference. 

I think it should be mentioned in the plugin tutorial, very easy to miss for a beginner like me.

**Comment by jooste** [comment]
Yeah, I am also considering automatic instantiation of Entities in plugins to avoid this. This can only be undesired when Entities in a plugin are actually a subclass of another Entity in bluesky, but I can get around that.
