### ISSUE TITLE
Issue when calling BlueSky.py with an alternated config file.

### ISSUE THREAD

**Issue by amorfinv** [TUDelft-CNS-ATM/bluesky#257]
I created an alternate config file ([am.cfg.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/5913917/am.cfg.txt)). The only difference between am.cfg and settings.cfg is an extra plugin (ssd) and `start_location = 'GDL'`. When I call:

```
python BlueSky.py --config-file am.cfg
```

the window remains at EHAM and the SSD module is not loaded. This issue can be fixed by not calling an alternate config file and making the changes directly to settings.cfg. However, the issue will still be there when calling a default scenfile from the command line.

Proposed Solution:

Change the `addnodes` function at `bluesky/network/server.py` from:

```python
def addnodes(self, count=1):
    ''' Add [count] nodes to this server. '''
    for _ in range(count):
        p = Popen([sys.executable, 'BlueSky.py', '--sim'])
        self.spawned_processes.append(p)
```

to:

```python
def addnodes(self, count=1):
    ''' Add [count] nodes to this server. '''
    for _ in range(count):
        p = [sys.executable, 'BlueSky.py', '--sim']
        if '--config-file' in sys.argv or '--scenfile' in sys.argv:
            for i in range(len(sys.argv)):
                if len(sys.argv) > i + 1:
                    if sys.argv[i] == '--config-file':
                        cfgfile = sys.argv[i + 1]
                        p.extend(['--config-file', cfgfile])
                    elif sys.argv[i] == '--scenfile':
                        scnfile = sys.argv[i + 1]
                        p.extend(['--scenfile', scnfile])
            p = Popen(p)
        else:
            p = Popen(p)
        self.spawned_processes.append(p)
```

This will now ensure that the '--config-file' and '--scenfile' commands will get passed on. Hopefully this won't affect anything else. Now when I use am.cfg, the window is set to GDL.

Also, be sure to change line 98 from `bluesky/settings.py` to `print('Reading config from {}'.format(cfgfile))` so that the correct filename appears in the output.

Hope this works!

Shoutout to Andrei Badea for helping me with this issue.

**Comment by jooste** [comment]
Hi Andres! 

Thanks for the suggestion. Arguments indeed weren't passed on yet from the main to the simulation process(es). I decided to implement this a bit differently though, so that all arguments (aside from the one selecting the type of bluesky process to start) are passed on to child processes. See 31f463b.

**Comment by amorfinv** [comment]
very elegant solution. Thank you!
