### ISSUE TITLE
creconfs() issue

### ISSUE THREAD

**Issue by davidaranega96** [TUDelft-CNS-ATM/bluesky#258]
https://github.com/TUDelft-CNS-ATM/bluesky/blob/253742da22696df1e8d1a627f0892b0a53a48b5c/bluesky/traffic/traffic.py#L344

Hi guys, I believe that the bs.traf.creconfs() function is not working properly because the function that ends up creating the aircraft should be updated from self.create() to self.cre(). I don't know if I am missing.

Cheers!

**Comment by ProfHoekstra** [comment]
Thanks, you're right. It's fixed.
