### ISSUE TITLE
Plugin running in GUI or not.

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#259]
Is there a way to send to a plugin if the simulation is running with the GUI or not?

**Comment by jooste** [comment]
Hi! You want to know on the simulation side whether a gui is present? This information is currently not directly available, although you might be able to find out indirectly whether anything is known about a gui on the sim side. The ScreenIO object keeps track of things like zoom and pan per connected client. It does this in several dictionaries. If these dictionaries are not empty you know that either a client is connected, or that it was at some previous point in time.

If you have a good use-case for this we could add something more concrete on the TODO list!

**Comment by jooste** [comment]
Hi @Ellislee1! Without a good use case we currently won't pick this up, and will close this issue. If you do have a good use case just open the issue again and we can discuss it!
