### ISSUE TITLE
Conflicts are not detected if they take place across the lon = +/- 180 deg line. 

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#264]
Due to the way the bearing and distance between two aircraft are calculated, a conflict is not detected if it takes place across the longitude = 180 degrees line. 

To replicate, create a head-on conflict with aircraft on both sides of the line:
CRE AC1 B744 0   179.5 90 FL300 300
CRE AC2 B744 0  -179.5 90 FL300 300

The conflict will not be detected, as seen in the picture below:
![image](https://user-images.githubusercontent.com/37139260/111480424-47f0a580-8732-11eb-96fb-48c2494e6c9d.png)

**Comment by ProfHoekstra** [comment]
Fixed by adding wrap-around clipping to [-180,180] to some non-spherical calculations in geo.py
