### ISSUE TITLE
Using bluesky to build a reinforcement learning algorithm

### ISSUE THREAD

**Issue by sculyi** [TUDelft-CNS-ATM/bluesky#267]
Hi, everyone!
I want to build a reinforcement learning algorithm based on the bluesky tool.
Similar to  the pygame, I assume that the bluesky provides the application interface (API) to achieve the following functions by python code:
1 add or delete an aircraft
2 get the flight state, including  the lon, lat, alt, apd, hdg, etc
3 edit the route
4 control the flight based on my generated actions, such as control the spd, hdg, etc

However, I failed to find those interfaces from the package!
Anyone can help me about this issue.

**Comment by ProfHoekstra** [comment]
Yes, there certainly is a way to do that. Output/actions are performed by stacking commands, this makes your plugin more robuts. It is therefore advised to use the stack.stack(txt) function to stack any command you wish to be executed. 

You can do all the things you mention with stack commands (see the Command reference for details):
1) CRE or DEL command
2) Get the state: id2idx(acid) to get the index, and use this to read any of the traf.*** variables like lat,lon etc. As these arrays are dynamic the index might changes du to deletion and adding. If you keep your own lists make sure to use this traffic arrays feature as in the example plugin
3) ADDWPT acid and DELWPT , see the many featurs fo this command (FLYBY, FLYOVER, AFTER, AT, etc), also ORIG and DEST
4) HDG, SPD, ALT and VS command
