### ISSUE TITLE
RSZONEDH and RSZONER commands are present in the command reference but do not work in BlueSky

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#269]
These two commands are present in the command reference but are no longer part of the core BlueSky functions. It would be great to have them in order to set the vertical and horizontal protection zones from within scenarios.

**Comment by ProfHoekstra** [comment]
These commands were indeed present in the past (originally they come from a closed-source predecessor). 

Currently there is a setting in the settings.cfg file, asas_mar, in which the margin is set. This used as a factor for the resolution. The default value is 1.05 but this could also be less than 1.0 in case of sharing the effort between aircraft.

I would propose that in the settings.cfg we specify not one, but two factors for horizontal and vertical margins (e.g. asas_mar_h and asas_mar_v). Then these commands could also again be implemented, by modifying the values of the factors to fit the absolute value as specified by the user in the commands.

**Comment by andubadea** [comment]
Sounds good! A potential use case would be if one wants to run several scenarios in a row using different types of aircraft. The scenarios could then be loaded automatically one after the other, and settings would be applied to suit each one.

Maybe a "LOADCFG" function would be a more universal solution, where a .cfg file can be loaded using a stack command. Then, the settings can be applied from within the scenarios (at the beginning) by just loading the desired config file.

**Comment by jooste** [comment]
`LOADCFG` wouldn't really work, since many config variables are only considered during startup..

**Comment by ProfHoekstra** [comment]
And it would create invisible dependencies, e.g. making is susceptible to changes in settings.

The philosophy of BlueSky to control everything directly from scenario files. You can achieve the same as a loadcfg by calling another scenario file which contain the commands with your settings. 

This is also how Emmanuel set up his experiments.

P.S. I'm already implementing the commands RSZONER and RSZONR and the split between hor/vert in settings where the default values are as a factor. The commands alter the factor. In parallel, there is a branch under development for per aircraft pz dimensions.

**Comment by ProfHoekstra** [comment]
Commands RSZONER [zone radius in nm] and RSZONEDH [zonde dh in ft] have been restored.
