### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#270]
I have been doing some ML stuff, meaning that it has been runing for a while. Today afer about an hour I got the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
    File "C:\Users\Project Apollo\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
        self.run()
    File  "C:\Users\Project Apollo\Desktop\RL-Air-Traffic-master\bluesky-master\bluesky\network\server.py", line 137, in run
        sender_id = route[0]
IndexError: list index out of range
```
This is the first time in many hours of running this that I have seen this error. The simulation does still run in the background but the GUI is compleatly frozen up and unresponsive.

**Comment by jooste** [comment]
Hi!

This is difficult to debug without knowing what triggered it. I'll have a look at it when I have the time.

**Comment by jooste** [comment]
Hi @Ellislee1, this is a really weird bug: in the case you describe, an empty multipart message is received. This should not happen. I've added a check to avoid further processing of empty messages, see 5a43f83.
