### ISSUE TITLE
Using smaller thresholds for non-airliner in vertical navigation thresholds

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#272]
The threshold for vertical navigation seems to be hard-coded to be 10ft. I noticed two issues regarding this when simulating a hexacopter on a relatively small scale.

1. Negative changes in altitude (descending) are not registered or executed if the change is equal or lower than 10 ft.
2. The altitude of the aircraft changes suddenly to the target altitude once the difference between current and target altitude is lower than 10 ft.

In the attached scenario (and gif), the altitude change between WPT10 and WPT9 is executed but is sudden, the altitude change between WPT9 and WPT8 is ignored (equal or lower than 10), but it is executed for WPT7 (change in altitude is 11 ft). The latter is almost sudden, as the aircraft only descends 1ft before suddenly being set to the target altitude.  

![ySR7JSZbf5](https://user-images.githubusercontent.com/37139260/114845685-a3bb5680-9de4-11eb-96b4-60d43487e99c.gif)

Maybe a solution to this would be to be able to set the VNAV threshold using a command for each aircraft. 

[M2_test_2.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6316696/M2_test_2.scn.txt)

**Comment by ProfHoekstra** [comment]
Yes, agreed. Many of these thresholds are still based on airliners, but should be made dependent on the class of vehicles.

**Comment by ProfHoekstra** [comment]
Looking at this now. Seems indeed to be caused by the threshold/deadband value. 

You are aware there is, on purpose, also an asymmetry w.r.t. to climbing and descending, right? The FMS will always climb as soon as possible and allowed by previous altitude constraints, if any. And it will descend as late as possible. This is required to induce a cruising altitude behaviour. 

This does not explain this issue obviously, but it have a role in the asymmetry at which can occur in VNAV issues in general.

**Comment by andubadea** [comment]
Yes, I noticed the "climb as soon as possible" and "descend as late as possible" strategy. We might need to modify this when looking at drones in urban environments.

On my local copy of the source code, I replaced all the "10. * ft" limits with "0.9 * ft" and everything seems to work well.

**Comment by ProfHoekstra** [comment]
We still need to maintain this even for UAVs to have the opportunity to specify cruise alt behavior in a flight plan.

A solution that still allows what you might want is using the new AT command ( I’m currently modifying that in such a way that it issues any command for this aircraft when passing the waypoint). This will be available shortly.

Examples:

KL204 AT LOPIK ALT FL70
KL204 AT LOPIK SPD 250
KL204 AT LOPIK HDG 90
KL204 AT LOPIK VNAV ON

The syntax is then:

<acid> AT <wptinrte> <cmdtxt>   this will issue the command <acid cmdtxt> when passing it.
Is equivalent to: AT <acid> <wptinrte> <cmdttxt>

Multiple commands can be stacked at a waypoint in this way. You can also make it climb and descend immediately.

When altitude are specified in as part of a route, we should always maintain the cruising behaviour. But the AT command gives you the flexibility to do whatever you want at any waypoint.

**Comment by ProfHoekstra** [comment]
Altitude capture is now time-based and independent of scale of altitude step or vehicle.
