### ISSUE TITLE
DELRTE command is broken

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#275]
The DELRTE command is currently not functioning. It gives the following error:

![image](https://user-images.githubusercontent.com/37139260/115022716-7050f880-9ec6-11eb-900f-6f2d3bd50793.png)

This can be fixed by changing line 914 in bluesky/traffic/route.py from:
`self.__init__()`
to
`self.__init__(bs.traf.id[iac])`
or simply
`self.__init__(self.acid)`

**Comment by ProfHoekstra** [comment]
Suggested fix has been made in route.py and tested.

Thanks!
