### ISSUE TITLE
ALT command does not work with some types of OpenAP aircraft

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#276]
In short, changing the altitude with the "ALT" command works for some aircraft (like a B744), but not for all. In the attached scenario file, there are three aircraft: A B744 and two M600 (Matrice 600 hexacopters). 3 seconds into the simulation, they all receive an altitude command:

```
00:00:00.00>CRE HX1 M600 0 0 0 100 20
00:00:00.00>CRE HX2 M600 0 1 0 FL100 20
00:00:00.00>CRE AC1 B744 0 -1 0 FL200 300

00:00:03.00>ALT HX1 50
00:00:03.00>ALT HX2 FL90
00:00:03.00>ALT AC1 FL90
```

It appears that only the B744 aircraft executes a change in altitude. The commands given towards the M600s have no effect.

[alt_test.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6325134/alt_test.scn.txt)

**Comment by ProfHoekstra** [comment]
Which performance models do you use? OpenAP or BADA? And could you try the other to see if it if specific to one database?

**Comment by andubadea** [comment]
Ah yes. I initially used OpenAP. All aircraft descend if I use BADA or Legacy. So it seems the issue is OpenAP-specific.

**Comment by junzis** [comment]
This should be fixed now. (seems to only affect M600)

Note that M600 is a DJI drone, which does not exist in BADA. It will be changed to the default B744 automatically if you change to BADA model.
