### ISSUE TITLE
DELWPT not working when deleting active way point

### ISSUE THREAD

**Issue by amorfinv** [TUDelft-CNS-ATM/bluesky#277]
The DELWPT command is having some issues when deleting the active waypoint. 

I attached a scenario with three waypoints. After deleting the active wpt, aircraft keeps going towards deleted wpt. Once reaching the deleted wpt, it skips a wpt.

https://user-images.githubusercontent.com/78442543/115036331-b65d8a80-9ecd-11eb-9a30-69a1062068cb.mov

I think it can be fixed by adding the code below between lines 937 and 939 of bluesky/traffic/route.py

```python
        # check if active way point is the one being deleted and that it is not the last wpt.
        # If active wpt is deleted then change path of aircraft
        if self.iactwp == idx and not idx == self.nwp - 1:
            self.direct(iac, self.wpname[idx+1])
```

The attached scenario should now look like this

https://user-images.githubusercontent.com/78442543/115040506-cc6d4a00-9ed1-11eb-88e0-af66558e63f8.mov

Scenario file:
[am1.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6325903/am1.scn.txt)

**Comment by ProfHoekstra** [comment]
Suggested fix has been made in route.py and tested.
