### ISSUE TITLE
How to run known scenario repeatedly without GUI

### ISSUE THREAD

**Issue by epaulz-vt** [TUDelft-CNS-ATM/bluesky#278]
Hello,

I am trying to understand how to run the simulation without the GUI as I am performing many iterations of the same scenario.  I am trying 'python BlueSky.py --headless --scenfile merge.scn', but it seems to pause after loading plugins and never actually initiates the scenario.  Am I missing something?

Eric

**Comment by jooste** [comment]
Hi Eric!

It depends what you want to achieve. If you want to run bluesky simulations from within another python program you can import bluesky as well and control it manually. If you want to repeatedly start a bluesky simulation process from a script (.bat, .sh), you can start isolated simulations with the `--detached` argument. You can also create batch scenario files, and let bluesky distribute those over the available cpu cores of your computer. This is done with the `BATCH` command. You can find example batch scenario files in the `scenario` folder. Finally, you can run bluesky in headless mode (`--headless`). This starts a bluesky server to which you can connect with a bluesky client (`--client`).

Hope this helps!
```

**Comment by jooste** [comment]
I assume this is solved, so I'll close this issue!
