### ISSUE TITLE
GUI needs to show actual PZ size of aircraft during runtime, not just default 5 nm value or just the one from settings. 

### ISSUE THREAD

**Issue by ProfHoekstra** [TUDelft-CNS-ATM/bluesky#279]
GUI needs to know the PZ radius as set by the ZONER command.

Soon for individual aircraft, this might even deviate from the default value as given by ZONER command (runtime) or setting file (initialization). That should also be visible in the GUI then. Currently this is part of a new branch, soon to be merged. This issue is just a reminder to also update the GUI.

**Comment by jooste** [comment]
Implemented in 3963748.
