### ISSUE TITLE
Question: Running different configurations of the same scenario

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#280]
Hello,

I have a scenario, with let's say 10 aircraft. However, I also need to change parts or all of the trajectory for some of the aircraft, e.g. delay one aircraft, make a heading change etc. I can create a new scenario for each combination of changes, but this is not really efficient if I have to change a lot of aircraft, with a lot of possible combinations. 

Is there a way I can leverage bluesky's features for a more efficient approach to my problem?

Cheers,
Ralvi

**Comment by ProfHoekstra** [comment]
Dear Ralvi,

No, it can be any string. Check out EHAM procedures, where the variable %0 is used for a call sign.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 10 May 2021, at 19:48, Ralvi Isufaj ***@***.***> wrote:

﻿

Hi Joost,

Thanks for the quick and very helpful reply!

Are the arguments of PCALL (except for the scenario file obviously) bluesky commands? For instance, is var0 simply a HDG AC1 150?

**Comment by risufaj** [comment]
I see, thank you very much!
