### ISSUE TITLE
Aircraft slow down too early for FLYTURN waypoints

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#291]
Whenever I use a FLYTURN waypoint, I noticed that the aircraft slows down a considerable amount of time before it actually starts turning. If I replace the waypoint with a FLYBY waypoint with a speed constraint, then the aircraft starts slowing down much later.

This scenario file (also attached) shows two aircraft performing the same (mirrored) manoeuvrer. DRON1, which uses a turn waypoint, starts slowing down about 5 seconds before DRON2 does, which has a speed constraint.

```
00:00:00.00>HOLD
00:00:00.00>PAN 41.140648,-75.068741
00:00:00.00>CRE DRON1 M600 41.131908 -75.107251 90 90 30
00:00:00.00>CRE DRON2 M600 41.121908 -75.107251 90 90 30
00:00:00.00>ADDWPT DRON1 FLYTURN
00:00:00.00>ADDWPT DRON1 TURNSPEED 10
00:00:00.00>ADDWPT DRON1 41.131908 -75.097251
00:00:00.00>ADDWPT DRON1 FLYBY
00:00:00.00>ADDWPT DRON1 41.141908 -75.097251
00:00:00.00>ADDWPT DRON1 FLYBY
00:00:00.00>ADDWPT DRON2 41.121908 -75.097251 ,, 10
00:00:00.00>ADDWPT DRON2 41.111908 -75.097251 ,, 10
00:00:00.00>LNAV DRON1 ON
00:00:00.00>VNAV DRON1 ON
00:00:00.00>LNAV DRON2 ON
00:00:00.00>VNAV DRON2 ON

```

While it does make sense that the aircraft needs to slow down earlier than in the FLYBY case to ensure the turn conditions are met, DRON1 only starts turning 27 seconds after it slowed down. 

[turnspd_test.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6597672/turnspd_test.scn.txt)

**Comment by andubadea** [comment]
I think this could be solved by applying the speed constraint logic (decelerate as late as possible) combined with the calculated turn radius for a waypoint to determine when to start decelerating.

**Comment by andubadea** [comment]
I think I have found the issue. In `autopilot.py`, on line 296 there is the following code:
```
useturnspd = np.logical_or(bs.traf.actwp.turntonextwp,(dist2wp < dxturnspdchg+bs.traf.actwp.turndist) *\
                                                      swturnspd*bs.traf.swvnavspd*bs.traf.swvnav*bs.traf.swlnav)
```
This decides per aircraft whether to use the turn speed or not. The first issue is that here, bs.traf.actwp.turndist is calculated at the current speed and not the turn speed. Thus, the calculated distance to turn is for a usually much faster speed. Because of this, the aircraft actually starts slowing down way in advance. A solution for this is to create a new array in bs.traf.actwp that keeps track of the turn distance considering the commanded turn speed.

The second issue is in the calculation of `dxturnspdchg`, found on line 281:
```
dxturnspdchg  = np.where(swturnspd, np.abs(turntasdiff)/np.maximum(0.01,ax)*(bs.traf.tas+0.5*np.abs(turntasdiff)),
                                                                   0.0*bs.traf.tas)
```

I think the prediction would be better if the analytical solution would be used, and then multipled by a safety factor:
`dx = abs((Vtarget**2 - Vinitial**2)/2/np.maximum(0.01, ax)) * 1.1`

On an unrelated note, the same formula could also be used for `dxspdconchg` on line 290. 

The third issue I found in `autopilot.py` related to this is on line 178:
```
if bs.traf.actwp.flyturn[i] and bs.traf.actwp.turnrad[i]<0.0 and bs.traf.actwp.turnspd[i]>=0.:
                turntas = cas2tas(bs.traf.actwp.turnspd[i], bs.traf.alt[i])
                bs.traf.actwp.turndist[i] = bs.traf.actwp.turndist[i]*turntas*turntas/(bs.traf.tas[i]*bs.traf.tas[i])
```

I think this is where the turn distance should be set to the actual turn distance considering the given turn speed. However, this always gets overwritten every simulation cycle, as this code only gets called when the active waypoint is reached, while `bs.traf.actwp.Reached` is called every simulation step. The values for `bs.traf.actwp.turndist` are calculated in `bs.traf.actwp.Reached` using the actual speed and not the turn speed.

**Comment by ProfHoekstra** [comment]
Good point. Sometimes, mostly, obviously the normal speed is needed as well, but indeed in some cases this makes it too early. I will have a look at implementing these good suggestions, while carefully testing that it also keeps working in normal flight plans, without specified turn radii or turn speeds and for airliner-like flight plans. Thanks!

**Comment by ProfHoekstra** [comment]
Fixed in https://github.com/TUDelft-CNS-ATM/bluesky/commit/fdf3308ddbcac38339306e1bc7cf3f4416c30c42
