### ISSUE TITLE
How to modify some icon when running the BlueSky GUI interface

### ISSUE THREAD

**Issue by weiguowilliam** [TUDelft-CNS-ATM/bluesky#293]
Hi guys, I try to modify some icons (change color/size...) when running the BlueSky Gui interface. I thought it should be somehow related to `server.run()` part. But I got lost in pyzmq package...

Could you please help me with this? Maybe a code demo. Thanks in advance.

**Comment by jooste** [comment]
Hi!

Color and size of icons are controlled in bluesky's settings file, and in a global palette configuration.

In your settings.cfg you will find `text_size`, `apt_size`, `wpt_size` and `ac_size`, as well as `colour_palette`. You can create a custom palette file in data/graphics/palettes, and point to it in your settings file.

**Comment by weiguowilliam** [comment]
Thanks. I found that. My question is if we can change the icon when BlueSky is already running. e.g., when aircraft is [under a specific condition], we make its size larger?

**Comment by jooste** [comment]
Hi, it's only read on startup. You currently can't change such default colours or sizes during runtime for all objects. Colours of aircraft you can, however, already change during runtime, with the COLOR command.

**Comment by weiguowilliam** [comment]
Thank you! `COLOR` should be good! I don't find `COLOR` command on this page (https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Command-Reference). Does that mean you create some new command (e.g., COLOR)?

**Comment by jooste** [comment]
Ah, you're right. Seems the command reference is not up to date anymore! That's something we'll have to look into!

**Comment by weiguowilliam** [comment]
Thanks!
