### ISSUE TITLE
[Enhancement] Making all classes marked as "replaceable" actually replaceable through plugins

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#296]
In Bluesky, there are many core classes that are market as replaceable, which provides a great way to customise their implementation without modifying the core Bluesky functions. However, only few of these classes can actually be implemented within a plugin due to the lack of commands to replace them. For example, conflict detection has the command 'CDMETHOD', and conflict resolution has 'RESO', but there is no way to enable an Autopilot plugin, even if the Autopilot class is marked as replaceable. 

I think it would be great to have commands for the other classes as well, either through a command of their own (for example, AUTOPILOT for choosing an autopilot plugin), or maybe it would be best to have a universal command that can replace any class marked as replaceable. For example, through the PLUGINS command:

`PLUGINS LIST` returns `AREA, DATAFEED, MYAUTOPILOT`
then using the command
`PLUGINS ENABLE MYAUTOPILOT`
Bluesky would automatically load MYAUTOPILOT as an Autopilot plugin. Lastly, a command like
`PLUGINS RESET`
would reset all plugins and use the core classes again.

**Comment by jooste** [comment]
Hi Andrei, There actually is a general command for this: `IMPL` (or `IMPLEMENTATION`). The `CDMETHOD` and `CRMETHOD` functions are just there because they provide additional functionality.

**Comment by andubadea** [comment]
Oh I see! Thank you!
