### ISSUE TITLE
Aircraft routes don't appear anymore with the POS command

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#299]
With the latest update, on my machine, aircraft routes do not appear anymore when using the POS command or double clicking an aircraft. The information is displayed in the command area, but no route path is visible on the map. 

![image](https://user-images.githubusercontent.com/37139260/124106578-0085ef00-da6d-11eb-8ed3-d1aa5f23a77b.png)

I am very sure that the aircraft have paths, as they follow them when simulating.

**Comment by jooste** [comment]
Fixed in bf888bb!
