### ISSUE TITLE
Issue with vectorised conf.rpz

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#305]
Now that the protection zone is a per-aircraft specification, conf.rpz is in vector format. However, some parts of the code were not adapted for this. I get the following error when I try to use MVP as a resolution method:

```
  File "bluesky\traffic\asas\mvp.py", line 316, in MVP
    if (conf.rpz * self.resofach) < dist and dabsH < dist:   
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by andubadea** [comment]
I also found the same thing in resolution.py, conf.rpz is used without an index a couple of times in ```resumenav```.

**Comment by andubadea** [comment]
The same errors appear with conf.dtlookahead, conf.hpz in MVP and more locations in Bluesky.

**Comment by andubadea** [comment]
An issue related to this is that, in Statebased.py, rpz is taken as a diameter instead of a radius. An easy fix entails creating a new variable called "dpz = rpz * 2".

**Comment by jooste** [comment]
Hi Andrei,

I think that if you follow the equations in statebased.py you'll find that RPZ is used correctly, not as a diameter. (I think it's only used in a comparison with dCPA, `dcpa2 < R2`).

**Comment by andubadea** [comment]
Hi Joost,

Then the problem might be somewhere else then (either in statebased or in the drawing and interpretation of RPZ).
In the Bluesky settings.cfg file, I set the following value:
asas_pzr = 0.00863930885529 [nm]
Which is equivalent to 16 m. Thus, because this is a radius, I expect that the minimum separation between two aircraft to be 32 meters.
x <------- 32m -------> x

But then I run the following scenario with two aircraft heading towards each other with a small offset:
```
00:00:00.00>HOLD
00:00:00.00>ASAS ON
00:00:00.00>PAN 41.142025 -75.069111
00:00:00.00>ZOOM 40
00:00:00.00>CRE DRON1 M600 41.141908 -75.07811 270 50 30
00:00:00.00>CRE DRON2 M600 41.142068 -75.08011 90 50 30
```

The minimum distance between these two aircraft is approximately 18 metres, and their separation bubbles intersect, but no conflict is detected, which I think is due to the fact that statebased takes "rpz" as the required separation, not as half the required separation.

**Comment by jooste** [comment]
The circles indeed intersect: they also have RPZ as radius. Only when an aircraft falls inside another circle, a loss of separation occurs. If you want touching circles to indicate a LoS, the circle radius should be half the rpz. However, with variable (uneven) RPZ this doesn't make sense.

**Comment by andubadea** [comment]
Oh I understand now. 

So then, if I want 32m separation between two drones, I need to set asas_pzr as the equivalent to 32m. 

Thanks for the clarifications!

**Comment by andubadea** [comment]
Fixed in https://github.com/TUDelft-CNS-ATM/bluesky/commit/4d11c391ef310229cf3ce06ac1c8672642ffdb63.
