### ISSUE TITLE
Aircraft starts flying backwards if RTA is unattainable

### ISSUE THREAD

**Issue by undefiened** [TUDelft-CNS-ATM/bluesky#306]
If RTA is unattainable, the aircraft just starts flying backward with negative speed.
As an example see the scenario below where the a/c starts flying backwards around waypoint D8_5.

Scenario:
[bug_scenario.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6830779/bug_scenario.txt)

**Comment by ProfHoekstra** [comment]
Thanks, we are changing a lot of limits for adapting to the scale of UAS simulations. I will have a look at this to prevent this from happening.

**Comment by ProfHoekstra** [comment]
Should be fixed in [fdf3308](https://github.com/TUDelft-CNS-ATM/bluesky/commit/fdf3308ddbcac38339306e1bc7cf3f4416c30c42
