### ISSUE TITLE
Bluesky does not reset CR properly

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#313]
A reset command doesn't reset conflict resolution completely. It seems some behaviour from a CR-enabled scenario is still present after a reset.

I have attached two example scenarios. If I open a fresh instance of Bluesky and run the scenario that only has ASAS on (CRtest.scn), the two aircraft should enter a series of conflicts at about 00:02:40. However, because CR is not enabled. They should just continue following their path, which in this situation they do:

![image](https://user-images.githubusercontent.com/37139260/130125152-f400dd0a-bacd-4cb7-bd5e-96b27a384f4a.png)

I stop the scenario, run a RESET command from the bluesky console, and the load CRtestMVP.scn, an identical scenario that only has MVP enabled with RMETHH SPD. I let it run for a few seconds and then I stop the scenario and do another RESET command. I then load the CRtest.scn scenario again (the one without CR enabled). 

This time, at about 00:02:55, a conflict is detected between the aircraft, and it seems that, even though CR is not enabled, Bluesky freezes their heading and speed as if they are doing conflict resolution, thus they both overshoot their turn:

![image](https://user-images.githubusercontent.com/37139260/130125652-9a35148e-9584-497f-a2f4-79a422dafc2c.png)

I think this is due to something related to CR not resetting properly when a reset command is run. This also affects batch simulations if scenarios without CR are ran after scenarios with CR enabled.

I have attached the two scenarios I used for this demonstration. 

[CRtest.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/7016912/CRtest.scn.txt)
[CRtestMVP.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/7016913/CRtestMVP.scn.txt)

**Comment by andubadea** [comment]
This behaviour also happens even if RESOOFF is called on D90 and D93 when running the non-CR scenario the second time.

**Comment by jooste** [comment]
Fixed in f4a819e.
