### ISSUE TITLE
SPD command takes entered value as m/s instead of kts

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#315]
Simply put, the command `SPD acid X` now interprets X as m/s instead of kts.

Example:
```
00:00:00>CRE D1 M600 52.27065 2.04949 90 30 20
00:00:00>SPD D1 5
```
D1 will then decelerate to 10 kts, equivalent to approximately 5 m/s.

**Comment by jooste** [comment]
This is WIP as discussed at the last hackathon, but 253860a should be a quick-and-dirty fix.

**Comment by andubadea** [comment]
> 
> 
> This is WIP as discussed at the last hackathon, but [253860a](https://github.com/TUDelft-CNS-ATM/bluesky/commit/253860adf6360d10a1588640188a3a12e531446d) should be a quick-and-dirty fix.

I think this broke the CRE command now. After creating an aircraft at any speed, it proceeds to decelerate to half its speed. So
````
00:00:00>CRE D1 M600 52.27065 2.04949 90 30 20
```

decelerates to 10 kts.
