### ISSUE TITLE
Aircraft fly backwards if last waypoint has a speed constraint and VNAV is on

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#316]
While this bug has been previously fixed, it is somehow back. 

Aircraft start flying backwards if the last waypoint in their route has a speed constraint, VNAV is on, and they have just passed the respective waypoint. An example:

```
CRE D1 M600 52.270765 2.04949 90 30 20
ADDWPT D1 52.270765 2.054839 ,, 15
VNAV D1 ON
```
After it has passed the final waypoint, aircraft will start flying backwards.

Previously, this was due to the "Reached" function being called twice, which means that the placeholder speed of -999, set when an aircraft has passed the final waypoint, gets passed on to the autopilot.

**Comment by jooste** [comment]
Should be resolved in 92cdacf!
