### ISSUE TITLE
Creating more than one aircraft sets the speeds of all other aircraft to 0

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#318]
Steps to reproduce:
1. Create an aircraft (Any, but for best results, one that can hover, an M600)
2. Create a second aircraft

The speed of the first aircraft should be set to zero as soon as the second aircraft is created. If a third aircraft is added, the speed of the second one is set to 0, and so on. Only the latest added aircraft has a non-zero speed.

Example scenario:
```
0:00:00.00>CRE MS841, M600,  51.42972,   4.15673, 118.4 30, 30
0:00:10.00>CRE LY620, M600,  49.97940,   5.68314, 335.4 30, 30
```

**Comment by jooste** [comment]
Fixed in 95f45ee (hopefully this time without creating a new bug 😉).
