### ISSUE TITLE
txt2tas function

### ISSUE THREAD

**Issue by SerkanGuldal** [TUDelft-CNS-ATM/bluesky#323]
Hello,
I am trying to make a traffic low. `trafgen` looks like an option but there is a bug.
In` plugins>trafgenclasses.py`, `txt2tas` function uses 1 parameter. However, it is defined by 2 parameters in `bluesky>tools>misc.py` as `txt2tas(txt, h)`.
This mismatch needs to be fixed.

Also, is there any way to define a simple traffic from point A (created) to point B (deleted)?
Any scenario file will be appreciated.

**Comment by jooste** [comment]
Hi!

The bug you mentioned is fixed in f603c98. I think the behaviour you are looking for is *almost* possible with the trafgen plugin, but that would require some edits to the code. Maybe the creator of this plugin can weigh in, @ProfHoekstra ?
