### ISSUE TITLE
Fast Forward the Simulation

### ISSUE THREAD

**Issue by hemjyoti** [TUDelft-CNS-ATM/bluesky#324]
Hello Professor,

I am trying to fast-forward the simulations using Bluesky plugins, but I am unable to do it. However I am able to fast forward the simulation using the command line.

For instance, if I write, "FF" or "DTMULT 10" in the command line, the simulation does becomes fast. But when I try to do the same thing with the plugins using stack function  stack.stack('DTMULT 20') or stack.stack('FF'), then it does not work. 

Please note that I am able to successful run other stack function using plugin, except for the fast-forward. 

I will highly appreciate if you can help me solve it. Thanks !

**Comment by jooste** [comment]
Hi! This is difficult to assess without more information / a MWE, but my first guess would be that your plugin sends these commands when the simulation is not yet in `OP`. What happens if you do the following:
```python
stack.stack('OP;FF')
```

**Comment by hemjyoti** [comment]
Thank you so much, professor !  Issue solved and thus closing the issue.
