### ISSUE TITLE
Issuing a specific Bank Angle

### ISSUE THREAD

**Issue by hemjyoti** [TUDelft-CNS-ATM/bluesky#326]
Hello Professor,

I am trying to limit the maximum bank angle of the aircraft, using the command BANK. 
I tried issuing the command BANK using the command " BANK KL001 30", where KL001 is my aircraft ID.

I end up getting the error as follows:
'Traffic' object has no attribute 'bank'

Can you please give me some pointers ? 

Thank you

**Comment by jooste** [comment]
Are you completely up-to-date with the master version of BlueSky? A bug in the `BANK' command that caused the behaviour you are describing was fixed recently.

**Comment by hemjyoti** [comment]
Thank you again professor ! I just updated the master branch and the problem is solved. Thank you so much for your prompt reply !
