### ISSUE TITLE
Unable to run Bluesky

### ISSUE THREAD

**Issue by johannafernandezlubary** [TUDelft-CNS-ATM/bluesky#329]
hi, I'm having some issues while trying to run Bluesky on my computer. I'm using Anaconda Prompt (Anaconda 3), already installed all the requirements however, I still keep getting stuck with opengl problems which can be seen in the picture attached below
![opengl prob](https://user-images.githubusercontent.com/92155756/136538379-ee0014b3-a35a-412b-bc2d-7f0cb39fe4f6.PNG)
.

Anyclue what is happening? I'd really appreciate some help.

Thank you very much in advance.

**Comment by jooste** [comment]
Hi Johanna,

This probably is because you don't have pyopengl installed. It's only needed to generate the airport layout polygons, but not having it will stop bluesky from running!

**Comment by johannafernandezlubary** [comment]
> Hi Johanna,
> 
> This probably is because you don't have pyopengl installed. It's only needed to generate the airport layout polygons, but not having it will stop bluesky from running!
