### ISSUE TITLE
Opengl problems

### ISSUE THREAD

**Issue by johannafernandezlubary** [TUDelft-CNS-ATM/bluesky#330]
Hi everyone,

I have installed pyqt5 pyqtwebengine, numpy, scipy, matplotlib,  pandas, pyopengl, pyopengl-accelerate, msgpack, zmq, pygame in anaconda prompt in order to open BlueSky.  I've even tried freeglut to get opengl through codeblocks and in that enviroment it works perfectly whereas in my anaconda prompt when I'm about to run BlueSky still returns me this:

(base) C:\xxxxx\xxxx\xxx\xxxx\xxxxI\bluesky\bluesky>BlueSky.py
Reading config from settings.cfg
Using Python-based geo functions
Bluesky needs OpenGL.GLU
Run setup-python.bat (Windows) or check requirements.txt (other systems)
Install using e.g. pip install OpenGL.GLU
BlueSky normal end.

then I run the setup-python.bat, check the requirements and it comes back with a "requirement already satisfied" message. But when I try pip install OpenGL.GLU it still returns:
ERROR: Could not find a version that satisfies the requirement OpenGL.GLU (from versions: none)
ERROR: No matching distribution found for OpenGL.GLU

I'll appreciate any help,

Thanks in advance

**Comment by jooste** [comment]
Hi @johannafernandezlubary, could you let me know the versions of the pyopengl packages installed by Anaconda, and if you installed it with Conda or Pip? Apparently their package of pyopengl doesn't include GLU anymore, so it's useful to know from which version on this is.

If you installed them through conda you could try installing them through pip, I think those packages do still contain GLU.
