### ISSUE TITLE
A condition might not behave as expected because of the [0,360] modulo thing

### ISSUE THREAD

**Issue by richardalligier** [TUDelft-CNS-ATM/bluesky#332]
Hello,

I believe that the lines below, in some corner cases, are not doing what the author expected because of the [0,360] modulo thing.

https://github.com/TUDelft-CNS-ATM/bluesky/blob/4d2fcf3d7a3938404e00d5a33361bed744e601c1/bluesky/traffic/asas/resolution.py#L147-L148

Best regards,
Richard

**Comment by jooste** [comment]
Also thanks for this one, merged just now!
