### ISSUE TITLE
failed to load BADA performance model

### ISSUE THREAD

**Issue by weiguowilliam** [TUDelft-CNS-ATM/bluesky#336]
I use `79ca0a0 ` version. And I can run BlueSky.py and check.py successfully. The question is during the initialization/check it shows 'failed to load BADA performance model'. I wonder if there would be any influence? How should I repair this? Thanks:)

**Comment by ProfHoekstra** [comment]
That is indeed normal behaviour if you did not install the BADA data files. It will then default to OpenAP.

We cannot distribute the BADA files for license purposes. But if you put the BADA (v3.x) in the data/performance/BADA folder BlueSky will automatically see them and load them.

**Comment by weiguowilliam** [comment]
@ProfHoekstra Thank you for helping close the issue. I forgot to close that. Sorry for that:)
