### ISSUE TITLE
KeyError in bluesky.tools.areafilter after resetting the simulator

### ISSUE THREAD

**Issue by MiGiliam** [TUDelft-CNS-ATM/bluesky#337]
Using the function get_intersecting() from bluesky.tools.areafilter, I encounter problems after resetting the simulation. The function uses areatree which is an instance of class rtree.index.Index(). Using areatree.intersection(_coordinates_), a list is found containing all objects from areatree that intersect the given coordinates (line 69). Finally, the corresponding areas of class Shape() are found using the WeakValueDictionary() areas_by_id (line 70).

After resetting the simulator and loading a new scenario, a KeyError might be encountered when looking up the intersecting areas in areas_by_id (line 70). I tried printing the ids returned by areatree.intersection() (line 69) and it appears that the objects in areatree are not deleted when the simulation is reset. Therefore, areas created before reset still exist in areatree and are checked for intersections. However, they are removed from areas_by_id after reset, hence the potential KeyError.

In order to also delete the objects in areatree, the following line should be added to the function reset() on line 59, before basic_shapes.clear():
>[area.\_\_delete\_\_() for area in basic_shapes.values()]

After implementing this line, the KeyError did not occur again. Finally, it could be neat to reset the global counter to keep track of used shape ids in reset():
>Shape.max_area_id = 0

Do you think implementing these changes would cause problems elsewhere in BlueSky?

**Comment by jooste** [comment]
Hi Michiel,

This was actually a bug where __delete__ was used instead of __del__. This should be fixed in 3f797d2.

**Comment by MiGiliam** [comment]
Hi Joost,

Thanks, that fixed the problem!
