### ISSUE TITLE
Old aircraft route reappearing on radar screen after reset

### ISSUE THREAD

**Issue by MiGiliam** [TUDelft-CNS-ATM/bluesky#344]
I encountered a small issue with aircraft routes being displayed on the radar map. When a simulation is reset while an aircraft with active waypoint is currently selected (using double click before reset), the route of that aircraft reappears on the screen when a new aircraft is created after reset. This seems to be purely visual, the old route does not apply to the new aircraft. After double clicking the new aircraft, the old route disappears. Below, you can find a screen recording showing what happens:

https://user-images.githubusercontent.com/26272893/144228606-3fb5645c-da45-4bb8-bc36-d47c1a1aed77.mp4

**Comment by jooste** [comment]
Should be fixed in 8382e60!
