### ISSUE TITLE
OSError: could not find or load spatialindex_c-32.dll

### ISSUE THREAD

**Issue by borisdjartov** [TUDelft-CNS-ATM/bluesky#347]
Hello,

I am having trouble getting passed the check and actually running BlueSky. The error i get is 
OSError: could not find or load spatialindex_c-32.dl, specifically: 

![error](https://user-images.githubusercontent.com/44361789/144865051-601ff050-5fda-4157-ab29-dbaf354dbe1e.png)

I downgraded python to 3.6.4 and I have tracked the problem down to rtree, however i really do not know how to fix it. My OS is Windows. 
I have tried reinstalling rtree, no luck. I have also treid to downgrade it but it has not worked.

Any help would be appreciated.

**Comment by jooste** [comment]
Hi, how did you install python? From python.org, using Anaconda, or something else?

**Comment by borisdjartov** [comment]
Hey jooste, thank you for the quick resonse. I installed python by downloading an .exe file from python.org

**Comment by borisdjartov** [comment]
Update,
I managed to resolve the issue. I installed the package from the cmd terminal insted of the one from VScode and it did the trick. However i am faced now with my original problem. I thought downgrading my python should have solved this error.


![error 2](https://user-images.githubusercontent.com/44361789/144868521-3398f62b-a8b5-4b48-b2b0-82084592093a.PNG)

**Comment by borisdjartov** [comment]
Hi Jooste,

So when i run the check now i do not seem to get any issues:

![proof](https://user-images.githubusercontent.com/44361789/144869995-25b41699-352f-4a6b-bd29-21290e6e59a4.PNG)

However, there is still an issue. When i run BlueSky.py the previos image is the main screen along with:

![main](https://user-images.githubusercontent.com/44361789/144870320-2c67680f-deeb-4f80-83f9-80a8c2e92681.PNG)

I am kinda stuck and dont really know what to do i really want to use the visualisation capabilities

**Comment by jooste** [comment]
Ah, there is actually an error in the terminal output in your screenshot (can't open file ...). You are getting this error because you aren't running bluesky from it's main folder, but from one folder up. Because of this bluesky can't find it's own main python file, and might also have issues with other files. Try starting it from `d:\BlueSky\bluesky` and see if that fixes it!
