### ISSUE TITLE
Aircraft stay in turn mode if LNAV is set to OFF during a turn

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#351]
If LNAV is turned off for aircraft while in a turn, the aircraft stays in turn mode and is not responsive to any commands. An LNAV ON check should be added to the autopilot turn mode.

**Comment by ProfHoekstra** [comment]
Indeed! Thanks, I”ll add the fix and check some other spots for the switching of the LNAV/VNAV as well.

Best regards,
       Jacco Hoekstra

On 17 Dec 2021, at 09:28, andubadea ***@***.***> wrote:

﻿

If LNAV is turned off for aircraft while in a turn, the aircraft stays in turn mode and is not responsive to any commands. An LNAV ON check should be added to the autopilot turn mode.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TUDelft-2DCNS-2DATM_bluesky_issues_351&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=BwNITyXv7x8Cc3CuhMy86QqjRThCNh81X1nE-U96Aww&s=1w-KuQhsqk96u9DrDrV7TNvOEpmbF5pG4Onjbmf6fOs&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABWT2BHQUYKU334GJGMRI7LURLYDNANCNFSM5KIIKY7A&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=BwNITyXv7x8Cc3CuhMy86QqjRThCNh81X1nE-U96Aww&s=VvJkdx-UTOAka-Qu3iFiMi_FQ6qLDlRoREKKeH0zC38&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=BwNITyXv7x8Cc3CuhMy86QqjRThCNh81X1nE-U96Aww&s=wNNjqX6b5urfuiop6v9GN6dCC2B2XmrWKL7GcuinIvg&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=BwNITyXv7x8Cc3CuhMy86QqjRThCNh81X1nE-U96Aww&s=9nEtx2Ie6VxAC5wCqAH7cTnCRjDJeG_4w17PJJz-qhQ&e=>.

**Comment by ProfHoekstra** [comment]
Was a misplaced bracket. Will add coms extra checks.
