### ISSUE TITLE
Problem starting BlueSky on new MacBook

### ISSUE THREAD

**Issue by yaofuzhou** [TUDelft-CNS-ATM/bluesky#352]
Hello,
I am having problem starting/running BlueSky on my new MacBook (M1 Max). Thank you for taking your time reading this.

To begin with,

MacOS Monterey Version 12.1

>  » which python3
> /opt/anaconda3/bin/python3
>
>  » python3 --version
> Python 3.9.7

Here I am posting the printout from `check.py`:

~/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky(master) » python check.py
This script checks the availability of the libraries required by BlueSky, and the capabilities of your system.

> Checking for numpy               [OK]
> Checking for scipy               [OK]
> Checking for matplotlib          [OK]
> Checking for pyqt                [QT 5.15.2]
> Checking for pyopengl            [OK]
> OpenGL module version is         [3.1.5]
> Checking GL capabilities         [OK]
> GL Version at least 3.3          [OK]
> Supported GL version             [4.1]
> Checking for pyopengl-accelerate [OK]
> Checking for pygame              pygame 2.1.0 (SDL 2.0.16, Python 3.9.7)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [OK]
> 
> You have all the required libraries to run BlueSky. You can use both the QTGL and the pygame versions.
> Checking bluesky modules
> Using Python-based geo functions
> Reading config from settings.cfg
> Reading magnetic variation data
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
> Loading palette bluesky-default
> Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
> Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
> Using Qt 5.15.2 for windows and widgets
> Attempt to reimplement HELP from <function showhelp at 0x7fc3b81a2f70> to <function showhelp at 0x7fc40b5a9310>
> Failed to load BADA performance model
> Successfully loaded all BlueSky modules. Start BlueSky by running BlueSky.py.
> (base) ------------------

Here are the symptoms starting/running `BlueSky.py`:

The program did start with GUI, but froze soon after which may be reflected in the printout:

> ~/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky(master) » python3 BlueSky.py
> Using Python-based geo functions
> Reading config from settings.cfg
> Reading magnetic variation data
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
>    *****   BlueSky Open ATM simulator *****
> Distributed under GNU General Public License v3
> Accepting event connections on port 11000, and stream connections on port 11001
> Discovery is disabled
> Loading palette bluesky-default
> Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
> Using Qt 5.15.2 for windows and widgets
> Using Python-based geo functions
> Reading config from settings.cfg
> Reading magnetic variation data
> Loading global navigation database...
> Reading cache: data/cache/py3/navdata.p
> Failed to load BADA performance model
> Successfully loaded plugin AREA
> Successfully loaded plugin DATAFEED
> Reading cache: data/cache/py3/coastlines.p
> Maximum supported texture size: 16384
> Loading texture data/graphics/world.16384x8192.dds
> Reading cache: data/cache/py3/aptsurface.p
> Client b'\x00\xc1"\xcet' connected to host b'\x00$i\xf4\x9e'
> Traceback (most recent call last):
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/network/client.py", line 136, in update
>     self.receive()
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/network/client.py", line 178, in receive
>     self.stream(strmname, pydata, sender_id)
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/guiclient.py", line 48, in stream
>     actdata = self.get_nodedata(sender_id)
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/guiclient.py", line 119, in get_nodedata
>     self.send_event(b'GETSIMSTATE', target=nodeid)
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/network/client.py", line 232, in send_event
>     self.event_io.send_multipart(self._getroute(target) + [target, name, pydata])
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
> 

Although I do not intend to use `BlueSky_pygame.py`, I am posting its printout in case it helps (no need to read if unnecessary):

> ~/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky(master) » python3 BlueSky_pygame.py 
> pygame 2.1.0 (SDL 2.0.16, Python 3.9.7)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> Using Python-based geo functions
> Loading palette bluesky-default
> Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
> Traceback (most recent call last):
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/BlueSky_pygame.py", line 6, in <module>
>     from bluesky.ui.pygame import splash
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/__init__.py", line 2, in <module>
>     from bluesky.ui.qtgl.glhelpers import (gl, RenderObject, RenderTarget, RenderWidget,
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/__init__.py", line 2, in <module>
>     from bluesky.ui.qtgl.gui import start
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/gui.py", line 9, in <module>
>     from bluesky.ui.qtgl.mainwindow import MainWindow, Splash, DiscoveryDialog
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/mainwindow.py", line 21, in <module>
>     from bluesky.ui.qtgl.radarwidget import RadarWidget
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/radarwidget.py", line 15, in <module>
>     from .glmap import Map
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/qtgl/glmap.py", line 7, in <module>
>     from bluesky.ui.loadvisuals import load_coastlines
>   File "/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/loadvisuals.py", line 6, in <module>
>     from bluesky.ui.loadvisuals_txt import load_coastline_txt, load_aptsurface_txt
> ImportError: cannot import name 'load_aptsurface_txt' from 'bluesky.ui.loadvisuals_txt' (/Users/yaofuzhou/Dropbox/Mac (2)/Documents/Advanced_Air_Mobility/TUDelft-CNS-ATM/bluesky/bluesky/ui/loadvisuals_txt.py)
> (base) -----------------

Although I doubt it is related, in case you wonder about the path to my `BlueSky`, the appearance of `/Dropbox/Mac (2)/` is due to me backing up my system on Dropbox, but I do not know why my terminal would often refer to the backup path rather than the original one...

**Comment by jooste** [comment]
Hi! The TypeError you are getting is caused by a stale Bluesky process that is still running in the background. Use the activity monitor to kill it, or reboot and it will also be gone.

**Comment by yaofuzhou** [comment]
> Hi! The TypeError you are getting is caused by a stale Bluesky process that is still running in the background. Use the activity monitor to kill it, or reboot and it will also be gone.

Thank you for attending to this but it does not seem to be where the issue originates. In the meantime I will try to work with an older Python environment.
