### ISSUE TITLE
Suggestion: Make Reached available as a class variable in Autopilot.

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#353]
In update_fms in the AutoPilot, Bluesky checks if aircraft have reached a waypoint:

```
for i in bs.traf.actwp.Reached(qdr, dist, bs.traf.actwp.flyby, bs.traf.actwp.flyturn,bs.traf.actwp.turnrad,bs.traf.actwp.swlastwp):
```

However, due to the way the for loop is made, the  output of the reached function is not stored anywhere and thus not available. We have an instance in which we need the output of this function (to know when aircraft reached their next waypoint), so it would be great if the output of Reached would be stored in a class variable and thus made available to plugins:

```
self.reached = bs.traf.actwp.Reached(qdr, dist, bs.traf.actwp.flyby, bs.traf.actwp.flyturn,bs.traf.actwp.turnrad,bs.traf.actwp.swlastwp)
for i in self.reached:
```

Thank you!

**Comment by ProfHoekstra** [comment]
Done, thanks!
