### ISSUE TITLE
Segmentation Fault when installing on Windows

### ISSUE THREAD

**Issue by risufaj** [TUDelft-CNS-ATM/bluesky#357]
Hello,

I've been using Bluesky for a while now, but I was trying to install it on a new Windows machine. There is a pygame_parachute segmentation fault (see screenshot) that happens consistently over different python versions: 3.6, 3.7, 3.8, 3.9. According to setup-python.errors.then.readme.txt pyopengl_accelerate doesn't work for 3.7 so for attempts with python >=3.7 I only installed pyopengl (however the file seems old so I'm not sure if the issue still remains). 

<img width="552" alt="error" src="https://user-images.githubusercontent.com/24636674/149762981-e63ed892-7e46-4e39-80c4-775be4fe5cd6.PNG">

I am running Windows 10, and creating new virtual environments through anaconda to test the issue. The neccesary packages have been installed by running setup-python.bat and running check.py returns the following screenshot
<img width="928" alt="check" src="https://user-images.githubusercontent.com/24636674/149763082-0f6f00d2-4e16-4ae0-b3d0-2b1775ec1c10.PNG">

Lastly, I am also unable to open it through running Bluesky_pygame.py, but the error there seems to me unrelated to what I've reported previously:
<img width="913" alt="pygame" src="https://user-images.githubusercontent.com/24636674/149763496-20aeb3e8-a413-4b01-a49a-a4225f83e643.PNG">

Any clue on how to fix these issue would be appreciated.
Cheers,
Ralvi

**Comment by jooste** [comment]
Hi @risufaj,

pyopengl is indeed still required, pyopengl_accelerate not. The segmentation fault is difficult to debug without more information on where it occurs, the terminal output you show doesn't really tell anything.

The issue starting the pygame version however was more clear. I've made some fixes here: d1e9c4b. These should allow you to start the pygame version again.

**Comment by risufaj** [comment]
Hi @jooste

thanks for the reply. the pygame version seems fine now, thanks.

I was trying to run again the other version but now error is different, which is really strange as I did no changes:
<img width="609" alt="error2" src="https://user-images.githubusercontent.com/24636674/149788118-21a6ee21-2360-4d7c-af11-46e6986ddf62.PNG">

**Comment by jooste** [comment]
This error typically occurs when there is a stale bluesky process still running in the background. You can check this with the Windows Task Manager. If bluesky processes are listed even though you don't have bluesky running you should terminate them, which should resolve the error you show.

**Comment by risufaj** [comment]
Well it seems that terminating stale python/bluesky processes seemed to have solved both issues :). 
But just to confirm, I replicated the first error on another machine with a fresh installation of bluesky. From my observation, the segmentation fault happens after running bluesky for the first time after the packages are installed. If you close your cmd/anaconda prompt or whatever and terminate python processes and re-run then it works. 

In any case, I'm closing issue.
