### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'glGetActiveUniformBlockName'

### ISSUE THREAD

**Issue by bkzfyx** [TUDelft-CNS-ATM/bluesky#362]
Hello, I try to run BlueSky.py in virtual machine, the environment is Ubuntu20.04 with python3.8.10, but this error happened and the picture keep stopping this. But I can run the BlueSky_pygame.py. I wonder if it is caused by wrong qt version
![de9fec368b319200986d06a9e36f983](https://user-images.githubusercontent.com/52231924/150461786-fb4b0f9b-8ec5-4129-b73c-2fc574a2003b.png)
?

**Comment by jooste** [comment]
Hi @bkzfyx,

My guess is that this is related to trying to run bluesky in a virtual machine. A quick google gives the following suggestion (for virtualbox):

1. Install VirtualBox Guest Additions
2. Check Enable 3D Acceleration

Hope it helps!
