### ISSUE TITLE
Unable to load plugins (1392545)

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#367]
When trying to load any plugin Bluesky is unable always returning a message e.g. `BlueSky plugin system failed to load DATAFEED : No module named 'plugins\\adsbfeed'`. Currently running Python 3.6

**Comment by Ellislee1** [comment]
Found what was causing the error for me. In the most recent push the `importlib` lib class doesn't work as before meaning that the modules cannot be found in the plugin folder.
Reverting back to the previous code has resolved the issue for me (using `imp`)

**Comment by jooste** [comment]
Hi @Ellislee1!

Thanks for mentioning this, again it shows that cross-platform compatibility is always difficult :) The bug should be fixed in 786738d.
