### ISSUE TITLE
Question: simulate 100 different scenario files concurrently in their own environment

### ISSUE THREAD

**Issue by andersmh** [TUDelft-CNS-ATM/bluesky#369]
As I have been unable to find a solution to this, I wondered if it is possible to run 100 different scenario files in separate environments as each of the scenario files can't interfere with each other, they also need individual logging. Is this something which would be possible to do? If it is not possible to do this concurrently, would it be possible to run the scenarios in a new environment one by one automatically?

**Comment by ProfHoekstra** [comment]
There are many different ways to do this. Check out the BATCH command. 
It is also possible to start a new scenario at a time to end a scenario using the IC command with the name  to sequentially run them. You could also use PCALL but this does not reset the simulation as IC does.

**Comment by andersmh** [comment]
Hmmm, I have been unsuccessful to get it working with the BATCH command, however, I do think sequentially calling the IC command at the end of each scenario file should be sufficient enough to automatically run large numbers og simulations in my case! Thank you for the help professor Hoekstra!

**Comment by jooste** [comment]
To use batch mode you need to create a batch scenario that calls each individual scenario you want to run. Have a look at the example batch file in `scenario/testscenarios/batch_test.scn` for the appropriate format of a batch file.

**Comment by jooste** [comment]
The nice thing about batch mode, compared to successive IC calls, is that it allows bluesky to run as many scenarios in parallel as your computer has CPU cores.

**Comment by jooste** [comment]
No, they are put into a central scheduler, that assigns individual scenarios to separate simulation nodes (so separate environments as you call them). When a node is done with one scenario it will get the next one in the central schedule.
