### ISSUE TITLE
Issue with starting app

### ISSUE THREAD

**Issue by dzuchowska** [TUDelft-CNS-ATM/bluesky#375]
Hello,

The problem is similar to the issue #301 
I installed the BlueSky according to the Instalation Tutorial.
I am trying to run BlueSky in Windows 10. The app does start with the main window with aircraft and that's it. Nothing else happens, the GUI does not appear.

Python version is 3.6.7

 I get the following error while running it:

Using Python-based geo functions
Reading config from settings.cfg
Reading magnetic variation data
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Accepting event connections on port 11000, and stream connections on port 11001
Discovery is disabled
Loading palette bluesky-default
Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
Using Python-based geo functions
Reading config from settings.cfg
Reading magnetic variation data
pygame 2.1.2 (SDL 2.0.18, Python 3.6.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Warning: RTree could not be loaded. areafilter get_intersecting and get_knearest won't work
Using Qt 5.15.2 for windows and widgets
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
Warning: RTree could not be loaded. areafilter get_intersecting and get_knearest won't work
Traceback (most recent call last):
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 131, in initializeGL
    super().initializeGL()
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 720, in initializeGL
    self._shaderset.create()
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 46, in create
    'radarwidget-color.frag')
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 322, in load_shader
    if newshader.create(vs, fs, gs):
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 430, in create
    name = gl.glGetActiveUniformBlockName(self.programId(), ub)
  File "C:\Users\fd\Desktop\bluesky-master\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 118, in p_getuboname
    c_getuboname(programid, uboid, 20, None, ctypes.pointer(name))
ValueError: Procedure called with not enough arguments (20 bytes missing) or wrong calling convention
Failed to load BADA performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED

Please, advise.

Kind regards
Daria Żuchowska

**Comment by jooste** [comment]
Hi @dzuchowska!

Thanks for pointing this out, because it made me realise that the installation instructions on the wiki were a bit out of date. I'm not sure if this is also the cause of your error though, it is a strange one! How did you install python? With a bundle like anaconda, or straight from Python.org? Unfortunately the wiki recommended you to install python 3.6, which has actually recently been deprecated. Sorry for the confusion! I would recommend installing either version 3.9 or 3.10 from python.org, and to install the required packages using pip. I've just updated the installation instructions on the wiki, hopefully they are now correct!

**Comment by dzuchowska** [comment]
Thank you for the prompt answer!

I installed the new version of the Python and it works now. 

Could you tell me please, if the window (see below) is the one that I should see when run the BlueSky.py? I am not sure if it is the same version (Qt-OpenGL) as described in BlueSky Paper (Figure 8). Why the tab Analysis is not available?

![image](https://user-images.githubusercontent.com/100065312/154936126-ad22bbc9-791b-498f-beeb-f273996108fb.png)

Regards,
Daria

**Comment by jooste** [comment]
Hi Daria,

Yes, that is the way BlueSky should look when you first run it. The screenshot in the paper is from a long time back. You can of course perform many kinds of analysis with bluesky, but this didn't end up in a menu because they are all modular through the plugin structure of bluesky.
