### ISSUE TITLE
Import issues using BlueSky as Python Package

### ISSUE THREAD

**Issue by slee-aurora** [TUDelft-CNS-ATM/bluesky#391]
Hello,

We've been trying to use BlueSky as a Python package from source (i.e. cloning the git and pip installing with the setup.py file in the root folder), so that we can import and utilize the BlueSky modules in our external code.

However, we keep running into import and pathing issues when using the modules. For example, if we run:
`bluesky.init(mode="sim-detached",cfgfile=self.cfg_file)`
The simulator fails to initializes and throws errors like:
`File "/usr/local/lib/python3.9/dist-packages/bluesky/core/trafficarrays.py", line 78, in _init_trafarrays
    if TrafficArrays.root.ntraf:
AttributeError: 'NoneType' object has no attribute 'ntraf'`
or
`  File "/usr/local/lib/python3.9/dist-packages/bluesky/stack/basecmds.py", line 56, in initbasecmds
    bs.net.addnodes,
AttributeError: 'NoneType' object has no attribute 'addnodes'`

Any thoughts on why this may be happening and possible fixes?

Also, the pip installation seems to install additional data files (e.g. the data and plugins folders), but we wanted to use our own folders for certain settings in settings.cfg, like the scenario_path or plugin_path. Is this supported? We've tried changing some of these folders and it seems to cause some pathing issues at times.

As background information, we are using BlueSky for reinforcement learning and are using the OpenAI gym format with Python 3.9 on Ubuntu 20. Let me know if you need more information.

Thanks!

**Comment by jooste** [comment]
Hi @slee-aurora,

The arguments to `bluesky.init()` were recently updated to simplify the initialisation logic. Unfortunately we didn't immediately update the examples and documentation on the wiki as well. Thanks to your issue this is now fixed :)

The way to initialise a detached simulation is now:
```python
    import bluesky as bs
    bs.init(mode='sim', detached=True)
```
Apologies for the confusion!

**Comment by jooste** [comment]
Oh, and as of now BlueSky is also kept up to date on PyPI! You can install BlueSky with pip as:
```
    pip install bluesky-simulator[full]
```
To install bluesky with all dependencies (also gui). When the gui is not needed you can also install without `[full]`.

**Comment by slee-aurora** [comment]
That fixed our issue, thanks for the help!
