### ISSUE TITLE
RL: controlling multiple simulation instances

### ISSUE THREAD

**Issue by echen-aurora** [TUDelft-CNS-ATM/bluesky#392]
Hi all,

I'm working on an updated gym wrapper for bluesky, in order to use the simulator in RL experiments. So far I'm able to import from python and step through a single simulation by sending stack commands, but I'm wondering if you have any examples of how we might setup and step through multiple simulation instances in parallel? This is all without the GUI, as I only need to send actions to an aircraft and retrieve state information.

I've seen the docs for ADDNODES, which seems to be implementing what I want - the ability to launch separate simulation instances. What would be the best way to connect to these additional simulation environments and send them stack commands individually from a python script? Do I need to initialize separate Client() instances with different ports for each simulation instance I want to access? Ideally we'd like to follow the gym paradigm and just have each gym environment represent a single class instance with access to it's own bluesky simulation node.

Any help is greatly appreciated, and thanks for all your work on this project! Do let me know if I can provide more information or clarify anything.

**Comment by jooste** [comment]
Hi @echen-aurora, you can in principle do this with only one Client. You can switch between nodes with `Client.actnode()` and then use the regular `stack.stack()`, or directly send stack commands to individual nodes using `Client.send_event(b'STACK', cmd, target=...)`.
