### ISSUE TITLE
Vertical takeoff and landing of drones

### ISSUE THREAD

**Issue by ChengHuang-CH** [TUDelft-CNS-ATM/bluesky#422]
Hi, I am looking for the function for UAV's vertical takeoff and landing.  But after investigating the source code, from https://github.com/TUDelft-CNS-ATM/bluesky/blob/5eab3752386a6549583704caa8dbace7e1b31954/bluesky/traffic/performance/openap/phase.py#L71 and https://github.com/TUDelft-CNS-ATM/bluesky/blob/5eab3752386a6549583704caa8dbace7e1b31954/bluesky/traffic/performance/openap/perfoap.py#L251  

it seems that the vertical takeoff and landing ability is not implemented, right?  If it is not implemented, how can I get similar operations?   

FYI, I would like to generate [this flight profile](https://www.researchgate.net/figure/TOL-flight-profile-The-five-phases-of-VTOL-travel-are-takeoff-hover-climb-cruise_fig1_332306106 ) .

Looking forward to your reply. Thanks!

**Comment by jooste** [comment]
Dear @ChengHuang-CH,

Sorry for not replying to this earlier. This functionality should already be implemented. If I for instance do the following:
```
CRE TEST M600 52 4 0 0 0
TEST ALT 100
```
I get a Matrice 600 drone that starts at altitude 0 with speed 0, and vertically climbs to 100 ft, where it then hovers at horizontal speed 0.
