### ISSUE TITLE
ALT Command

### ISSUE THREAD

**Issue by kliu14146** [TUDelft-CNS-ATM/bluesky#428]
Hi all,

I'm trying to implement a simulator that takes action commands to control a plane at each timestep. So far, I have been creating aircraft using "CRE", and simulating them in 2d using "MOVE" and changing the "hdg" and "spd" fields based on some action input that increments these values. I'd like to extend this environment to the 3d case and control altitude at each timestep in a similar way. 

I've tried using "ALT" and specifying "alt" and "vspd", but I get a strange behavior when doing so. For example, if I specify only positive "vspd", and set "alt" to equal current altitude + ("vspd"/60)xDT where DT is the timestep increment in seconds the plane will only descend until it hits the ground. Am I misinterpreting the "ALT" or "MOVE" commands? Do I need to instantiate VNAV or some form of autopilot before being able to control altitude? Is there an area of the codebase where vertical climb dynamics are processed that I should take a look at?

Any help is greatly appreciated! Thank you for your work on this great tool -

**Comment by ProfHoekstra** [comment]
Thanks, we will check what happens in this specific case of using the current altitude as selected altitude. It should go to ALT HOLD.

In general: Vertical speed only works with an altitude command for a different altitude than the current altitude. It is an extra specification of the ALT command. This also means you can not use the V/S without a target altitude.

Does this answer help already?

Best regards,
    Jacco Hoekstra


On 29 Sep 2022, at 00:58, kliu14146 ***@***.***> wrote:

﻿

Hi all,

I'm trying to implement a simulator that takes action commands to control a plane at each timestep. So far, I have been creating aircraft using "CRE", and simulating them in 2d using "MOVE" and changing the "hdg" and "spd" fields based on some action input that increments these values. I'd like to extend this environment to the 3d case and control altitude at each timestep in a similar way.

I've tried using "ALT" and specifying "alt" and "vspd", but I get a strange behavior when doing so. For example, if I specify only positive "vspd", and set "alt" to equal current altitude + ("vspd"/60)xDT where DT is the timestep increment in seconds the plane will only descend until it hits the ground. Am I misinterpreting the "ALT" or "MOVE" commands? Do I need to instantiate VNAV or some form of autopilot before being able to control altitude? Is there an area of the codebase where vertical climb dynamics are processed that I should take a look at?

Any help is greatly appreciated! Thank you for your work on this great tool -

**Comment by kliu14146** [comment]
I see ok - thanks for the quick answer. I have been using a different target altitude than the current altitude, with a positive climb rate. Should this still be producing a rapid altitude loss? The plane speed is set to a reasonably high value.

Thanks for your help -

**Comment by ProfHoekstra** [comment]
No, that does not sound good. Can you given me the exact scenario file or commands you use? Then I can see what is going on.

**Comment by jooste** [comment]
I assume that this issue is resolved? Closing it because it's been inactive for almost a year :)
