### ISSUE TITLE
Climb profiles for newly generated aircraft

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#429]
Is there a reason that newly generated aircraft will always take a more extreme climb to reach the first waypoint when compared to existing aircraft on the same route?

In the image AC1 is following a route of 2 waypoints. 25 seconds after reaching the first waypoint AC2 is added with the same parameters as AC1 and the same next waypoint. AC2 takes an aggressive climb reaches the next wpt alt 2 minutes before arriving while AC1 climbs for the entire distance.

![ac alt issue](https://user-images.githubusercontent.com/29206618/193643087-d1276adf-d519-4057-a6ac-347a70f534bf.png)

Here is the MRC for testing that I used:
```python
import bluesky as bs
from bluesky.simulation import ScreenIO
import matplotlib.pyplot as plt
import numpy as np

from tqdm import trange


class ScreenDummy(ScreenIO):
    """
    Dummy class for the screen. Inherits from ScreenIO to make sure all the
    necessary methods are there. This class is there to reimplement the echo
    method so that console messages are printed.
    """

    def __init__(self, verbose=False):
        """Initilising the dummy screen

        Args:
            verbose (bool, optional): If BlueSky messages should be displayed. Defaults to False.
        """

        super().__init__()
        self.verbose = verbose

    def echo(self, text="", flags=0):
        """Just print echo messages"""

        if self.verbose:
            print("BlueSky console:", text)


route = [[52.093472, -0.560397, 1000, 50], [52.067749, -0.545041, 1750, 60]]

start = [52.07, -0.619361, 10, 20, 15]

bs.init(mode="sim", detached=True)
bs.scr = ScreenDummy()

ac = {}

bs.traf.cre(
    acid="AC1",
    actype="AMZN",
    aclat=start[0],
    aclon=start[1],
    achdg=start[3],
    acalt=start[2],
    acspd=start[4],
)


for wpt in route:
    bs.stack.stack(f"ADDWPT AC1 {wpt[0]} {wpt[1]} {wpt[2]}")
bs.stack.stack("LNAV AC1 ON; VNAV AC1 ON")

bs.stack.stack("DT 1; FF")

c = 0

for i in trange(700):
    bs.sim.step()

    for i in range(bs.traf.ntraf):
        if bs.traf.id[i] not in ac:
            ac[bs.traf.id[i]] = [
                [
                    bs.sim.simt,
                    bs.traf.lat[i],
                    bs.traf.lon[i],
                    bs.traf.alt[i],
                    bs.traf.hdg[i],
                    bs.traf.tas[i],
                ]
            ]

        else:
            ac[bs.traf.id[i]].append(
                [
                    bs.sim.simt,
                    bs.traf.lat[i],
                    bs.traf.lon[i],
                    bs.traf.alt[i],
                    bs.traf.hdg[i],
                    bs.traf.tas[i],
                ]
            )

    if bs.traf.ap.route[0].iactwp == 1:
        c += 1

    if c == 25:
        bs.traf.cre(
            acid="AC2",
            actype="AMZN",
            aclat=bs.traf.lat[0],
            aclon=bs.traf.lon[0],
            achdg=bs.traf.hdg[0],
            acalt=bs.traf.alt[0],
            acspd=bs.traf.tas[0],
        )

        wpt = route[1]
        bs.stack.stack(f"ADDWPT AC2 {wpt[0]} {wpt[1]} {wpt[2]}")
        bs.stack.stack("LNAV AC2 ON; VNAV AC2 ON")


print(ac.keys())

plt.plot(np.array(ac["AC1"])[:, 0], np.array(ac["AC1"])[:, 3], label="AC1")
plt.plot(np.array(ac["AC2"])[:, 0], np.array(ac["AC2"])[:, 3], label="AC2")

plt.legend()

plt.show()
```

**Comment by ProfHoekstra** [comment]
Dear Ellis,

Thanks for including the code, we’ll have a look at what is happening here.

Best regards,
    Jacco Hoekstra


On 3 Oct 2022, at 19:41, Ellis Thompson ***@***.***> wrote:

﻿

Is there a reason that newly generated aircraft will always take a more extreme climb to reach the first waypoint when compared to existing aircraft on the same route?

In the image AC1 is following a route of 2 waypoints. 25 seconds after reaching the first waypoint AC2 is added with the same parameters as AC1 and the same next waypoint. AC2 takes an aggressive climb reaches the next wpt alt 2 minutes before arriving while AC1 climbs for the entire distance.

[ac alt issue]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/29206618/193643087-d1276adf-d519-4057-a6ac-347a70f534bf.png__;!!PAKc-5URQlI!-SqAwB5KNFmsmP8tK196CQoI9rrr3bb81MBIVuAe2NGXEiQxLhgBYQ_DhyWDWEt6WbNXiaAsiB4G0Ic8KqJYq0hR1iuzIw$>

Here is the MRC for testing that I used:

import bluesky as bs
from bluesky.simulation import ScreenIO
import matplotlib.pyplot as plt
import numpy as np

from tqdm import trange


class ScreenDummy(ScreenIO):
    """
    Dummy class for the screen. Inherits from ScreenIO to make sure all the
    necessary methods are there. This class is there to reimplement the echo
    method so that console messages are printed.
    """

    def __init__(self, verbose=False):
        """Initilising the dummy screen

        Args:
            verbose (bool, optional): If BlueSky messages should be displayed. Defaults to False.
        """

        super().__init__()
        self.verbose = verbose

    def echo(self, text="", flags=0):
        """Just print echo messages"""

        if self.verbose:
            print("BlueSky console:", text)


route = [[52.093472, -0.560397, 1000, 50], [52.067749, -0.545041, 1750, 60]]

start = [52.07, -0.619361, 10, 20, 15]

bs.init(mode="sim", detached=True)
bs.scr = ScreenDummy()

ac = {}

bs.traf.cre(
    acid="AC1",
    actype="AMZN",
    aclat=start[0],
    aclon=start[1],
    achdg=start[3],
    acalt=start[2],
    acspd=start[4],
)


for wpt in route:
    bs.stack.stack(f"ADDWPT AC1 {wpt[0]} {wpt[1]} {wpt[2]}")
bs.stack.stack("LNAV AC1 ON; VNAV AC1 ON")

bs.stack.stack("DT 1; FF")

c = 0

for i in trange(700):
    bs.sim.step()

    for i in range(bs.traf.ntraf):
        if bs.traf.id[i] not in ac:
            ac[bs.traf.id[i]] = [
                [
                    bs.sim.simt,
                    bs.traf.lat[i],
                    bs.traf.lon[i],
                    bs.traf.alt[i],
                    bs.traf.hdg[i],
                    bs.traf.tas[i],
                ]
            ]

        else:
            ac[bs.traf.id[i]].append(
                [
                    bs.sim.simt,
                    bs.traf.lat[i],
                    bs.traf.lon[i],
                    bs.traf.alt[i],
                    bs.traf.hdg[i],
                    bs.traf.tas[i],
                ]
            )

    if bs.traf.ap.route[0].iactwp == 1:
        c += 1

    if c == 25:
        bs.traf.cre(
            acid="AC2",
            actype="AMZN",
            aclat=bs.traf.lat[0],
            aclon=bs.traf.lon[0],
            achdg=bs.traf.hdg[0],
            acalt=bs.traf.alt[0],
            acspd=bs.traf.tas[0],
        )

        wpt = route[1]
        bs.stack.stack(f"ADDWPT AC2 {wpt[0]} {wpt[1]} {wpt[2]}")
        bs.stack.stack("LNAV AC2 ON; VNAV AC2 ON")


print(ac.keys())

plt.plot(np.array(ac["AC1"])[:, 0], np.array(ac["AC1"])[:, 3], label="AC1")
plt.plot(np.array(ac["AC2"])[:, 0], np.array(ac["AC2"])[:, 3], label="AC2")

plt.legend()

plt.show()

**Comment by ProfHoekstra** [comment]
Dear Ellis,

There are two things at play: timing, setting a (too) large time step and a safety net of the autopilot. 

First of all, when I run the same scenario, but with smaller DT than the 1 second that you use, I get no difference between the two aircraft:

![image](https://user-images.githubusercontent.com/7159044/194102256-66c2ea56-8090-4117-aaaa-e08300248b3e.png)

What is happening is that you use a DT=1 sec, which is quite coarse when it comes to waypoint passing. The jump you see in V/S is a reaction to passing a waypoint and not making the altitude with the calculated V/S and therefore going to this altitude with the maximum V/S while turning to the next leg.

I suspect the difference occurs, because the waypoint switching does not happen at t=rounded to a second, but something later and it misses the waypoint switching and there switches later, resulting in emergency climb.

Could you try it with a smaller DT, say DT=0.1? Then we can see whether it disappears.

By the way, I used the following scenario file to test it, first used the AT HOLD command to find the time of the first WP passing, this was around 10:04, so I add the 2nd aircraft at 10:29. Also check out the (yet) undocumented PLOT command!

00:00:00.00>CRE AC1,AMZN,52.07, -0.619361, 10, 20, 15
00:00:00.00>PAN AC1;++++;pos ac1
00:00:00.00>ADDWPT AC1 52.093472, -0.560397, 1000, 50
00:00:00.00>ADDWPT AC1 52.067749, -0.545041, 1750, 60
# 00:00:00.00>AC1 AT AC1001 DO HOLD
00:00:00.00>PLOT sim.simt, traf.alt,1
00:00:00.00>LNAV AC1 ON; VNAV AC1 ON
00:10:29.00>CRE AC2,AMZN,52.07, -0.619361, 10, 20, 15
00:10:29.00>ADDWPT AC2 52.093472, -0.560397, 1000, 50
00:10:29.00>ADDWPT AC2 52.067749, -0.545041, 1750, 60
00:10:29.00>LNAV AC2 ON; VNAV AC2 ON

Best regards,
     Jacco Hoekstra

**Comment by Ellislee1** [comment]
Hi Jacco,
Many thanks for your input, increasing the fineness of the time step does appear to resolve the variation in climb profiles for my, somewhat poorly coded, example.

Many thanks!

- Ellis

![Fixed alt](https://user-images.githubusercontent.com/29206618/194116383-a34ca0bb-28f2-4e71-a164-8bac0efda584.png)
