### ISSUE TITLE
[Bug] Autopilot uses the incorrect value to calculate when to slow down for a turn

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#436]
In Autopilot.py, on line 381, the distance at which an aircraft needs to start slowing down in order to turn is calculated. However, it is currently calculated using the maximum velocity of the aircraft:

```python
dxturnspdchg = distaccel(turntas,bs.traf.perf.vmax, bs.traf.perf.axmax)
```

If the aircraft is not travelling close to its performance-based maximum velocity, then it starts slowing down too early. I think the calculation should use the actual speed of the aircraft.

```python
dxturnspdchg = distaccel(turntas,bs.traf.tas, bs.traf.perf.axmax)
```

**Comment by ProfHoekstra** [comment]
Fixed
