### ISSUE TITLE
Question about GUI in real-time simulation

### ISSUE THREAD

**Issue by Shulu-Chen** [TUDelft-CNS-ATM/bluesky#438]
Hello BlueSky team,

I designed a policy to control aircraft by calling BlueSky API and using the stack module to change their speed. Is it possible to connect it to the GUI and see the operations in real-time? 

Currently my solution is to write a `scn` file simultaneously and show the demo after the simulation. But it is better to see the aircraft in real-time so we can provide extra operations on top of our separation algorithm. 

Sincerely,
Shulu

**Comment by jooste** [comment]
Hi!

`bs.net.run()` starts and runs the (entire) main loop, so it will block the rest of your code. Try replacing it with `bs.net.update()`

**Comment by Shulu-Chen** [comment]
Yes that's working now, thanks a lot for your help!
