### ISSUE TITLE
Stack command not executed

### ISSUE THREAD

**Issue by leonardocfor** [TUDelft-CNS-ATM/bluesky#440]
Hi guys, 

I'm trying to use the example TextClient class in [here](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Connecting-external-applications-to-BlueSky), but without the GUI part, as shown bellow and simply nothing happens. No error whatsoever but when I execute the command pan kl001 I get the output "KL001 is not a valid pan direction ..." in the GUI. I'm using Python 3.8.15 within a Conda enviroment. 

```
from bluesky.network.client import Client
from PyQt6.QtCore import QTimer
import traceback

class TextClient(Client):
    """
    Subclassed Client with a timer to periodically check for incoming data,
    an overridden event function to handle data, and a stack function to
    send stack commands to BlueSky.
    """

    def __init__(self):
        super().__init__()
        self.timer = QTimer()
        self.timer.timeout.connect(self.update)
        self.timer.start(20)

    def event(self, name, data, sender_id):
        """Overridden event function to handle incoming ECHO commands."""
        if name == b"ECHO":
            pass

    def stack(self, text):
        """Stack function to send stack commands to BlueSky."""
        self.send_event(b"STACKCMD", text)

try:
    bs = TextClient()
    bs.connect(event_port=11000, stream_port=11001)
    bs.stack("cre kl001 b737 37.329873 -121.8158 0 900 10")
except Exception as exc:
    print("Error: {}".format(exc))
    traceback.print_exc()
```

However if I fully use the GUI version provided in [here](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Connecting-external-applications-to-BlueSky) (same as above), it works, I get the acid kl001 created. 

I have also used the approach in [here](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/stack) as follows: 

```
from bluesky import stack
stack.stack('cre kl001 b737 37.329873 -121.8158 0 900 10')
```

And again the command is not executed as I can't find the acid in the GUI. Moreover, I'm not familiar with the meaning of the phrase "This will be executed the next time the stack is updated." in the wiki page. How can I force the stack to be updated so the command is executed ?

Can you guys advice what might be happening? 

Thank you,

**Comment by jooste** [comment]
Hi @leonardocfor,

Both on the sim and the gui side, calling `stack()` only puts a command on the command stack. This command stack is processed every update cycle. On the sim side this is when `Simulation.update()` is called (with networking and RT timing) or `Simulation.step()` when you manage your own timing. On the gui side you need to call `Client.update()`.

**Comment by leonardocfor** [comment]
Hi @jooste,

Thank you for your quick reply. Your suggestion works and here is the code I used for future reference: 

```
from bluesky.network.client import Client
from bluesky import stack

cl = Client()
cl.connect(event_port=11000, stream_port=11001)
stack.stack("cre kl001 b737 37.329873 -121.8158 0 900 10")
cl.update()

```

Thanks again
