### ISSUE TITLE
No operation interface process finished with exit code 0 appears

### ISSUE THREAD

**Issue by gwt679** [TUDelft-CNS-ATM/bluesky#443]
Hello, dear ProfHoekstra, sorry to bother you. Instead of the Settings screen popping up when I opened BlueSky.py in Python, the following code appears Using Python-based geo functions
Reading config from
Reading magnetic variation data
Loading global navigation database...
Reading cache: C:\Users\23515\bluesky\cache\navdata.p
Bluesky needs zmq
Run setup-python.bat (Windows) or check requirements.txt (other systems)
Install using e.g. pip install zmq
BlueSky normal end.
Process finished with exit code 0
Please give me some advice. Thank you again

**Comment by jooste** [comment]
Hi @gwt679,

Looking at the output you've included in your post you are missing one (or more) required packages (it mentions `zmq`).

An easy way to install all the necessary requirements for bluesky, run the following command from the root bluesky folder:
```
pip install -r requirements.txt
```
If you are on mac or linux you can replace `requirements.txt` with `requirements-gui.txt`. On windows there are issues with PyQt6 (which is installed with the requirements-gui list), which means you need to select the pyqt5 packages yourself:
```
pip install PyQt5 PyQt5-WebEngine pygame pyopengl
```

**Comment by jooste** [comment]
> The first problem was: I copied the code on the Wiki and pasted it into command. Nothing valid can be done after that (the enter key is invalid). Can I only enter commands manually by myself?
What do you mean by this exactly? Which part of the wiki are you referring to, and what do you mean by 'the enter key is invalid'? You can manually enter commands, but you can also create and load timestamped scenario files.

> The second question is: when I use the command dtmult 10, speed: 6.4x is displayed. When I use the command dtmult 20, speed: 6.5x is displayed. May I ask what the reason is?
Fast-time running will only go as fast as your computer can cope with. If you are for instance running a simulation with many aircraft it can be that only a small multiple of real time is possible, or even only running slower than real time.

**Comment by gwt679** [comment]
> > The first problem was: I copied the code on the Wiki and pasted it into command. Nothing valid can be done after that (the enter key is invalid). Can I only enter commands manually by myself?
> 
> What do you mean by this exactly? Which part of the wiki are you referring to, and what do you mean by 'the enter key is invalid'? You can manually enter commands, but you can also create and load timestamped scenario files.
> 
> > The second question is: when I use the command dtmult 10, speed: 6.4x is displayed. When I use the command dtmult 20, speed: 6.5x is displayed. May I ask what the reason is?
> 
> Fast-time running will only go as fast as your computer can cope with. If you are for instance running a simulation with many aircraft it can be that only a small multiple of real time is possible, or even only running slower than real time.

 Hello, dear Professor jooste. I'm sorry to bother you again. After not exploring because I was sick, I recently found the following loading failures when running bluesky.py: Warning:
 RTree could not be loaded.  areafilter get_intersecting and get_knearest won't work
Using Qt 5.15.2 for windows and widgets
Warning: RTree could not be loaded.  areafilter get_intersecting and get_knearest won't work
Failed to load OpenAP performance model
Failed to load BADA performance model
Successfully loaded legacy performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Reading cache: D:\anaconda3\Lib2\cache\aptsurface.p
Qt gui warning:  An OpenGL Core Profile was requested,  but it is not supported on the current platform.  Falling back to a non-Core profile.  Note that this might cause  rendering issues.

I took a closer look at the tutorial, ran check.py and it showed the following result:
Checking for numpy               [OK]
Checking for scipy               [OK]
Checking for matplotlib          [OK]
Checking for pyqt [QT 6.4.0] Checking for PyQt [Qt 6.4.0]
Checking for pyopengl            [OK]
OpenGL module version is [3.1.6]
Checking GL capabilities
check.py:None (check.py)
. \vs3\Python39_64\Lib\importlib\__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
&lt; frozen importlib._bootstrap&gt; :1030: in _gcd_import
?????
&lt; frozen importlib._bootstrap&gt; :1007: in _find_and_load
?????
&lt; frozen importlib._bootstrap&gt; :986: in _find_and_load_unlocked
?????
&lt; frozen importlib._bootstrap&gt; :680: in _load_unlocked
?????
C:\Users\23515\AppData\Roaming\Python\Python39\site-packages\_pytest\assertion\rewrite.py:168: in exec_module
exec(co, module.__dict__)
D:\anaconda3\bluesky\Lib\check.py:73: in &lt; module&gt;
?????
E   AttributeError: type object 'QSurfaceFormat' has no attribute 'hasOpenGL'
collected 0 items / 1 error
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 1 error in 1.28 s = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
Process finished with exit code 2

I can't solve this problem by myself. Please help me. I would like to express my thanks again. Wish you a happy life.

**Comment by jooste** [comment]
Hi @gwt679,

The check.py error you can ignore, it uses a check that was removed in Qt6.

The RTree message at the start of bluesky indicates that you don't have RTree installed. By default it is not used in the simulation, so this also shouldn't be a problem for you. It is there for simulation setups with large numbers of polygons (urban environment simulations), and the plugins to use these data. In normal simulations, poly data is accessed through dicts, which works fine without rtree.

**Comment by gwt679** [comment]
> Hi @gwt679,
> 
> The check.py error you can ignore, it uses a check that was removed in Qt6.
> 
> The RTree message at the start of bluesky indicates that you don't have RTree installed. By default it is not used in the simulation, so this also shouldn't be a problem for you. It is there for simulation setups with large numbers of polygons (urban environment simulations), and the plugins to use these data. In normal simulations, poly data is accessed through dicts, which works fine without rtree.

Hello, dear Professor jooste. Thank you for taking time out of your busy schedule to reply me. Several problems occurred when I ran the Scenario files

① When running 0-vnav-TestScenario, it is found that kl204 reaches the destination with a height of 0 but not a speed of 0, and kl205 reaches the destination with both a height and a speed of 0. I have read the command carefully but cannot find the problem

② The following error occurs when running CIRCLE12. 
Unknown command or ai rcraft:lable
Unknown command: NAVTYPE
Unknown command: radardt
Un known command: navdt
Base dt set to 0.25
performance dt is unchanged.
asas dt is unchanged.
AREA dt is unchanged.
DATAFEED. update dt set to 0.25 to match integer multiple of base dt.
Unknown command: RECONACTRTE
This TMX command has not (yet) been implemented in BlueSky。
Un known command: DTREACT
Unknown command: TREACTNO
Un known command: DTREACTNO
Un known command: ADSB
Unknown command :ADSB
Unknown command :resonr
Setting default CD lookahead to 300.0 sec 
Unknown command :DTLOOKI NT
Un known command: FILTRED
Unknown command: FILTAMB
Setting default PZ radius to 5.0 NM
Horizontal resolution factor updated to 1.04， resulting in radius: 5.2 nm
Setting default PZ height to 900.0 ft
Vertical resolution factor updated to 1.111111111111112 , resulting in height: 1000.0 ft
Unknown command: DZONER
Un known command: DZONEDH
RMETHH CPA10
Syntax error: The current RMETHH implementation doesn't provide this function (function was originally declared in Command)
Horizontal resolution factor set to 1.0
RMETHV NONE
Syntax error: The current RMETHV implementation doesn' tprovide this function (function was originally declared in Command)
Vertical resolution factor set to 1.0
This TMX command has not (yet) been implemented in BlueSky .
Unknown command: dtcpred
Unknown command: dtcpambr
Unknown command: dtcpcyan
Unknown command: CRZALT
Unknown command: DELALT

I checked the command reference and found no explanation for the following command.
# Sim
 0:00:00.00>symbol;symbol;symbol
 0:00:00.00>label;label;label;label
 0:00:00.00>NAVTYPE 0
 0:00:00.00>radardt 0.0
 0:00:00.00>navdt 0.0
 0:00:00.00>rtf 1.0
 0:00:00.00>DT 0.25
 0:00:00.00>RECONACTRTE OFF
# Pilot Model
 0:00:00.00>TREACT  NORM 10;  TREACT FAST 5;  TREACT ULT 5
 0:00:00.00>DTREACT NORM  2; DTREACT FAST 1; DTREACT ULT 0
 0:00:00.00>TREACTNO 150
 0:00:00.00>DTREACTNO 30
# ADS-B settings
 0:00:00.00>ADSB DEF UPD MS OFF
 0:00:00.00>ADSB DEF UPD RF OFF
 0:00:00.00>ADSB DEF UPD TS OFF
 0:00:00.00>ADSB DEF UPD TR OFF
 0:00:00.00>ADSB DEF UPD TC OFF
# CD&R
 0:00:00.00>resonr 26
 0:00:00.00>DTLOOK 300
 0:00:00.00>DTLOOKINT 600
 0:00:00.00>FILTRED 2
 0:00:00.00>FILTAMB 4
 0:00:00.00>PRIORULES OFF
 0:00:00.00>ZONER 5.0; RSZONER 5.2
 0:00:00.00>zonedh 900; rszonedh 1000
 0:00:00.00>DZONER 0.1; DZONEDH 100.0
 0:00:00.00>RMETHH CPA10; RFACH 1.0
 0:00:00.00>RMETHV NONE;   RFACV 1.0
# PASAS
 0:00:00.00>SWNLRPASAS ON
 0:00:00.00>BGPASAS ON
 0:00:00.00>dtcpred   60.0
 0:00:00.00>dtcpambr  300.0
 0:00:00.00>dtcpcyan  300.0
# Misc
 0:00:00.00>CRZALT * 25000
 0:00:00.00>DELALT 10000
# Log
# 0:00:00.00>INTRLOG ON
# 0:00:00.00>TRAFLOG ON

I'd like to ask you a few more questions; ① Can the conflict criteria be changed in settings.cfg? (such as horizontal distance, vertical distance, etc.) Because different regional conflict definition is different ② detailed plane plan of the airport. I found that some airports have very detailed plans, some airports only have one runway. Can I get the detailed airport plan I need?③ How do I get the climb profile of the aircraft flight path.
Sorry to bother you again, please give me some advice in your spare time. Again, my respect to you.

**Comment by jooste** [comment]
Hi @gwt679,

1) I don't see a KL205 in the scenario file you mention? Aside from that, BlueSky currently doesn't have a dedicated ground model, which might explain the things you are seeing
2) Some scenario files come from bluesky's predecessor, TMX. Not all TMX commands are available in BlueSky.

1) you can set the protected zone margins per aircraft with the `ZONER` and `ZONEDH` commands within the simulation.
2) You mean the visualisation of airports in bluesky? These data are taken from X-plane. There is an editor for the file format X-plane uses, so you could create your own layouts for airports you want to have added.
3)what do you mean? If you want to visualise the (historical) altitude of an aircraft you can use the `PLOT` command (`PLOT alt`).

**Comment by ProfHoekstra** [comment]
By the way, taxiing should work nevertheless. But the performance is not very realistic, as the performance models do not have no ground model, friction etc is also not modelled.

Also note that some of the scenarios have been made with different performance models for the airborne part, which means the "open-loop" descents now have a different angle, resulting in a steep descent or landing short.

**Comment by gwt679** [comment]
hi @jooste 
Thank you again for your great help. I'm a beginner. My goal is to use blue sky to simulate standard departure procedures at a specific airport. I need flight data throughout the flight. I encountered the following problems. ① I want to show the flight profile. 'synatax error: variable plot not found' occurs when I use the 'plot plot alt' command. I have 'plot' in python. Why does this problem occur and how do I solve it? ② Can I import the online map in blue sky as the background map ③ Where can I retrieve the flight data (altitude, speed, heading, etc.) during the whole flight

Thank you for your help. Have a nice life.

**Comment by jooste** [comment]
For sake of completeness:

- The plot command is called as: `PLOT [state to plot]`, so e.g., `PLOT alt`
- You can use tiled maps from ao. OpenStreetMap using the TiledMap renderer in bluesky. Enable it with `VIS MAP TILEDMAP`
- You can create loggers that generate CSV log files using the `CRELOG` command:
- `CRELOG TESTLOGGER 1`
- `TESTLOGGER ADD lat, lon, alt, trk`
- In plugins you can access all state variables by importing the appropriate object (e.g., bluesky.traf)
