### ISSUE TITLE
Change aircraft color

### ISSUE THREAD

**Issue by Shulu-Chen** [TUDelft-CNS-ATM/bluesky#448]
Hello,

I want to highlight aircraft that involve loss of separation, is there some command I can use to change the aircraft color? Thanks!

**Comment by ProfHoekstra** [comment]
Yes, see command reference on Wiki. Command is Colour or Color. You can also type the command to get help,

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 3 Feb 2023, at 21:11, Rex Chen ***@***.***> wrote:

﻿

Hello,

I want to highlight aircraft that involve loss of separation, is there some command I can use to change the aircraft color? Thanks!

**Comment by Shulu-Chen** [comment]
Hi Prof. Hoekstra, `color` works here, thanks a lot! But it seems that this command is not in the command reference.

**Comment by ProfHoekstra** [comment]
Ok, thanks. We will fix that omission.

Best regards,
    Jacco Hoekstra


On 4 Feb 2023, at 23:51, Rex Chen ***@***.***> wrote:

﻿

Hi Prof. Hoekstra, color works here, thanks a lot! But it seems that this command is not in the command reference.
