### ISSUE TITLE
Labels not showing GUI

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#450]
Fresh install of bluesky (python package) and the Labels seem to be broken both for Airports/Waypoints and Aircraft. I have tried turning labels on and off to no luck.

Here is the output trace as well, I dont see any potential issues unless it has something to do with the `QT gui warning`?
```
C:\Users\Ellis>bluesky
Using Python-based geo functions
Reading config from C:\Users\Ellis\bluesky\settings.cfg
Reading magnetic variation data
Loading global navigation database...
Reading cache: C:\Users\Ellis\bluesky\cache\navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Accepting event connections on port 11000, and stream connections on port 11001
Discovery is disabled
Loading palette bluesky-greyscale
Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
Using Python-based geo functions
Reading config from C:\Users\Ellis\bluesky\settings.cfg
Reading magnetic variation data
Loading global navigation database...
Reading cache: C:\Users\Ellis\bluesky\cache\navdata.p
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
pygame 2.1.0 (SDL 2.0.16, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Using Qt 5.15.2 for windows and widgets
Successfully loaded OpenAP performance model
Failed to load BADA performance model
Successfully loaded legacy performance model
Reading cache: C:\Users\Ellis\bluesky\cache\aptsurface.p
Qt gui warning: An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
Reading cache: C:\Users\Ellis\bluesky\cache\console_history.p
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Reading cache: C:\Users\Ellis\bluesky\cache\coastlines.p
Maximum supported texture size: 16384
Loading texture C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\resources\graphics\world.16384x8192.dds
Client b'\x00\x0f\xa9\xaa\x1c' connected to host b'\x00\xed\x19KX'
```

![image](https://user-images.githubusercontent.com/29206618/217115651-fc401007-515d-4313-913d-4014e4fca300.png)

**Comment by jooste** [comment]
Hi @Ellislee1,

The Qt/OpenGL warning is a known harmless one. Could you provide a bit more information:
- It looks like you installed Python 3.10.x from python.org, correct?
- Did labels previously work with a packaged version of bluesky?
- what happens if you roll back to a previous version of the bluesky package?

**Comment by Ellislee1** [comment]
3.10.x was installed from python.org, I've also had this issue with 3.9.x as well after some compat testing today.
Labels have previously worked, and seem to work on my laptop I have tried all released packages from Aug-Dec 2022 to no luck on both 3.10.x and 3.9.x.

In fact I have been getting this now with no UI at all:

```
PS C:\Users\Ellis> bluesky
Using Python-based geo functions
Reading config from C:\Users\Ellis\bluesky\settings.cfg
Reading magnetic variation data
Loading global navigation database...
Reading cache: C:\Users\Ellis\bluesky\cache\navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Accepting event connections on port 11000, and stream connections on port 11001
Discovery is disabled
Loading palette bluesky-default
Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
Using Python-based geo functions
Reading config from C:\Users\Ellis\bluesky\settings.cfg
Reading magnetic variation data
Loading global navigation database...
Reading cache: C:\Users\Ellis\bluesky\cache\navdata.p
pygame 2.1.2 (SDL 2.0.18, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Warning: RTree could not be loaded. areafilter get_intersecting and get_knearest won't work
Using Qt 6.4.2 for windows and widgets
Warning: RTree could not be loaded. areafilter get_intersecting and get_knearest won't work
Reading cache: C:\Users\Ellis\bluesky\cache\aptsurface.p
Qt gui warning: An OpenGL Core Profile was requested, but it is not supported on the current platform. Falling back to a non-Core profile. Note that this might cause rendering issues.
Qt information message:

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python
  *  browser-subprocess-path C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\PyQt6\Qt6\bin\QtWebEngineProcess.exe
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl desktop

Successfully loaded OpenAP performance model
Failed to load BADA performance model
Successfully loaded legacy performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
```

**Comment by jooste** [comment]
Ok, do you know of other things on your computer that may have changed, like video drivers? It's odd that only the text doesn't work anymore.

**Comment by Ellislee1** [comment]
I have managed to get the UI to load again by installing pyQT 5 from the actual bluesky repo. But still no labels. I have checked everything and its in the same config from a few months ago. Something interesting though is the map button also doesnt work. Could these be linked?

**Comment by Ellislee1** [comment]
So after trying to bug fix this for the better part of 2 months I am not any closer unfortunately.
The QT6 version downloads and runs in any any non GUI mode but crashes in a GUI mode. The QT5 version still doesn't yield any labels. It must be drivers or something but they are kept up to date from AMD so I really don't know what the issue could be.

**Comment by jooste** [comment]
Hi @Ellislee1, that's a pity! Since the labels worked before, and previous releases of the bluesky package now give you the same results this problem has to be related to something else in your computer's installation, like gfx drivers. Unfortunately there's not much I can do about this without access to a machine with the same issues. If you have experience with GLSL you could try playing around with the `radarwidget-text.frag` file.

**Comment by Ellislee1** [comment]
I might have a look, thanks @jooste

**Comment by Ellislee1** [comment]
After some fairly exhaustive testing with different OSs, I believe that this issue must be related to my hardware. For reference the machine that this issue is present on is:
```
> AMD Ryzen 7 5800X
> AMD Radeon RX6900 XT 
> 32 GB RAM
> Windows 7,10&11 / Ubuntu
```

**Comment by jooste** [comment]
Hi @Ellislee1, thanks a lot for the update. If I come across a machine with similar specs I'll do some more testing!
