### ISSUE TITLE
Link for available aircraft and rotor types is not found

### ISSUE THREAD

**Issue by juliedhj** [TUDelft-CNS-ATM/bluesky#456]
On the site https://github.com/TUDelft-CNS-ATM/bluesky/wiki/openap, there is a link to the aircraft types and the rotor types. When navigating to those link it says "The 'TUDelft-CNS-ATM/bluesky' repository doesn't contain the 'data/performance/OpenAP/fixwing/aircraft.json' path in 'master'."

**Comment by amorfinv** [comment]
Hello @juliedhj . The BlueSky structure has been slightly modified since that page was last edited. The aircraft types are now [here](https://github.com/TUDelft-CNS-ATM/bluesky/tree/master/bluesky/resources/performance/OpenAP).

**Comment by jooste** [comment]
I've now also fixed the links on the wiki, thanks for notifying!
