### ISSUE TITLE
Reading Cache

### ISSUE THREAD

**Issue by uriibra** [TUDelft-CNS-ATM/bluesky#463]
Hi, i've been trying to run bluesky, and when i run it, stays freezed on Loading global navigation database...
Reading cache: C:\Users\breic\Desktop\bluesky1\bluesky-master\cache\navdata.p.
I tried to run the check.py and this is the output: 

Checking for numpy               [OK]
Checking for scipy               [OK]
Checking for matplotlib          [OK]
Checking for pyqt                [QT 6.5.0]
Checking for pyopengl            [OK]
OpenGL module version is         [3.1.7]
Checking GL capabilities         Traceback (most recent call last):

  File "C:\Users\breic\Desktop\bluesky1\bluesky-master\check.py", line 73, in <module>
    if not QGLFormat.hasOpenGL():

AttributeError: type object 'QSurfaceFormat' has no attribute 'hasOpenGL'

I'm not sure what to do next, someone knows? Thank you!

**Comment by uriibra** [comment]
For anyone on the same situation, It seems that i faind the problem. Pyqt6 doesnt have the checks, to solve this you only need to open the check.py document and delete  the qt check. This worked for me!

**Comment by jooste** [comment]
Thanks, indeed `check.py` needs an update for Qt6!

**Comment by jooste** [comment]
Qt / GL checks have been revised in 09df986.
