### ISSUE TITLE
Adding text information to both waypoints and aircraft

### ISSUE THREAD

**Issue by nl22-nmsu** [TUDelft-CNS-ATM/bluesky#478]
Hello,

I'm running a simulation and it'd be nice to display certain pieces of information (numbers and strings) that get updated regularly in Bluesky. Is there already a method implemented to do this?

The idea is to have a number or string printed next to a waypoint of interest. Similarly, a number or string that is "attached" to the aircraft. I know the aircraft already have information attached to them so I imagine there is a simple way to add that information. 

Thanks in advance.

**Comment by ProfHoekstra** [comment]
There is no command for that right now. If it is from a plug-in. There is a workaround that you could try: change the name of the aircraft or create a waypoint with the same but longer name at that location. Custom waypoint can be createdto display info anyway. I know pilots do this sometimes in their FMS as a joke for the next crew. ;)

Changing the name of an aircraft might be a bit risky as it is sometimes used as a reference internally. And it does affect your data logging. Still, worth a try maybe?

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 25 Aug 2023, at 16:28, nl22-nmsu ***@***.***> wrote:

﻿

Hello,

I'm running a simulation and it'd be nice to display certain pieces of information (numbers and strings) that get updated regularly in Bluesky. Is there already a method implemented to do this?

The idea is to have a number or string printed next to a waypoint of interest. Similarly, a number or string that is "attached" to the aircraft. I know the aircraft already have information attached to them so I imagine there is a simple way to add that information.

Thanks in advance.

**Comment by nl22-nmsu** [comment]
Alright, I'll try that workaround for the waypoints!

I can't change the names of the aircraft, that will mess some things up. The aircraft displays the speed information though, is there not a way to manually add a row to the displayed agent info? Alternatively, I don't really need to see the aircraft speed, could I replace the speed with other data (without changing the speed of course)?

**Comment by nl22-nmsu** [comment]
For the waypoint text, using your suggested workaround, how do you delete the waypoint from the map? delwpt is the only option I see related to that and seems to be only for deleting an aircraft's waypoint, but I need to delete them from the map.

**Comment by ProfHoekstra** [comment]
Do you try the DEL command?

Met vriendelijke groeten,
       Jacco Hoekstra

On 25 Aug 2023, at 19:12, nl22-nmsu ***@***.***> wrote:

﻿

For the waypoint text, using your suggested workaround, how do you delete the waypoint from the map? delwpt is the only option I see related to that and seems to be only for deleting an aircraft's waypoint, but I need to delete them from the map.

**Comment by nl22-nmsu** [comment]
Yes,

I create the wpt using:        defwpt my_wpt_name refference_wpt

I get the confirmation message that the new wpt "my_wpt_name" has been added to navdb.

I've tried:
1) del my_wpt_name
2) delwpt my_wpt_name

**Comment by ProfHoekstra** [comment]
Ok, DEL should have done it. I will add it to the options checked by the DEL command.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 28 Aug 2023, at 19:55, nl22-nmsu ***@***.***> wrote:

﻿

Yes,

I create the wpt using: defwpt my_wpt_name refference_wpt

I get the confirmation message that the new wpt "my_wpt_name" has been added to navdb.

I've tried:

  1.  del my_wpt_name
  2.  delwpt my_wpt_name

**Comment by ProfHoekstra** [comment]
P.S. DELWPT is the opposite of the ADDWPT and the argument is hence a “waypoint in route”. This command can not be used for DEFWPT waypoints without causing ambiguities, hence it will be added to the DEL command.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 28 Aug 2023, at 19:55, nl22-nmsu ***@***.***> wrote:

﻿

Yes,

I create the wpt using: defwpt my_wpt_name refference_wpt

I get the confirmation message that the new wpt "my_wpt_name" has been added to navdb.

I've tried:

  1.  del my_wpt_name
  2.  delwpt my_wpt_name

**Comment by nl22-nmsu** [comment]
Great! Thank you! How can I update my bluesky to include these changes once you make them?

**Comment by ProfHoekstra** [comment]
It will be in the master version after I’ve tested it.

**Comment by ProfHoekstra** [comment]
If you update to the latest master version you should be able to delete custom waypoints. It is implemented slightly different from what I suggested before. It is now an option of DEFWPT. When the wptype is DEL or DELETE, the waypoint will be deleted. See also wiki command reference.

Example usage:
DEFWPT NORTH,52.35,4.02      Adds a custom waypoint w/o type
DEFWPT SOUTH,52.35,4.02,FIX  Adds a custom waypoint of type FIX
DEFWPT NORTH,,DEL            Deletes/removes a custom waypoint
DEFWPT SOUTH,,DEL            Deletes/removes a custom waypoint
