### ISSUE TITLE
Initialization as a python package issue

### ISSUE THREAD

**Issue by borisdjartov** [TUDelft-CNS-ATM/bluesky#485]
Hi guys,

I am trying to import bluesky as a python package as you demonstrate in your notebook. However when i run:

bs.init(mode='sim', detached=True)

i get the following error:

File "d:\Simulation\test.py", line 3, in <module>
    bs.init(mode='sim', detached=True)
  File "C:\Users\djar_bo\AppData\Local\Programs\Python\Python39\lib\site-packages\bluesky\__init__.py", line 72, in init
    tools.init()
  File "C:\Users\djar_bo\AppData\Local\Programs\Python\Python39\lib\site-packages\bluesky\tools\__init__.py", line 20, in init
    geo.initdecl_data()
  File "C:\Users\djar_bo\AppData\Local\Programs\Python\Python39\lib\site-packages\bluesky\tools\geo.py", line 495, in initdecl_data
    dec_table = np.genfromtxt(bs.resource(bs.settings.navdata_path) / 'geo_declination_data.csv',
AttributeError: module 'bluesky.settings' has no attribute 'navdata_path'

A while back i used it as a python package and did not have this issue, could you provide any help?

Kind regards,
Boris

**Comment by jooste** [comment]
Hi @borisdjartov, 

Are you trying this with the bluesky-simulator pip package? When I try this in ipython:

```python
import bluesky as bs
bs.init(mode='sim', detached=True)
```
it works as expected. Package versions in my case are:
```
bluesky-guidata     2022.9.18
bluesky-simdata     2022.9.18
bluesky-simulator   2022.10.19
```
Although it shouldn't matter, what you could try is to edit your bluesky.cfg file in $HOME/bluesky, and add
```
navdata_path = 'navdata'
```

**Comment by borisdjartov** [comment]
Hi jooste, apologies for the late reply. There is not bluesky.cfg file. When i run pip install bluesky-simulator[full] and check my installation folder in python there is no .cfg file. I am not sure how to continue

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/44361789/842252d5-3b7b-46ad-a4f3-1d849faca493)
