### ISSUE TITLE
Switch performance model.

### ISSUE THREAD

**Issue by uriibra** [TUDelft-CNS-ATM/bluesky#486]
Hello, I'm trying to implement OpenAp in Bluesky. I know there is a folder with OpenAp in the bluesky pack. But I'm not really sure if OpenAp is the default performance model used in bluesky. In that case how do I switch to OpenAp in order to be used in my simulations.

Thank you in advance!

**Comment by jooste** [comment]
Hi,

OpenAP is the default performance model, no need to select it manually. Switching to different performance models can be done with the `PERF` command.
