### ISSUE TITLE
QT Gui Fatal Error

### ISSUE THREAD

**Issue by Madaa29** [TUDelft-CNS-ATM/bluesky#490]
Hello, 
When i try to install a new bluesky-simulator with the pip package (bluesky-simulator[full]) I get this error and don't know how to fix it.

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/58108819/b4e3d3e6-9c80-493d-9914-2f0df5c66fe5)

Thanks in advance.

**Comment by jooste** [comment]
Hi @Madaa29,

This is a bug introduced by Qt6 which has been fixed some time ago, but a new package wasn't made yet. I generated an up-to-date pip package just now, please try that one out and see if it fixes your problem!

**Comment by Madaa29** [comment]
It worked ! Thanks a lot for the speed of response ! :)
