### ISSUE TITLE
Is there any built- in function to calculate distance travel by the single aircraft?

### ISSUE THREAD

**Issue by Grey-Hat-07** [TUDelft-CNS-ATM/bluesky#492]
Note: While traveling one point to another the aircraft taking 100s of turns. <br/> The function must calculate the total distance traveled by the aircraft

**Comment by Grey-Hat-07** [comment]
Note: while traveling one point to another the aircraft taking 100s of turns.

**Comment by jooste** [comment]
The total track distance flown for each aircraft is stored in `traf.distflown`. You can use it in a plugin like this:
```python
import bluesky as bs

def somefunction():
    print(bs.traf.distflown)
```
You can also plot it while running bluesky: `PLOT traf.distflown`

Or log it to a CSV file with the following commands:
```
CRELOG MYLOG 1.0
MYLOG ADD traf.id traf.distflown
MYLOG ON
```

**Comment by Grey-Hat-07** [comment]
thanks, it is working.

**Comment by Grey-Hat-07** [comment]
Is there any similar exists for time taken by the aircraft to complete the trip?

**Comment by jooste** [comment]
No, although if you are using a logger you can take the difference of the timestep of first occurrence of a callsign and the last occurrence.
