### ISSUE TITLE
How to import flightradar 24 csv file into bluesky

### ISSUE THREAD

**Issue by Amitoj-26** [TUDelft-CNS-ATM/bluesky#497]
Please provide me sol thnks

**Comment by andubadea** [comment]
Hi!

BlueSky doesn't currently have a way to import FlightRadar24 historical data CSV files. However, you can probably create a script to convert these CSV files to BlueSky scenarios. You can create a .scn file and add commands to it in the right order.

The relevant documentation for commands can be found here:
https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Command-Reference
These commands can be chained and put in a .scn file with a time stamp. Check out one of the example scenarios to see how this can be done:
https://github.com/TUDelft-CNS-ATM/bluesky/blob/master/scenario/simpleRoute.scn

To make the aircraft closely follow the historical data, you can add the waypoints from the CSV file together with their speed and altitude constraints (ADDWPT command) and then tell the aircraft when it needs to be at each waypoint by using the RTA command together with the timestamp of the waypoint given in the CSV (converted to HH:MM:SS in simulation time).

**Comment by Amitoj-26** [comment]
Thnks for the reply can u send me by doing this practically in it

**Comment by Amitoj-26** [comment]
Sir i did nt get it

**Comment by Amitoj-26** [comment]
Please help me

**Comment by Amitoj-26** [comment]
Can u help me

**Comment by Amitoj-26** [comment]
??

**Comment by jooste** [comment]
There are several examples of scenario creation scripts in the folder `utils/Scenario-creator`. These should give you enough inspiration to create your own script!
