### ISSUE TITLE
How to simulate air traffic of your aerodrome in bluesky. Where is the source code of bluesky to read ?

### ISSUE THREAD

**Issue by Amitoj-26** [TUDelft-CNS-ATM/bluesky#498]
Please provide reply

**Comment by andubadea** [comment]
Hi! You can find the source code by selecting the <> Code tab from this page:

<img width="548" alt="Screenshot 2024-02-23 at 09 17 59" src="https://github.com/TUDelft-CNS-ATM/bluesky/assets/37139260/8cf653cf-038b-4087-9ecb-15e8369ed9d1">

Then, the "bluesky" folder contains the source code for the simulator.

As for simulating air traffic, check out this tutorial:
https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Editing-flight-plans
