### ISSUE TITLE
Failed to load BADA performance model

### ISSUE THREAD

**Issue by hw-kim-ivan** [TUDelft-CNS-ATM/bluesky#508]
Dear TUDelft,

"Failed to load BADA performance model" message is shown when running 'python_demo.ipynb'.

According to the README file, I've added all BADA files including APF, OPF, PTD, SYNONYM, ReleaseSummary, and changed performance_model from 'openap' to 'bada' in default.cfg.

Is this due to a compatibility issue between BlueSky and BADA 3.10 and 3.16, or am I missing some procedure to load the BADA model?

Thank you in advance,
HW.

**Comment by jooste** [comment]
Hi @hw-kim-ivan!

Where did you put your BADA files? If you cloned/forked/copied bluesky from github they should be in `bluesky/resources/performance/BADA`

**Comment by hw-kim-ivan** [comment]
Dear @jooste,

I cloned the code and indeed put BADA files to `bluesky/resources/performance/BADA` where README file exists.
Below are the files located in the above directory.

APF, OPF, PTD, PTF files of many aircraft, README.md, ReleaseSummary, SYNONYM.NEW

**Comment by jooste** [comment]
Ok, it's not immediately clear what's happening then. It could be related to the file format having changed, or otherwise an issue that was introduced with an earlier change in BlueSky. The latter one we can check

**Comment by hw-kim-ivan** [comment]
Thank you for your support. I'll see what I can do to resolve the issue and get back to you with good news.

**Comment by tinpusher** [comment]
Is that on a Mac or PC?

**Comment by hw-kim-ivan** [comment]
hello! @tinpusher.

It's on Window11.

**Comment by tinpusher** [comment]
OOK, the reason for the question, I have Mac and win10, win 10 happy with version 3.10 and 3.15, but Mac happy with 3.10 but not 3.15.

**Comment by hw-kim-ivan** [comment]
Dear @jooste and @tinpusher.

I solved the problem by editing the bada file's directory on settings.cfg in `root`, rather than on default.cfg in `bluesky/resources/performance/BADA`.

Besides, the program successfully loads BADA 3.10, but prints out `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 390: invalid continuation byte` error when parsing BADA 3.16 files.

Parsing errors are beyond the scope of this issue, so let's close this issue.
Thank you for your support.
