### ISSUE TITLE
Create conflict detection between aircraft pairs

### ISSUE THREAD

**Issue by Amitoj-26** [TUDelft-CNS-ATM/bluesky#509]
What list of command and sequence of steps can be used to create conflict between aircraft pairs using bluesky

**Comment by jooste** [comment]
Hi @Amitoj-26, you can use the [CRECONFS](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/creconfs) command for this!

**Comment by Amitoj-26** [comment]
Sir can you give example to demonstrate use of command

**Comment by jooste** [comment]
`CRECONFS` creates a new aircraft that is in conflict with the provided reference aircraft. So for example

```
CRE KL204 B744 52 4 0 FL300 250
CRECONFS KL205 B744 KL204 90 1 120 0 0 300
ASAS ON
```

`ASAS ON` is there so that the conflict is also detected with bluesky's state-based CD

**Comment by Amitoj-26** [comment]
Thanks I will try
