### ISSUE TITLE
import csv file containig huge data into bluesky

### ISSUE THREAD

**Issue by Amitoj-26** [TUDelft-CNS-ATM/bluesky#512]
I just want to state that i had csv file of flightradar24 historical data of one aircraft going from source to destination in terms of timestamp , date, lat ,long, heading, speed, altitude. i want to simulate this file inside bluesky. writing scenario file for such long data is not feasible, plz provide me solution . thnks ?

**Comment by jooste** [comment]
Hi @Amitoj-26, the idea is still to write a script that processes the csv file and generate a scenario file. To get to a reasonable number of waypoints from historical tracks you can use something like Ramer-Douglas-Peucker to reduce the number of trajectory points. Use the resulting lower resolution trajectory to make a route with waypoints.

**Comment by Amitoj-26** [comment]
Didnt understood sir

**Comment by jooste** [comment]
Ramer Douglas Peucker:
[wiki explanation](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)

[python package](https://pypi.org/project/rdp/#:~:text=Python%2FNumPy%20implementation%20of%20the,by%20a%20series%20of%20points.)

Example scripts that generate bluesky scenario files are on the bluesky repo under `utils`

**Comment by Amitoj-26** [comment]
Thanks, I'll check it out.

**Comment by Amitoj-26** [comment]
Sir can you do it for me as examole i have shared you csv file on linkedin

**Comment by tinpusher** [comment]
You might find filtering (dataset reduction), might be easier to filter on the timestamp. A typical ATC display system has an update every 3-5 seconds.  Depending on what fidelity you require. 360kts equates to 6nm per minute.
