### ISSUE TITLE
Aircraft not following airways

### ISSUE THREAD

**Issue by Kriso23** [TUDelft-CNS-ATM/bluesky#523]
Hi there I am trying to get an aircraft to fly along a route however it doesn't follow the airway. Is there no way to get the aircraft to fly along an airway? I've tried the different ADDWPTMODEs like flyby and flyover and I can't get the airplane to fly along the airway connecting 2 waypoints. Am I missing something?

The aircraft are crossing the waypoints but not flying along the airways in between. 

Hopefully somebody can point me in the right direction? Thanks in advance!

https://github.com/user-attachments/assets/af4d23e1-bd27-49cf-b7dc-48d7146bcba0

**Comment by ProfHoekstra** [comment]
Do you mean route or airway? When following an airway it is necessary to add all waypoints to the route, when just the beginning and end of the section of the airway, it will do just that. Aircraft do not always follow the airways so BlueSky could not know which waypoints to pass or to skip. That is why it has been put in explicitly, The AIRWAY command is just like POS an information command.

If this does not help, then send me the scenario file, which illustrates the problem.

Best regards,
     Jacco Hoekstra

From: Kriso23 ***@***.***>
Sent: maandag 19 augustus 2024 17:21
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] Aircraft not following airways (Issue #523)


Hi there I am trying to get an aircraft to fly along a route however it doesn't follow the airway. Is there no way to get the aircraft to fly along an airway? I've tried the different ADDWPTMODEs like flyby and flyover and I can't get the airplane to fly along the airway connecting 2 waypoints. Am I missing something?

The aircraft are crossing the waypoints but not flying along the airways in between.

https://github.com/user-attachments/assets/af4d23e1-bd27-49cf-b7dc-48d7146bcba0

-

**Comment by Kriso23** [comment]
Hi there, thank you for the quick reply.

Actually I was using route and airway interchangeably but I mean route. I thought by adding waypoints to an aircraft that it would fly along the straight lines that connect them. In the video I posted the aircraft does not fly along the magenta line even though I added all 3 waypoints (NICSO, 48N50, 50N40 and some further points outside the viewport). There is probably some setup definition I am missing...

Here is my scenario file:

```
#This is an eastbound crossing test scenario.

# Display setup
00:00:00.00>PAN 41.95848674930467, -68.68646506428104
00:00:00.00>ZOOM 0.1

# AREA definition
00:00:00.00>BOX,SIMAREA, 60, -60, 40, 5
00:00:00.00>AREA,SIMAREA

# Add entry waypoint
00:00:00.00>DEFWPT NICSO, 47.500000, -52.000000, FIX



# AUA001 on track Z
00:00:00>CRE,AUA001,B744, 47.500000, -52.5, 090, 32000, .82
00:00:02>AUA001 DEST LOWW
00:00:02>AUA001 ADDWPT NICSO
00:00:02>AUA001 ADDWPT 48N50, , .82
00:00:02>AUA001 ADDWPT 50N40, , .82
00:00:02>AUA001 ADDWPT 50N30, , .82
00:00:02>AUA001 ADDWPT 49N20, , .82
00:00:05>AUA001 LNAV ON
00:00:05>AUA001 VNAV ON
```

**Comment by ProfHoekstra** [comment]
Thanks, this helps! Just tried your commands in a scenario file and it seems to run just fine. The deviation you see on the display is due to the projection. The autopilot flies a great circle between the waypoints. Due to the Mercator projection we use on screen, you will see a deviation from the straight kine. This is also why the deviation seems large on the last leg: this is the longest leg.

So the drawing of straight line for the route drawn on screen is an approximation. In reality the route is slightly more complex, due to waypoint passing logic and the spherical earth.

Hope this answers your question.

Best regards,
     Jacco Hoekstra

**Comment by Kriso23** [comment]
Ahh that makes sense! I had a feeling that might be the case, well good to know that it is working as expected. Thank you for the tool so far, really helpful for my bachelor thesis!
