### ISSUE TITLE
True Airspeed display

### ISSUE THREAD

**Issue by n-wuttiphan** [TUDelft-CNS-ATM/bluesky#524]
Hi BlueSky Team, 

I want the interface to display the true airspeed value instead of the usual calibrated airspeed. I have edited some lines of code from screen.py by changing the variable 'cas' to 'tas'. Nonetheless, it still displays 'cas'. Can you please help me point out what I did wrong? The edited section is on screen.py, I changed 'cas' to 'tas' in if sentences as shown below.

                if self.swlabel > 2:
                    tas = bs.traf.tas[i] / kts        #changed cas to tas
                    label.append(str(int(round(tas))))  # changed cas to tas
                else:
                    label.append(" ")
                
                # Check for changes in traffic label text
                if  not (type(bs.traf.label[i])==list) or \
                      not (type(bs.traf.label[i][3])==str) or \
                        not (label[:3] == bs.traf.label[i][:3]):

                    bs.traf.label[i] = []
                    labelbmp = pg.Surface((100, 60), 0, self.win)
                    if not bs.traf.cd.inconf[i]:
                        acfont = self.fontrad
                    else:
                        acfont = self.fontamb

                    acfont.printat(labelbmp, 0, 0, label[0])
                    acfont.printat(labelbmp, 0, dy, label[1])
                    acfont.printat(labelbmp, 0, 2 * dy, label[2])

                    bs.traf.label[i].append(label[0])
                    bs.traf.label[i].append(label[1])
                    bs.traf.label[i].append(label[2])
                    bs.traf.label[i].append(labelbmp)
                    
          

                # Blit label
                dest = bs.traf.label[i][3].get_rect()
                dest.top = trafy[i] - 5
                dest.left = trafx[i] + 15
                self.win.blit(bs.traf.label[i][3], dest, None, pg.BLEND_ADD)

**Comment by ProfHoekstra** [comment]
Your edit is good, but this only affects the pygame interface. Check out the gltraffic.py in lines 295-297 for the QtGL interface, that's where you can change it.

From: NineNW ***@***.***>
Sent: dinsdag 27 augustus 2024 10:09
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] True Airspeed disply (Issue #524)


Hi BlueSky Team,

I want the interface to display the true airspeed value instead of the usual calibrated airspeed. I have edited some lines of code from screen.py by changing the variable 'cas' to 'tas'. Nonetheless, it still displays 'cas'. Can you please help me point out what I did wrong? The edited section is on screen.py, I changed 'cas' to 'tas' in bold characters as shown below.

            if self.swlabel > 2:

                **tas** = bs.traf.**tas**[i] / kts

                label.append(str(int(round(**tas**))))  # line 3 of label: speed

            else:

                label.append(" ")



            # Check for changes in traffic label text

            if  not (type(bs.traf.label[i])==list) or \

                  not (type(bs.traf.label[i][3])==str) or \

                    not (label[:3] == bs.traf.label[i][:3]):



                bs.traf.label[i] = []

                labelbmp = pg.Surface((100, 60), 0, self.win)

                if not bs.traf.cd.inconf[i]:

                    acfont = self.fontrad

                else:

                    acfont = self.fontamb



                acfont.printat(labelbmp, 0, 0, label[0])

                acfont.printat(labelbmp, 0, dy, label[1])

                acfont.printat(labelbmp, 0, 2 * dy, label[2])



                bs.traf.label[i].append(label[0])

                bs.traf.label[i].append(label[1])

                bs.traf.label[i].append(label[2])

                bs.traf.label[i].append(labelbmp)







            # Blit label

            dest = bs.traf.label[i][3].get_rect()

            dest.top = trafy[i] - 5

            dest.left = trafx[i] + 15

            self.win.blit(bs.traf.label[i][3], dest, None, pg.BLEND_ADD)

-

**Comment by n-wuttiphan** [comment]
Thank you for the answer. I sincerely appreciate it.
