### ISSUE TITLE
Modifying fix.dat

### ISSUE THREAD

**Issue by Kriso23** [TUDelft-CNS-ATM/bluesky#527]
Hi there,
I want to rename some of the fixes and add some new ones such as H3950 (these waypoints exist in the current airac). I know I could use DEFWPT but is there anyway to actually modify the fix.dat file in the resources folder? Because nothing changes when I modify it. Is there some command to refresh the navdb?

Kind regards,
Kristian Todt

**Comment by tinpusher** [comment]
Two things to try, (1) is it reading the correct folder accoring to the settings.cfg.
(2) if correct it sounds like is not detecting a change to the file, try removing (move out) of the cache directory, and let bluesky recreate the .dat file(s)

**Comment by Kriso23** [comment]
(2) seems to work thanks!
