### ISSUE TITLE
How can I simulate an airplane landing

### ISSUE THREAD

**Issue by crixus5678** [TUDelft-CNS-ATM/bluesky#531]
Hi Team, 

I'm working on a project and I want to assess if the airspace can handle X amount of airplane movement without any planes encountering loss of separation. As a start, I was hoping I could land a plane in an airport before trying to do a larger-scale simulation. I'm wondering if there is any example that I can follow for landing an aircraft?

Best Regards

**Comment by crixus5678** [comment]
okay seems like 0-VNAV-Landing.SCN is a good start

**Comment by jooste** [comment]
Hi @crixus5678,

Good that you found one, there are indeed a couple of example scenarios. Note that aircraft do not automatically disappear once they land. You can do this manually, or via the AREA plugin, using the command `TAXI OFF <alt>`. Once set, aircraft will be deleted from the simulation once their altitude sinks below the specified altitude `<alt>`.

**Comment by crixus5678** [comment]
thanks for the tips, i was still wondering how come it move out of the airport.
Added the following to the scn file and it seems like it works
0:00:00.00>TAXI OFF 1
